// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryCommitmentTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCommitmentTreeRequest) Reset() {
	*x = QueryCommitmentTreeRequest{}
	mi := &file_zvote_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentTreeRequest) ProtoMessage() {}

func (x *QueryCommitmentTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentTreeRequest.ProtoReflect.Descriptor instead.
func (*QueryCommitmentTreeRequest) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryCommitmentTreeRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type QueryCommitmentTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *CommitmentTreeState   `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCommitmentTreeResponse) Reset() {
	*x = QueryCommitmentTreeResponse{}
	mi := &file_zvote_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCommitmentTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCommitmentTreeResponse) ProtoMessage() {}

func (x *QueryCommitmentTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCommitmentTreeResponse.ProtoReflect.Descriptor instead.
func (*QueryCommitmentTreeResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryCommitmentTreeResponse) GetTree() *CommitmentTreeState {
	if x != nil {
		return x.Tree
	}
	return nil
}

type QueryLatestTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestTreeRequest) Reset() {
	*x = QueryLatestTreeRequest{}
	mi := &file_zvote_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestTreeRequest) ProtoMessage() {}

func (x *QueryLatestTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestTreeRequest.ProtoReflect.Descriptor instead.
func (*QueryLatestTreeRequest) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryLatestTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *CommitmentTreeState   `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLatestTreeResponse) Reset() {
	*x = QueryLatestTreeResponse{}
	mi := &file_zvote_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLatestTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLatestTreeResponse) ProtoMessage() {}

func (x *QueryLatestTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLatestTreeResponse.ProtoReflect.Descriptor instead.
func (*QueryLatestTreeResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryLatestTreeResponse) GetTree() *CommitmentTreeState {
	if x != nil {
		return x.Tree
	}
	return nil
}

type QueryVoteRoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteRoundRequest) Reset() {
	*x = QueryVoteRoundRequest{}
	mi := &file_zvote_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteRoundRequest) ProtoMessage() {}

func (x *QueryVoteRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteRoundRequest.ProtoReflect.Descriptor instead.
func (*QueryVoteRoundRequest) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryVoteRoundRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryVoteRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         *VoteRound             `protobuf:"bytes,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVoteRoundResponse) Reset() {
	*x = QueryVoteRoundResponse{}
	mi := &file_zvote_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVoteRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVoteRoundResponse) ProtoMessage() {}

func (x *QueryVoteRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVoteRoundResponse.ProtoReflect.Descriptor instead.
func (*QueryVoteRoundResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVoteRoundResponse) GetRound() *VoteRound {
	if x != nil {
		return x.Round
	}
	return nil
}

type QueryProposalTallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalTallyRequest) Reset() {
	*x = QueryProposalTallyRequest{}
	mi := &file_zvote_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalTallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalTallyRequest) ProtoMessage() {}

func (x *QueryProposalTallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalTallyRequest.ProtoReflect.Descriptor instead.
func (*QueryProposalTallyRequest) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryProposalTallyRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *QueryProposalTallyRequest) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type QueryProposalTallyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mapping from vote_decision to serialized ElGamal ciphertext (64 bytes each).
	Tally         map[uint32][]byte `protobuf:"bytes,1,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProposalTallyResponse) Reset() {
	*x = QueryProposalTallyResponse{}
	mi := &file_zvote_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProposalTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProposalTallyResponse) ProtoMessage() {}

func (x *QueryProposalTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProposalTallyResponse.ProtoReflect.Descriptor instead.
func (*QueryProposalTallyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryProposalTallyResponse) GetTally() map[uint32][]byte {
	if x != nil {
		return x.Tally
	}
	return nil
}

type QueryTallyResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultsRequest) Reset() {
	*x = QueryTallyResultsRequest{}
	mi := &file_zvote_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultsRequest) ProtoMessage() {}

func (x *QueryTallyResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultsRequest.ProtoReflect.Descriptor instead.
func (*QueryTallyResultsRequest) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTallyResultsRequest) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

type QueryTallyResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TallyResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTallyResultsResponse) Reset() {
	*x = QueryTallyResultsResponse{}
	mi := &file_zvote_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTallyResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTallyResultsResponse) ProtoMessage() {}

func (x *QueryTallyResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTallyResultsResponse.ProtoReflect.Descriptor instead.
func (*QueryTallyResultsResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryTallyResultsResponse) GetResults() []*TallyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_zvote_v1_query_proto protoreflect.FileDescriptor

const file_zvote_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x14zvote/v1/query.proto\x12\bzvote.v1\x1a\x14zvote/v1/types.proto\"4\n" +
	"\x1aQueryCommitmentTreeRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"P\n" +
	"\x1bQueryCommitmentTreeResponse\x121\n" +
	"\x04tree\x18\x01 \x01(\v2\x1d.zvote.v1.CommitmentTreeStateR\x04tree\"\x18\n" +
	"\x16QueryLatestTreeRequest\"L\n" +
	"\x17QueryLatestTreeResponse\x121\n" +
	"\x04tree\x18\x01 \x01(\v2\x1d.zvote.v1.CommitmentTreeStateR\x04tree\";\n" +
	"\x15QueryVoteRoundRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"C\n" +
	"\x16QueryVoteRoundResponse\x12)\n" +
	"\x05round\x18\x01 \x01(\v2\x13.zvote.v1.VoteRoundR\x05round\"`\n" +
	"\x19QueryProposalTallyRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\"\x9d\x01\n" +
	"\x1aQueryProposalTallyResponse\x12E\n" +
	"\x05tally\x18\x01 \x03(\v2/.zvote.v1.QueryProposalTallyResponse.TallyEntryR\x05tally\x1a8\n" +
	"\n" +
	"TallyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\">\n" +
	"\x18QueryTallyResultsRequest\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"L\n" +
	"\x19QueryTallyResultsResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.zvote.v1.TallyResultR\aresults2\xd0\x03\n" +
	"\x05Query\x12e\n" +
	"\x16CommitmentTreeAtHeight\x12$.zvote.v1.QueryCommitmentTreeRequest\x1a%.zvote.v1.QueryCommitmentTreeResponse\x12[\n" +
	"\x14LatestCommitmentTree\x12 .zvote.v1.QueryLatestTreeRequest\x1a!.zvote.v1.QueryLatestTreeResponse\x12N\n" +
	"\tVoteRound\x12\x1f.zvote.v1.QueryVoteRoundRequest\x1a .zvote.v1.QueryVoteRoundResponse\x12Z\n" +
	"\rProposalTally\x12#.zvote.v1.QueryProposalTallyRequest\x1a$.zvote.v1.QueryProposalTallyResponse\x12W\n" +
	"\fTallyResults\x12\".zvote.v1.QueryTallyResultsRequest\x1a#.zvote.v1.QueryTallyResultsResponseB&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_query_proto_rawDescOnce sync.Once
	file_zvote_v1_query_proto_rawDescData []byte
)

func file_zvote_v1_query_proto_rawDescGZIP() []byte {
	file_zvote_v1_query_proto_rawDescOnce.Do(func() {
		file_zvote_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_query_proto_rawDesc), len(file_zvote_v1_query_proto_rawDesc)))
	})
	return file_zvote_v1_query_proto_rawDescData
}

var file_zvote_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_zvote_v1_query_proto_goTypes = []any{
	(*QueryCommitmentTreeRequest)(nil),  // 0: zvote.v1.QueryCommitmentTreeRequest
	(*QueryCommitmentTreeResponse)(nil), // 1: zvote.v1.QueryCommitmentTreeResponse
	(*QueryLatestTreeRequest)(nil),      // 2: zvote.v1.QueryLatestTreeRequest
	(*QueryLatestTreeResponse)(nil),     // 3: zvote.v1.QueryLatestTreeResponse
	(*QueryVoteRoundRequest)(nil),       // 4: zvote.v1.QueryVoteRoundRequest
	(*QueryVoteRoundResponse)(nil),      // 5: zvote.v1.QueryVoteRoundResponse
	(*QueryProposalTallyRequest)(nil),   // 6: zvote.v1.QueryProposalTallyRequest
	(*QueryProposalTallyResponse)(nil),  // 7: zvote.v1.QueryProposalTallyResponse
	(*QueryTallyResultsRequest)(nil),    // 8: zvote.v1.QueryTallyResultsRequest
	(*QueryTallyResultsResponse)(nil),   // 9: zvote.v1.QueryTallyResultsResponse
	nil,                                 // 10: zvote.v1.QueryProposalTallyResponse.TallyEntry
	(*CommitmentTreeState)(nil),         // 11: zvote.v1.CommitmentTreeState
	(*VoteRound)(nil),                   // 12: zvote.v1.VoteRound
	(*TallyResult)(nil),                 // 13: zvote.v1.TallyResult
}
var file_zvote_v1_query_proto_depIdxs = []int32{
	11, // 0: zvote.v1.QueryCommitmentTreeResponse.tree:type_name -> zvote.v1.CommitmentTreeState
	11, // 1: zvote.v1.QueryLatestTreeResponse.tree:type_name -> zvote.v1.CommitmentTreeState
	12, // 2: zvote.v1.QueryVoteRoundResponse.round:type_name -> zvote.v1.VoteRound
	10, // 3: zvote.v1.QueryProposalTallyResponse.tally:type_name -> zvote.v1.QueryProposalTallyResponse.TallyEntry
	13, // 4: zvote.v1.QueryTallyResultsResponse.results:type_name -> zvote.v1.TallyResult
	0,  // 5: zvote.v1.Query.CommitmentTreeAtHeight:input_type -> zvote.v1.QueryCommitmentTreeRequest
	2,  // 6: zvote.v1.Query.LatestCommitmentTree:input_type -> zvote.v1.QueryLatestTreeRequest
	4,  // 7: zvote.v1.Query.VoteRound:input_type -> zvote.v1.QueryVoteRoundRequest
	6,  // 8: zvote.v1.Query.ProposalTally:input_type -> zvote.v1.QueryProposalTallyRequest
	8,  // 9: zvote.v1.Query.TallyResults:input_type -> zvote.v1.QueryTallyResultsRequest
	1,  // 10: zvote.v1.Query.CommitmentTreeAtHeight:output_type -> zvote.v1.QueryCommitmentTreeResponse
	3,  // 11: zvote.v1.Query.LatestCommitmentTree:output_type -> zvote.v1.QueryLatestTreeResponse
	5,  // 12: zvote.v1.Query.VoteRound:output_type -> zvote.v1.QueryVoteRoundResponse
	7,  // 13: zvote.v1.Query.ProposalTally:output_type -> zvote.v1.QueryProposalTallyResponse
	9,  // 14: zvote.v1.Query.TallyResults:output_type -> zvote.v1.QueryTallyResultsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_zvote_v1_query_proto_init() }
func file_zvote_v1_query_proto_init() {
	if File_zvote_v1_query_proto != nil {
		return
	}
	file_zvote_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_query_proto_rawDesc), len(file_zvote_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zvote_v1_query_proto_goTypes,
		DependencyIndexes: file_zvote_v1_query_proto_depIdxs,
		MessageInfos:      file_zvote_v1_query_proto_msgTypes,
	}.Build()
	File_zvote_v1_query_proto = out.File
	file_zvote_v1_query_proto_goTypes = nil
	file_zvote_v1_query_proto_depIdxs = nil
}
