// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: zvote/v1/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_CommitmentTreeAtHeight_FullMethodName = "/zvote.v1.Query/CommitmentTreeAtHeight"
	Query_LatestCommitmentTree_FullMethodName   = "/zvote.v1.Query/LatestCommitmentTree"
	Query_VoteRound_FullMethodName              = "/zvote.v1.Query/VoteRound"
	Query_ProposalTally_FullMethodName          = "/zvote.v1.Query/ProposalTally"
	Query_TallyResults_FullMethodName           = "/zvote.v1.Query/TallyResults"
	Query_CommitmentLeaves_FullMethodName       = "/zvote.v1.Query/CommitmentLeaves"
	Query_ActiveRound_FullMethodName            = "/zvote.v1.Query/ActiveRound"
	Query_CeremonyState_FullMethodName          = "/zvote.v1.Query/CeremonyState"
	Query_VoteManager_FullMethodName            = "/zvote.v1.Query/VoteManager"
	Query_VoteSummary_FullMethodName            = "/zvote.v1.Query/VoteSummary"
	Query_ListRounds_FullMethodName             = "/zvote.v1.Query/ListRounds"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the vote module's gRPC query service.
type QueryClient interface {
	// CommitmentTreeAtHeight returns the commitment tree root at a specific anchor height.
	CommitmentTreeAtHeight(ctx context.Context, in *QueryCommitmentTreeRequest, opts ...grpc.CallOption) (*QueryCommitmentTreeResponse, error)
	// LatestCommitmentTree returns the latest commitment tree state.
	LatestCommitmentTree(ctx context.Context, in *QueryLatestTreeRequest, opts ...grpc.CallOption) (*QueryLatestTreeResponse, error)
	// VoteRound returns information about a specific vote round.
	VoteRound(ctx context.Context, in *QueryVoteRoundRequest, opts ...grpc.CallOption) (*QueryVoteRoundResponse, error)
	// ProposalTally returns the accumulated tally for a proposal within a vote round.
	ProposalTally(ctx context.Context, in *QueryProposalTallyRequest, opts ...grpc.CallOption) (*QueryProposalTallyResponse, error)
	// TallyResults returns finalized tally results for a vote round (after MsgSubmitTally).
	TallyResults(ctx context.Context, in *QueryTallyResultsRequest, opts ...grpc.CallOption) (*QueryTallyResultsResponse, error)
	// CommitmentLeaves returns the commitment tree leaves organized by block height.
	// Used by remote clients implementing TreeSyncApi to sync the vote commitment tree.
	CommitmentLeaves(ctx context.Context, in *QueryCommitmentLeavesRequest, opts ...grpc.CallOption) (*QueryCommitmentLeavesResponse, error)
	// ActiveRound returns the first active voting round, if any.
	// Iterates all stored rounds and returns the first with SESSION_STATUS_ACTIVE.
	ActiveRound(ctx context.Context, in *QueryActiveRoundRequest, opts ...grpc.CallOption) (*QueryActiveRoundResponse, error)
	// CeremonyState returns the current EA key ceremony lifecycle state.
	CeremonyState(ctx context.Context, in *QueryCeremonyStateRequest, opts ...grpc.CallOption) (*QueryCeremonyStateResponse, error)
	// VoteManager returns the current vote manager address.
	VoteManager(ctx context.Context, in *QueryVoteManagerRequest, opts ...grpc.CallOption) (*QueryVoteManagerResponse, error)
	// VoteSummary returns a denormalized view of a vote round with proposals,
	// ballot counts, and (if finalized) decrypted totals. Single query for frontend display.
	VoteSummary(ctx context.Context, in *QueryVoteSummaryRequest, opts ...grpc.CallOption) (*QueryVoteSummaryResponse, error)
	// ListRounds returns all stored vote rounds.
	ListRounds(ctx context.Context, in *QueryListRoundsRequest, opts ...grpc.CallOption) (*QueryListRoundsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CommitmentTreeAtHeight(ctx context.Context, in *QueryCommitmentTreeRequest, opts ...grpc.CallOption) (*QueryCommitmentTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCommitmentTreeResponse)
	err := c.cc.Invoke(ctx, Query_CommitmentTreeAtHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestCommitmentTree(ctx context.Context, in *QueryLatestTreeRequest, opts ...grpc.CallOption) (*QueryLatestTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLatestTreeResponse)
	err := c.cc.Invoke(ctx, Query_LatestCommitmentTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteRound(ctx context.Context, in *QueryVoteRoundRequest, opts ...grpc.CallOption) (*QueryVoteRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVoteRoundResponse)
	err := c.cc.Invoke(ctx, Query_VoteRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProposalTally(ctx context.Context, in *QueryProposalTallyRequest, opts ...grpc.CallOption) (*QueryProposalTallyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryProposalTallyResponse)
	err := c.cc.Invoke(ctx, Query_ProposalTally_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TallyResults(ctx context.Context, in *QueryTallyResultsRequest, opts ...grpc.CallOption) (*QueryTallyResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTallyResultsResponse)
	err := c.cc.Invoke(ctx, Query_TallyResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CommitmentLeaves(ctx context.Context, in *QueryCommitmentLeavesRequest, opts ...grpc.CallOption) (*QueryCommitmentLeavesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCommitmentLeavesResponse)
	err := c.cc.Invoke(ctx, Query_CommitmentLeaves_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveRound(ctx context.Context, in *QueryActiveRoundRequest, opts ...grpc.CallOption) (*QueryActiveRoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryActiveRoundResponse)
	err := c.cc.Invoke(ctx, Query_ActiveRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CeremonyState(ctx context.Context, in *QueryCeremonyStateRequest, opts ...grpc.CallOption) (*QueryCeremonyStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCeremonyStateResponse)
	err := c.cc.Invoke(ctx, Query_CeremonyState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteManager(ctx context.Context, in *QueryVoteManagerRequest, opts ...grpc.CallOption) (*QueryVoteManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVoteManagerResponse)
	err := c.cc.Invoke(ctx, Query_VoteManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteSummary(ctx context.Context, in *QueryVoteSummaryRequest, opts ...grpc.CallOption) (*QueryVoteSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryVoteSummaryResponse)
	err := c.cc.Invoke(ctx, Query_VoteSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListRounds(ctx context.Context, in *QueryListRoundsRequest, opts ...grpc.CallOption) (*QueryListRoundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryListRoundsResponse)
	err := c.cc.Invoke(ctx, Query_ListRounds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the vote module's gRPC query service.
type QueryServer interface {
	// CommitmentTreeAtHeight returns the commitment tree root at a specific anchor height.
	CommitmentTreeAtHeight(context.Context, *QueryCommitmentTreeRequest) (*QueryCommitmentTreeResponse, error)
	// LatestCommitmentTree returns the latest commitment tree state.
	LatestCommitmentTree(context.Context, *QueryLatestTreeRequest) (*QueryLatestTreeResponse, error)
	// VoteRound returns information about a specific vote round.
	VoteRound(context.Context, *QueryVoteRoundRequest) (*QueryVoteRoundResponse, error)
	// ProposalTally returns the accumulated tally for a proposal within a vote round.
	ProposalTally(context.Context, *QueryProposalTallyRequest) (*QueryProposalTallyResponse, error)
	// TallyResults returns finalized tally results for a vote round (after MsgSubmitTally).
	TallyResults(context.Context, *QueryTallyResultsRequest) (*QueryTallyResultsResponse, error)
	// CommitmentLeaves returns the commitment tree leaves organized by block height.
	// Used by remote clients implementing TreeSyncApi to sync the vote commitment tree.
	CommitmentLeaves(context.Context, *QueryCommitmentLeavesRequest) (*QueryCommitmentLeavesResponse, error)
	// ActiveRound returns the first active voting round, if any.
	// Iterates all stored rounds and returns the first with SESSION_STATUS_ACTIVE.
	ActiveRound(context.Context, *QueryActiveRoundRequest) (*QueryActiveRoundResponse, error)
	// CeremonyState returns the current EA key ceremony lifecycle state.
	CeremonyState(context.Context, *QueryCeremonyStateRequest) (*QueryCeremonyStateResponse, error)
	// VoteManager returns the current vote manager address.
	VoteManager(context.Context, *QueryVoteManagerRequest) (*QueryVoteManagerResponse, error)
	// VoteSummary returns a denormalized view of a vote round with proposals,
	// ballot counts, and (if finalized) decrypted totals. Single query for frontend display.
	VoteSummary(context.Context, *QueryVoteSummaryRequest) (*QueryVoteSummaryResponse, error)
	// ListRounds returns all stored vote rounds.
	ListRounds(context.Context, *QueryListRoundsRequest) (*QueryListRoundsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) CommitmentTreeAtHeight(context.Context, *QueryCommitmentTreeRequest) (*QueryCommitmentTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitmentTreeAtHeight not implemented")
}
func (UnimplementedQueryServer) LatestCommitmentTree(context.Context, *QueryLatestTreeRequest) (*QueryLatestTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestCommitmentTree not implemented")
}
func (UnimplementedQueryServer) VoteRound(context.Context, *QueryVoteRoundRequest) (*QueryVoteRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoteRound not implemented")
}
func (UnimplementedQueryServer) ProposalTally(context.Context, *QueryProposalTallyRequest) (*QueryProposalTallyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposalTally not implemented")
}
func (UnimplementedQueryServer) TallyResults(context.Context, *QueryTallyResultsRequest) (*QueryTallyResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TallyResults not implemented")
}
func (UnimplementedQueryServer) CommitmentLeaves(context.Context, *QueryCommitmentLeavesRequest) (*QueryCommitmentLeavesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitmentLeaves not implemented")
}
func (UnimplementedQueryServer) ActiveRound(context.Context, *QueryActiveRoundRequest) (*QueryActiveRoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActiveRound not implemented")
}
func (UnimplementedQueryServer) CeremonyState(context.Context, *QueryCeremonyStateRequest) (*QueryCeremonyStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CeremonyState not implemented")
}
func (UnimplementedQueryServer) VoteManager(context.Context, *QueryVoteManagerRequest) (*QueryVoteManagerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoteManager not implemented")
}
func (UnimplementedQueryServer) VoteSummary(context.Context, *QueryVoteSummaryRequest) (*QueryVoteSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VoteSummary not implemented")
}
func (UnimplementedQueryServer) ListRounds(context.Context, *QueryListRoundsRequest) (*QueryListRoundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRounds not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_CommitmentTreeAtHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitmentTreeAtHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CommitmentTreeAtHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitmentTreeAtHeight(ctx, req.(*QueryCommitmentTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestCommitmentTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestCommitmentTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestCommitmentTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestCommitmentTree(ctx, req.(*QueryLatestTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VoteRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteRound(ctx, req.(*QueryVoteRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProposalTally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposalTallyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposalTally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProposalTally_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposalTally(ctx, req.(*QueryProposalTallyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TallyResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTallyResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TallyResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_TallyResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TallyResults(ctx, req.(*QueryTallyResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CommitmentLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitmentLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CommitmentLeaves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitmentLeaves(ctx, req.(*QueryCommitmentLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ActiveRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveRound(ctx, req.(*QueryActiveRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CeremonyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCeremonyStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CeremonyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CeremonyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CeremonyState(ctx, req.(*QueryCeremonyStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VoteManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteManager(ctx, req.(*QueryVoteManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VoteSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteSummary(ctx, req.(*QueryVoteSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListRounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListRoundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListRounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ListRounds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListRounds(ctx, req.(*QueryListRoundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zvote.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitmentTreeAtHeight",
			Handler:    _Query_CommitmentTreeAtHeight_Handler,
		},
		{
			MethodName: "LatestCommitmentTree",
			Handler:    _Query_LatestCommitmentTree_Handler,
		},
		{
			MethodName: "VoteRound",
			Handler:    _Query_VoteRound_Handler,
		},
		{
			MethodName: "ProposalTally",
			Handler:    _Query_ProposalTally_Handler,
		},
		{
			MethodName: "TallyResults",
			Handler:    _Query_TallyResults_Handler,
		},
		{
			MethodName: "CommitmentLeaves",
			Handler:    _Query_CommitmentLeaves_Handler,
		},
		{
			MethodName: "ActiveRound",
			Handler:    _Query_ActiveRound_Handler,
		},
		{
			MethodName: "CeremonyState",
			Handler:    _Query_CeremonyState_Handler,
		},
		{
			MethodName: "VoteManager",
			Handler:    _Query_VoteManager_Handler,
		},
		{
			MethodName: "VoteSummary",
			Handler:    _Query_VoteSummary_Handler,
		},
		{
			MethodName: "ListRounds",
			Handler:    _Query_ListRounds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvote/v1/query.proto",
}
