// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: zvote/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateVotingSession creates a new voting session.
// vote_round_id is computed on-chain as Blake2b(snapshot_height, snapshot_blockhash, proposals_hash, vote_end_time, nullifier_imt_root, nc_root).
// ea_pk is sourced from the confirmed CeremonyState, not supplied by the caller.
type MsgCreateVotingSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Creator           string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	VkZkp1            []byte                 `protobuf:"bytes,8,opt,name=vk_zkp1,json=vkZkp1,proto3" json:"vk_zkp1,omitempty"`  // Verification key for ZKP #1
	VkZkp2            []byte                 `protobuf:"bytes,9,opt,name=vk_zkp2,json=vkZkp2,proto3" json:"vk_zkp2,omitempty"`  // Verification key for ZKP #2
	VkZkp3            []byte                 `protobuf:"bytes,10,opt,name=vk_zkp3,json=vkZkp3,proto3" json:"vk_zkp3,omitempty"` // Verification key for ZKP #3
	Proposals         []*Proposal            `protobuf:"bytes,11,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgCreateVotingSession) Reset() {
	*x = MsgCreateVotingSession{}
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSession) ProtoMessage() {}

func (x *MsgCreateVotingSession) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSession.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSession) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateVotingSession) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateVotingSession) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *MsgCreateVotingSession) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *MsgCreateVotingSession) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp1() []byte {
	if x != nil {
		return x.VkZkp1
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp2() []byte {
	if x != nil {
		return x.VkZkp2
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp3() []byte {
	if x != nil {
		return x.VkZkp3
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type MsgCreateVotingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateVotingSessionResponse) Reset() {
	*x = MsgCreateVotingSessionResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSessionResponse) ProtoMessage() {}

func (x *MsgCreateVotingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSessionResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSessionResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateVotingSessionResponse) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

// MsgDelegateVote corresponds to ZKP #1: delegation registration from keystone-signed action.
type MsgDelegateVote struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Rk                  []byte                 `protobuf:"bytes,1,opt,name=rk,proto3" json:"rk,omitempty"`                                                                // Randomized spend auth key (32 bytes)
	SpendAuthSig        []byte                 `protobuf:"bytes,2,opt,name=spend_auth_sig,json=spendAuthSig,proto3" json:"spend_auth_sig,omitempty"`                      // RedPallas signature
	SignedNoteNullifier []byte                 `protobuf:"bytes,3,opt,name=signed_note_nullifier,json=signedNoteNullifier,proto3" json:"signed_note_nullifier,omitempty"` // Nullifier of the dummy signed note
	CmxNew              []byte                 `protobuf:"bytes,4,opt,name=cmx_new,json=cmxNew,proto3" json:"cmx_new,omitempty"`                                          // Output note commitment
	EncMemo             []byte                 `protobuf:"bytes,5,opt,name=enc_memo,json=encMemo,proto3" json:"enc_memo,omitempty"`                                       // Encrypted memo
	VanCmx              []byte                 `protobuf:"bytes,6,opt,name=van_cmx,json=vanCmx,proto3" json:"van_cmx,omitempty"`                                          // Vote authority note commitment
	GovNullifiers       [][]byte               `protobuf:"bytes,7,rep,name=gov_nullifiers,json=govNullifiers,proto3" json:"gov_nullifiers,omitempty"`                     // Up to 4 governance nullifiers
	Proof               []byte                 `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`                                                          // Halo2 ZKP #1
	VoteRoundId         []byte                 `protobuf:"bytes,9,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Sighash             []byte                 `protobuf:"bytes,10,opt,name=sighash,proto3" json:"sighash,omitempty"` // Client-provided sighash for RedPallas signature verification (32 bytes)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgDelegateVote) Reset() {
	*x = MsgDelegateVote{}
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVote) ProtoMessage() {}

func (x *MsgDelegateVote) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVote.ProtoReflect.Descriptor instead.
func (*MsgDelegateVote) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDelegateVote) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *MsgDelegateVote) GetSpendAuthSig() []byte {
	if x != nil {
		return x.SpendAuthSig
	}
	return nil
}

func (x *MsgDelegateVote) GetSignedNoteNullifier() []byte {
	if x != nil {
		return x.SignedNoteNullifier
	}
	return nil
}

func (x *MsgDelegateVote) GetCmxNew() []byte {
	if x != nil {
		return x.CmxNew
	}
	return nil
}

func (x *MsgDelegateVote) GetEncMemo() []byte {
	if x != nil {
		return x.EncMemo
	}
	return nil
}

func (x *MsgDelegateVote) GetVanCmx() []byte {
	if x != nil {
		return x.VanCmx
	}
	return nil
}

func (x *MsgDelegateVote) GetGovNullifiers() [][]byte {
	if x != nil {
		return x.GovNullifiers
	}
	return nil
}

func (x *MsgDelegateVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgDelegateVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgDelegateVote) GetSighash() []byte {
	if x != nil {
		return x.Sighash
	}
	return nil
}

type MsgDelegateVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDelegateVoteResponse) Reset() {
	*x = MsgDelegateVoteResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVoteResponse) ProtoMessage() {}

func (x *MsgDelegateVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgDelegateVoteResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgCastVote corresponds to ZKP #2: create a vote commitment.
// Condition 4 (Spend Authority) adds r_vpk = vsk.ak + [alpha_v]*G; the circuit
// exposes r_vpk_x and r_vpk_y as public inputs, so the client must send them.
type MsgCastVote struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VanNullifier             []byte                 `protobuf:"bytes,1,opt,name=van_nullifier,json=vanNullifier,proto3" json:"van_nullifier,omitempty"`
	VoteAuthorityNoteNew     []byte                 `protobuf:"bytes,2,opt,name=vote_authority_note_new,json=voteAuthorityNoteNew,proto3" json:"vote_authority_note_new,omitempty"`
	VoteCommitment           []byte                 `protobuf:"bytes,3,opt,name=vote_commitment,json=voteCommitment,proto3" json:"vote_commitment,omitempty"`
	ProposalId               uint32                 `protobuf:"varint,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	RVpkX                    []byte                 `protobuf:"bytes,8,opt,name=r_vpk_x,json=rVpkX,proto3" json:"r_vpk_x,omitempty"`                    // Pallas Fp: x-coordinate of randomized voting key (condition 4)
	RVpkY                    []byte                 `protobuf:"bytes,9,opt,name=r_vpk_y,json=rVpkY,proto3" json:"r_vpk_y,omitempty"`                    // Pallas Fp: y-coordinate of randomized voting key (condition 4)
	VoteAuthSig              []byte                 `protobuf:"bytes,10,opt,name=vote_auth_sig,json=voteAuthSig,proto3" json:"vote_auth_sig,omitempty"` // RedPallas signature under randomized voting key
	Sighash                  []byte                 `protobuf:"bytes,11,opt,name=sighash,proto3" json:"sighash,omitempty"`                              // Client-provided canonical sighash (32 bytes)
	RVpk                     []byte                 `protobuf:"bytes,12,opt,name=r_vpk,json=rVpk,proto3" json:"r_vpk,omitempty"`                        // Compressed Pallas point (32 bytes) for sig verification
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgCastVote) Reset() {
	*x = MsgCastVote{}
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVote) ProtoMessage() {}

func (x *MsgCastVote) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVote.ProtoReflect.Descriptor instead.
func (*MsgCastVote) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgCastVote) GetVanNullifier() []byte {
	if x != nil {
		return x.VanNullifier
	}
	return nil
}

func (x *MsgCastVote) GetVoteAuthorityNoteNew() []byte {
	if x != nil {
		return x.VoteAuthorityNoteNew
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommitment() []byte {
	if x != nil {
		return x.VoteCommitment
	}
	return nil
}

func (x *MsgCastVote) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgCastVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgCastVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

func (x *MsgCastVote) GetRVpkX() []byte {
	if x != nil {
		return x.RVpkX
	}
	return nil
}

func (x *MsgCastVote) GetRVpkY() []byte {
	if x != nil {
		return x.RVpkY
	}
	return nil
}

func (x *MsgCastVote) GetVoteAuthSig() []byte {
	if x != nil {
		return x.VoteAuthSig
	}
	return nil
}

func (x *MsgCastVote) GetSighash() []byte {
	if x != nil {
		return x.Sighash
	}
	return nil
}

func (x *MsgCastVote) GetRVpk() []byte {
	if x != nil {
		return x.RVpk
	}
	return nil
}

type MsgCastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCastVoteResponse) Reset() {
	*x = MsgCastVoteResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVoteResponse) ProtoMessage() {}

func (x *MsgCastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgCastVoteResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{5}
}

// MsgRevealShare corresponds to ZKP #3: reveal vote share (server submits).
type MsgRevealShare struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ShareNullifier           []byte                 `protobuf:"bytes,1,opt,name=share_nullifier,json=shareNullifier,proto3" json:"share_nullifier,omitempty"`
	EncShare                 []byte                 `protobuf:"bytes,2,opt,name=enc_share,json=encShare,proto3" json:"enc_share,omitempty"` // 64 bytes: ElGamal ciphertext (C1 || C2, compressed Pallas points)
	ProposalId               uint32                 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision             uint32                 `protobuf:"varint,4,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgRevealShare) Reset() {
	*x = MsgRevealShare{}
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShare) ProtoMessage() {}

func (x *MsgRevealShare) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShare.ProtoReflect.Descriptor instead.
func (*MsgRevealShare) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRevealShare) GetShareNullifier() []byte {
	if x != nil {
		return x.ShareNullifier
	}
	return nil
}

func (x *MsgRevealShare) GetEncShare() []byte {
	if x != nil {
		return x.EncShare
	}
	return nil
}

func (x *MsgRevealShare) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgRevealShare) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *MsgRevealShare) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgRevealShare) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgRevealShare) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgRevealShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealShareResponse) Reset() {
	*x = MsgRevealShareResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShareResponse) ProtoMessage() {}

func (x *MsgRevealShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShareResponse.ProtoReflect.Descriptor instead.
func (*MsgRevealShareResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{7}
}

// MsgSubmitTally finalizes a voting session, transitioning it from TALLYING to FINALIZED.
// The election authority submits decrypted vote totals for each (proposal, decision) pair.
// Only the session creator (election authority) may submit this message.
type MsgSubmitTally struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Creator       string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"` // Must match the session creator
	Entries       []*TallyEntry          `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"` // One per (proposal_id, vote_decision) pair
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitTally) Reset() {
	*x = MsgSubmitTally{}
	mi := &file_zvote_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTally) ProtoMessage() {}

func (x *MsgSubmitTally) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTally.ProtoReflect.Descriptor instead.
func (*MsgSubmitTally) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgSubmitTally) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgSubmitTally) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSubmitTally) GetEntries() []*TallyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// TallyEntry contains the decrypted vote total for one (proposal, decision) pair.
type TallyEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      uint32                 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision    uint32                 `protobuf:"varint,2,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue      uint64                 `protobuf:"varint,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`               // Decrypted aggregate (zatoshi)
	DecryptionProof []byte                 `protobuf:"bytes,4,opt,name=decryption_proof,json=decryptionProof,proto3" json:"decryption_proof,omitempty"` // Chaum-Pedersen DLEQ proof (reserved for future use)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TallyEntry) Reset() {
	*x = TallyEntry{}
	mi := &file_zvote_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyEntry) ProtoMessage() {}

func (x *TallyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyEntry.ProtoReflect.Descriptor instead.
func (*TallyEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *TallyEntry) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyEntry) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyEntry) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *TallyEntry) GetDecryptionProof() []byte {
	if x != nil {
		return x.DecryptionProof
	}
	return nil
}

type MsgSubmitTallyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinalizedEntries uint32                 `protobuf:"varint,1,opt,name=finalized_entries,json=finalizedEntries,proto3" json:"finalized_entries,omitempty"` // Number of tally entries stored
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgSubmitTallyResponse) Reset() {
	*x = MsgSubmitTallyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTallyResponse) ProtoMessage() {}

func (x *MsgSubmitTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTallyResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitTallyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgSubmitTallyResponse) GetFinalizedEntries() uint32 {
	if x != nil {
		return x.FinalizedEntries
	}
	return 0
}

// MsgRegisterPallasKey registers a validator's Pallas public key for the EA key ceremony.
type MsgRegisterPallasKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                   // Validator address
	PallasPk      []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"` // Compressed Pallas point (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPallasKey) Reset() {
	*x = MsgRegisterPallasKey{}
	mi := &file_zvote_v1_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPallasKey) ProtoMessage() {}

func (x *MsgRegisterPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPallasKey.ProtoReflect.Descriptor instead.
func (*MsgRegisterPallasKey) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{11}
}

func (x *MsgRegisterPallasKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgRegisterPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

type MsgRegisterPallasKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterPallasKeyResponse) Reset() {
	*x = MsgRegisterPallasKeyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterPallasKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterPallasKeyResponse) ProtoMessage() {}

func (x *MsgRegisterPallasKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterPallasKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterPallasKeyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{12}
}

// MsgDealExecutiveAuthorityKey is submitted by the bootstrap dealer to distribute encrypted ea_sk shares.
type MsgDealExecutiveAuthorityKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`       // Dealer's validator address
	EaPk          []byte                 `protobuf:"bytes,2,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"` // Executive authority public key (Pallas, 32 bytes)
	Payloads      []*DealerPayload       `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`     // One ECIES envelope per registered validator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDealExecutiveAuthorityKey) Reset() {
	*x = MsgDealExecutiveAuthorityKey{}
	mi := &file_zvote_v1_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDealExecutiveAuthorityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDealExecutiveAuthorityKey) ProtoMessage() {}

func (x *MsgDealExecutiveAuthorityKey) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDealExecutiveAuthorityKey.ProtoReflect.Descriptor instead.
func (*MsgDealExecutiveAuthorityKey) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{13}
}

func (x *MsgDealExecutiveAuthorityKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgDealExecutiveAuthorityKey) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *MsgDealExecutiveAuthorityKey) GetPayloads() []*DealerPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type MsgDealExecutiveAuthorityKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDealExecutiveAuthorityKeyResponse) Reset() {
	*x = MsgDealExecutiveAuthorityKeyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDealExecutiveAuthorityKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDealExecutiveAuthorityKeyResponse) ProtoMessage() {}

func (x *MsgDealExecutiveAuthorityKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDealExecutiveAuthorityKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgDealExecutiveAuthorityKeyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{14}
}

// MsgAckExecutiveAuthorityKey is submitted by a validator to acknowledge receipt of their ea_sk share.
type MsgAckExecutiveAuthorityKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`                               // Validator address
	AckSignature  []byte                 `protobuf:"bytes,2,opt,name=ack_signature,json=ackSignature,proto3" json:"ack_signature,omitempty"` // Signature over H("ack" || ea_pk || validator_address)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAckExecutiveAuthorityKey) Reset() {
	*x = MsgAckExecutiveAuthorityKey{}
	mi := &file_zvote_v1_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAckExecutiveAuthorityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAckExecutiveAuthorityKey) ProtoMessage() {}

func (x *MsgAckExecutiveAuthorityKey) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAckExecutiveAuthorityKey.ProtoReflect.Descriptor instead.
func (*MsgAckExecutiveAuthorityKey) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{15}
}

func (x *MsgAckExecutiveAuthorityKey) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgAckExecutiveAuthorityKey) GetAckSignature() []byte {
	if x != nil {
		return x.AckSignature
	}
	return nil
}

type MsgAckExecutiveAuthorityKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAckExecutiveAuthorityKeyResponse) Reset() {
	*x = MsgAckExecutiveAuthorityKeyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAckExecutiveAuthorityKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAckExecutiveAuthorityKeyResponse) ProtoMessage() {}

func (x *MsgAckExecutiveAuthorityKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAckExecutiveAuthorityKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgAckExecutiveAuthorityKeyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{16}
}

// MsgCreateValidatorWithPallasKey wraps standard MsgCreateValidator with a Pallas public key.
// The handler creates the validator via the staking module, then registers the Pallas key
// in the ceremony state. Raw MsgCreateValidator is blocked by the ante handler for live txs.
type MsgCreateValidatorWithPallasKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StakingMsg    []byte                 `protobuf:"bytes,1,opt,name=staking_msg,json=stakingMsg,proto3" json:"staking_msg,omitempty"` // Encoded cosmos.staking.v1beta1.MsgCreateValidator
	PallasPk      []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"`       // Compressed Pallas point (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateValidatorWithPallasKey) Reset() {
	*x = MsgCreateValidatorWithPallasKey{}
	mi := &file_zvote_v1_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateValidatorWithPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateValidatorWithPallasKey) ProtoMessage() {}

func (x *MsgCreateValidatorWithPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateValidatorWithPallasKey.ProtoReflect.Descriptor instead.
func (*MsgCreateValidatorWithPallasKey) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{17}
}

func (x *MsgCreateValidatorWithPallasKey) GetStakingMsg() []byte {
	if x != nil {
		return x.StakingMsg
	}
	return nil
}

func (x *MsgCreateValidatorWithPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

type MsgCreateValidatorWithPallasKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateValidatorWithPallasKeyResponse) Reset() {
	*x = MsgCreateValidatorWithPallasKeyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateValidatorWithPallasKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateValidatorWithPallasKeyResponse) ProtoMessage() {}

func (x *MsgCreateValidatorWithPallasKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateValidatorWithPallasKeyResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateValidatorWithPallasKeyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{18}
}

// MsgReInitializeElectionAuthority resets the EA key ceremony back to INITIALIZING.
// Can only be submitted when no ceremony session is in progress (REGISTERING or DEALT).
// Allowed when ceremony is nil, UNSPECIFIED, INITIALIZING, or CONFIRMED.
type MsgReInitializeElectionAuthority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"` // Validator address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReInitializeElectionAuthority) Reset() {
	*x = MsgReInitializeElectionAuthority{}
	mi := &file_zvote_v1_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReInitializeElectionAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReInitializeElectionAuthority) ProtoMessage() {}

func (x *MsgReInitializeElectionAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReInitializeElectionAuthority.ProtoReflect.Descriptor instead.
func (*MsgReInitializeElectionAuthority) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{19}
}

func (x *MsgReInitializeElectionAuthority) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type MsgReInitializeElectionAuthorityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgReInitializeElectionAuthorityResponse) Reset() {
	*x = MsgReInitializeElectionAuthorityResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgReInitializeElectionAuthorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReInitializeElectionAuthorityResponse) ProtoMessage() {}

func (x *MsgReInitializeElectionAuthorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReInitializeElectionAuthorityResponse.ProtoReflect.Descriptor instead.
func (*MsgReInitializeElectionAuthorityResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{20}
}

var File_zvote_v1_tx_proto protoreflect.FileDescriptor

const file_zvote_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x11zvote/v1/tx.proto\x12\bzvote.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14zvote/v1/types.proto\"\x99\x03\n" +
	"\x16MsgCreateVotingSession\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x17\n" +
	"\avk_zkp1\x18\b \x01(\fR\x06vkZkp1\x12\x17\n" +
	"\avk_zkp2\x18\t \x01(\fR\x06vkZkp2\x12\x17\n" +
	"\avk_zkp3\x18\n" +
	" \x01(\fR\x06vkZkp3\x120\n" +
	"\tproposals\x18\v \x03(\v2\x12.zvote.v1.ProposalR\tproposals\"D\n" +
	"\x1eMsgCreateVotingSessionResponse\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"\xc3\x02\n" +
	"\x0fMsgDelegateVote\x12\x0e\n" +
	"\x02rk\x18\x01 \x01(\fR\x02rk\x12$\n" +
	"\x0espend_auth_sig\x18\x02 \x01(\fR\fspendAuthSig\x122\n" +
	"\x15signed_note_nullifier\x18\x03 \x01(\fR\x13signedNoteNullifier\x12\x17\n" +
	"\acmx_new\x18\x04 \x01(\fR\x06cmxNew\x12\x19\n" +
	"\benc_memo\x18\x05 \x01(\fR\aencMemo\x12\x17\n" +
	"\avan_cmx\x18\x06 \x01(\fR\x06vanCmx\x12%\n" +
	"\x0egov_nullifiers\x18\a \x03(\fR\rgovNullifiers\x12\x14\n" +
	"\x05proof\x18\b \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\t \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\asighash\x18\n" +
	" \x01(\fR\asighash\"\x19\n" +
	"\x17MsgDelegateVoteResponse\"\xb0\x03\n" +
	"\vMsgCastVote\x12#\n" +
	"\rvan_nullifier\x18\x01 \x01(\fR\fvanNullifier\x125\n" +
	"\x17vote_authority_note_new\x18\x02 \x01(\fR\x14voteAuthorityNoteNew\x12'\n" +
	"\x0fvote_commitment\x18\x03 \x01(\fR\x0evoteCommitment\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\rR\n" +
	"proposalId\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\x12\x16\n" +
	"\ar_vpk_x\x18\b \x01(\fR\x05rVpkX\x12\x16\n" +
	"\ar_vpk_y\x18\t \x01(\fR\x05rVpkY\x12\"\n" +
	"\rvote_auth_sig\x18\n" +
	" \x01(\fR\vvoteAuthSig\x12\x18\n" +
	"\asighash\x18\v \x01(\fR\asighash\x12\x13\n" +
	"\x05r_vpk\x18\f \x01(\fR\x04rVpk\"\x15\n" +
	"\x13MsgCastVoteResponse\"\x96\x02\n" +
	"\x0eMsgRevealShare\x12'\n" +
	"\x0fshare_nullifier\x18\x01 \x01(\fR\x0eshareNullifier\x12\x1b\n" +
	"\tenc_share\x18\x02 \x01(\fR\bencShare\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x04 \x01(\rR\fvoteDecision\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"\x18\n" +
	"\x16MsgRevealShareResponse\"~\n" +
	"\x0eMsgSubmitTally\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.zvote.v1.TallyEntryR\aentries\"\x9e\x01\n" +
	"\n" +
	"TallyEntry\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x02 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x03 \x01(\x04R\n" +
	"totalValue\x12)\n" +
	"\x10decryption_proof\x18\x04 \x01(\fR\x0fdecryptionProof\"E\n" +
	"\x16MsgSubmitTallyResponse\x12+\n" +
	"\x11finalized_entries\x18\x01 \x01(\rR\x10finalizedEntries\"M\n" +
	"\x14MsgRegisterPallasKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\"\x1e\n" +
	"\x1cMsgRegisterPallasKeyResponse\"\x82\x01\n" +
	"\x1cMsgDealExecutiveAuthorityKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x13\n" +
	"\x05ea_pk\x18\x02 \x01(\fR\x04eaPk\x123\n" +
	"\bpayloads\x18\x03 \x03(\v2\x17.zvote.v1.DealerPayloadR\bpayloads\"&\n" +
	"$MsgDealExecutiveAuthorityKeyResponse\"\\\n" +
	"\x1bMsgAckExecutiveAuthorityKey\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12#\n" +
	"\rack_signature\x18\x02 \x01(\fR\fackSignature\"%\n" +
	"#MsgAckExecutiveAuthorityKeyResponse\"_\n" +
	"\x1fMsgCreateValidatorWithPallasKey\x12\x1f\n" +
	"\vstaking_msg\x18\x01 \x01(\fR\n" +
	"stakingMsg\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\")\n" +
	"'MsgCreateValidatorWithPallasKeyResponse\"<\n" +
	" MsgReInitializeElectionAuthority\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\"*\n" +
	"(MsgReInitializeElectionAuthorityResponse2\xd8\a\n" +
	"\x03Msg\x12a\n" +
	"\x13CreateVotingSession\x12 .zvote.v1.MsgCreateVotingSession\x1a(.zvote.v1.MsgCreateVotingSessionResponse\x12L\n" +
	"\fDelegateVote\x12\x19.zvote.v1.MsgDelegateVote\x1a!.zvote.v1.MsgDelegateVoteResponse\x12@\n" +
	"\bCastVote\x12\x15.zvote.v1.MsgCastVote\x1a\x1d.zvote.v1.MsgCastVoteResponse\x12I\n" +
	"\vRevealShare\x12\x18.zvote.v1.MsgRevealShare\x1a .zvote.v1.MsgRevealShareResponse\x12I\n" +
	"\vSubmitTally\x12\x18.zvote.v1.MsgSubmitTally\x1a .zvote.v1.MsgSubmitTallyResponse\x12[\n" +
	"\x11RegisterPallasKey\x12\x1e.zvote.v1.MsgRegisterPallasKey\x1a&.zvote.v1.MsgRegisterPallasKeyResponse\x12s\n" +
	"\x19DealExecutiveAuthorityKey\x12&.zvote.v1.MsgDealExecutiveAuthorityKey\x1a..zvote.v1.MsgDealExecutiveAuthorityKeyResponse\x12p\n" +
	"\x18AckExecutiveAuthorityKey\x12%.zvote.v1.MsgAckExecutiveAuthorityKey\x1a-.zvote.v1.MsgAckExecutiveAuthorityKeyResponse\x12|\n" +
	"\x1cCreateValidatorWithPallasKey\x12).zvote.v1.MsgCreateValidatorWithPallasKey\x1a1.zvote.v1.MsgCreateValidatorWithPallasKeyResponse\x12\x7f\n" +
	"\x1dReInitializeElectionAuthority\x12*.zvote.v1.MsgReInitializeElectionAuthority\x1a2.zvote.v1.MsgReInitializeElectionAuthorityResponse\x1a\x05\x80\xe7\xb0*\x01B&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_tx_proto_rawDescOnce sync.Once
	file_zvote_v1_tx_proto_rawDescData []byte
)

func file_zvote_v1_tx_proto_rawDescGZIP() []byte {
	file_zvote_v1_tx_proto_rawDescOnce.Do(func() {
		file_zvote_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)))
	})
	return file_zvote_v1_tx_proto_rawDescData
}

var file_zvote_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_zvote_v1_tx_proto_goTypes = []any{
	(*MsgCreateVotingSession)(nil),                   // 0: zvote.v1.MsgCreateVotingSession
	(*MsgCreateVotingSessionResponse)(nil),           // 1: zvote.v1.MsgCreateVotingSessionResponse
	(*MsgDelegateVote)(nil),                          // 2: zvote.v1.MsgDelegateVote
	(*MsgDelegateVoteResponse)(nil),                  // 3: zvote.v1.MsgDelegateVoteResponse
	(*MsgCastVote)(nil),                              // 4: zvote.v1.MsgCastVote
	(*MsgCastVoteResponse)(nil),                      // 5: zvote.v1.MsgCastVoteResponse
	(*MsgRevealShare)(nil),                           // 6: zvote.v1.MsgRevealShare
	(*MsgRevealShareResponse)(nil),                   // 7: zvote.v1.MsgRevealShareResponse
	(*MsgSubmitTally)(nil),                           // 8: zvote.v1.MsgSubmitTally
	(*TallyEntry)(nil),                               // 9: zvote.v1.TallyEntry
	(*MsgSubmitTallyResponse)(nil),                   // 10: zvote.v1.MsgSubmitTallyResponse
	(*MsgRegisterPallasKey)(nil),                     // 11: zvote.v1.MsgRegisterPallasKey
	(*MsgRegisterPallasKeyResponse)(nil),             // 12: zvote.v1.MsgRegisterPallasKeyResponse
	(*MsgDealExecutiveAuthorityKey)(nil),             // 13: zvote.v1.MsgDealExecutiveAuthorityKey
	(*MsgDealExecutiveAuthorityKeyResponse)(nil),     // 14: zvote.v1.MsgDealExecutiveAuthorityKeyResponse
	(*MsgAckExecutiveAuthorityKey)(nil),              // 15: zvote.v1.MsgAckExecutiveAuthorityKey
	(*MsgAckExecutiveAuthorityKeyResponse)(nil),      // 16: zvote.v1.MsgAckExecutiveAuthorityKeyResponse
	(*MsgCreateValidatorWithPallasKey)(nil),          // 17: zvote.v1.MsgCreateValidatorWithPallasKey
	(*MsgCreateValidatorWithPallasKeyResponse)(nil),  // 18: zvote.v1.MsgCreateValidatorWithPallasKeyResponse
	(*MsgReInitializeElectionAuthority)(nil),         // 19: zvote.v1.MsgReInitializeElectionAuthority
	(*MsgReInitializeElectionAuthorityResponse)(nil), // 20: zvote.v1.MsgReInitializeElectionAuthorityResponse
	(*Proposal)(nil),                                 // 21: zvote.v1.Proposal
	(*DealerPayload)(nil),                            // 22: zvote.v1.DealerPayload
}
var file_zvote_v1_tx_proto_depIdxs = []int32{
	21, // 0: zvote.v1.MsgCreateVotingSession.proposals:type_name -> zvote.v1.Proposal
	9,  // 1: zvote.v1.MsgSubmitTally.entries:type_name -> zvote.v1.TallyEntry
	22, // 2: zvote.v1.MsgDealExecutiveAuthorityKey.payloads:type_name -> zvote.v1.DealerPayload
	0,  // 3: zvote.v1.Msg.CreateVotingSession:input_type -> zvote.v1.MsgCreateVotingSession
	2,  // 4: zvote.v1.Msg.DelegateVote:input_type -> zvote.v1.MsgDelegateVote
	4,  // 5: zvote.v1.Msg.CastVote:input_type -> zvote.v1.MsgCastVote
	6,  // 6: zvote.v1.Msg.RevealShare:input_type -> zvote.v1.MsgRevealShare
	8,  // 7: zvote.v1.Msg.SubmitTally:input_type -> zvote.v1.MsgSubmitTally
	11, // 8: zvote.v1.Msg.RegisterPallasKey:input_type -> zvote.v1.MsgRegisterPallasKey
	13, // 9: zvote.v1.Msg.DealExecutiveAuthorityKey:input_type -> zvote.v1.MsgDealExecutiveAuthorityKey
	15, // 10: zvote.v1.Msg.AckExecutiveAuthorityKey:input_type -> zvote.v1.MsgAckExecutiveAuthorityKey
	17, // 11: zvote.v1.Msg.CreateValidatorWithPallasKey:input_type -> zvote.v1.MsgCreateValidatorWithPallasKey
	19, // 12: zvote.v1.Msg.ReInitializeElectionAuthority:input_type -> zvote.v1.MsgReInitializeElectionAuthority
	1,  // 13: zvote.v1.Msg.CreateVotingSession:output_type -> zvote.v1.MsgCreateVotingSessionResponse
	3,  // 14: zvote.v1.Msg.DelegateVote:output_type -> zvote.v1.MsgDelegateVoteResponse
	5,  // 15: zvote.v1.Msg.CastVote:output_type -> zvote.v1.MsgCastVoteResponse
	7,  // 16: zvote.v1.Msg.RevealShare:output_type -> zvote.v1.MsgRevealShareResponse
	10, // 17: zvote.v1.Msg.SubmitTally:output_type -> zvote.v1.MsgSubmitTallyResponse
	12, // 18: zvote.v1.Msg.RegisterPallasKey:output_type -> zvote.v1.MsgRegisterPallasKeyResponse
	14, // 19: zvote.v1.Msg.DealExecutiveAuthorityKey:output_type -> zvote.v1.MsgDealExecutiveAuthorityKeyResponse
	16, // 20: zvote.v1.Msg.AckExecutiveAuthorityKey:output_type -> zvote.v1.MsgAckExecutiveAuthorityKeyResponse
	18, // 21: zvote.v1.Msg.CreateValidatorWithPallasKey:output_type -> zvote.v1.MsgCreateValidatorWithPallasKeyResponse
	20, // 22: zvote.v1.Msg.ReInitializeElectionAuthority:output_type -> zvote.v1.MsgReInitializeElectionAuthorityResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_zvote_v1_tx_proto_init() }
func file_zvote_v1_tx_proto_init() {
	if File_zvote_v1_tx_proto != nil {
		return
	}
	file_zvote_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zvote_v1_tx_proto_goTypes,
		DependencyIndexes: file_zvote_v1_tx_proto_depIdxs,
		MessageInfos:      file_zvote_v1_tx_proto_msgTypes,
	}.Build()
	File_zvote_v1_tx_proto = out.File
	file_zvote_v1_tx_proto_goTypes = nil
	file_zvote_v1_tx_proto_depIdxs = nil
}
