// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateVotingSession creates a new voting session.
// vote_round_id is computed on-chain as Blake2b(snapshot_height, snapshot_blockhash, proposals_hash, vote_end_time, nullifier_imt_root, nc_root).
type MsgCreateVotingSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Creator           string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	EaPk              []byte                 `protobuf:"bytes,8,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"`        // Election authority public key (Pallas, 32 bytes)
	VkZkp1            []byte                 `protobuf:"bytes,9,opt,name=vk_zkp1,json=vkZkp1,proto3" json:"vk_zkp1,omitempty"`  // Verification key for ZKP #1
	VkZkp2            []byte                 `protobuf:"bytes,10,opt,name=vk_zkp2,json=vkZkp2,proto3" json:"vk_zkp2,omitempty"` // Verification key for ZKP #2
	VkZkp3            []byte                 `protobuf:"bytes,11,opt,name=vk_zkp3,json=vkZkp3,proto3" json:"vk_zkp3,omitempty"` // Verification key for ZKP #3
	Proposals         []*Proposal            `protobuf:"bytes,12,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgCreateVotingSession) Reset() {
	*x = MsgCreateVotingSession{}
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSession) ProtoMessage() {}

func (x *MsgCreateVotingSession) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSession.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSession) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateVotingSession) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateVotingSession) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *MsgCreateVotingSession) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *MsgCreateVotingSession) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *MsgCreateVotingSession) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp1() []byte {
	if x != nil {
		return x.VkZkp1
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp2() []byte {
	if x != nil {
		return x.VkZkp2
	}
	return nil
}

func (x *MsgCreateVotingSession) GetVkZkp3() []byte {
	if x != nil {
		return x.VkZkp3
	}
	return nil
}

func (x *MsgCreateVotingSession) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type MsgCreateVotingSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateVotingSessionResponse) Reset() {
	*x = MsgCreateVotingSessionResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVotingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVotingSessionResponse) ProtoMessage() {}

func (x *MsgCreateVotingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVotingSessionResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateVotingSessionResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateVotingSessionResponse) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

// MsgDelegateVote corresponds to ZKP #1: delegation registration from keystone-signed action.
type MsgDelegateVote struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Rk                  []byte                 `protobuf:"bytes,1,opt,name=rk,proto3" json:"rk,omitempty"`                                                                // Randomized spend auth key (32 bytes)
	SpendAuthSig        []byte                 `protobuf:"bytes,2,opt,name=spend_auth_sig,json=spendAuthSig,proto3" json:"spend_auth_sig,omitempty"`                      // RedPallas signature
	SignedNoteNullifier []byte                 `protobuf:"bytes,3,opt,name=signed_note_nullifier,json=signedNoteNullifier,proto3" json:"signed_note_nullifier,omitempty"` // Nullifier of the dummy signed note
	CmxNew              []byte                 `protobuf:"bytes,4,opt,name=cmx_new,json=cmxNew,proto3" json:"cmx_new,omitempty"`                                          // Output note commitment
	EncMemo             []byte                 `protobuf:"bytes,5,opt,name=enc_memo,json=encMemo,proto3" json:"enc_memo,omitempty"`                                       // Encrypted memo
	GovComm             []byte                 `protobuf:"bytes,6,opt,name=gov_comm,json=govComm,proto3" json:"gov_comm,omitempty"`                                       // Governance commitment
	GovNullifiers       [][]byte               `protobuf:"bytes,7,rep,name=gov_nullifiers,json=govNullifiers,proto3" json:"gov_nullifiers,omitempty"`                     // Up to 4 governance nullifiers
	Proof               []byte                 `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`                                                          // Halo2 ZKP #1
	VoteRoundId         []byte                 `protobuf:"bytes,9,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Sighash             []byte                 `protobuf:"bytes,10,opt,name=sighash,proto3" json:"sighash,omitempty"` // Client-provided sighash for RedPallas signature verification (32 bytes)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgDelegateVote) Reset() {
	*x = MsgDelegateVote{}
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVote) ProtoMessage() {}

func (x *MsgDelegateVote) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVote.ProtoReflect.Descriptor instead.
func (*MsgDelegateVote) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDelegateVote) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *MsgDelegateVote) GetSpendAuthSig() []byte {
	if x != nil {
		return x.SpendAuthSig
	}
	return nil
}

func (x *MsgDelegateVote) GetSignedNoteNullifier() []byte {
	if x != nil {
		return x.SignedNoteNullifier
	}
	return nil
}

func (x *MsgDelegateVote) GetCmxNew() []byte {
	if x != nil {
		return x.CmxNew
	}
	return nil
}

func (x *MsgDelegateVote) GetEncMemo() []byte {
	if x != nil {
		return x.EncMemo
	}
	return nil
}

func (x *MsgDelegateVote) GetGovComm() []byte {
	if x != nil {
		return x.GovComm
	}
	return nil
}

func (x *MsgDelegateVote) GetGovNullifiers() [][]byte {
	if x != nil {
		return x.GovNullifiers
	}
	return nil
}

func (x *MsgDelegateVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgDelegateVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgDelegateVote) GetSighash() []byte {
	if x != nil {
		return x.Sighash
	}
	return nil
}

type MsgDelegateVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDelegateVoteResponse) Reset() {
	*x = MsgDelegateVoteResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegateVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegateVoteResponse) ProtoMessage() {}

func (x *MsgDelegateVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegateVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgDelegateVoteResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgCastVote corresponds to ZKP #2: create a vote commitment.
type MsgCastVote struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VanNullifier             []byte                 `protobuf:"bytes,1,opt,name=van_nullifier,json=vanNullifier,proto3" json:"van_nullifier,omitempty"`
	VoteAuthorityNoteNew     []byte                 `protobuf:"bytes,2,opt,name=vote_authority_note_new,json=voteAuthorityNoteNew,proto3" json:"vote_authority_note_new,omitempty"`
	VoteCommitment           []byte                 `protobuf:"bytes,3,opt,name=vote_commitment,json=voteCommitment,proto3" json:"vote_commitment,omitempty"`
	ProposalId               uint32                 `protobuf:"varint,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgCastVote) Reset() {
	*x = MsgCastVote{}
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVote) ProtoMessage() {}

func (x *MsgCastVote) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVote.ProtoReflect.Descriptor instead.
func (*MsgCastVote) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgCastVote) GetVanNullifier() []byte {
	if x != nil {
		return x.VanNullifier
	}
	return nil
}

func (x *MsgCastVote) GetVoteAuthorityNoteNew() []byte {
	if x != nil {
		return x.VoteAuthorityNoteNew
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommitment() []byte {
	if x != nil {
		return x.VoteCommitment
	}
	return nil
}

func (x *MsgCastVote) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgCastVote) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgCastVote) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgCastVote) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgCastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCastVoteResponse) Reset() {
	*x = MsgCastVoteResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCastVoteResponse) ProtoMessage() {}

func (x *MsgCastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCastVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgCastVoteResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{5}
}

// MsgRevealShare corresponds to ZKP #3: reveal vote share (server submits).
type MsgRevealShare struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ShareNullifier           []byte                 `protobuf:"bytes,1,opt,name=share_nullifier,json=shareNullifier,proto3" json:"share_nullifier,omitempty"`
	EncShare                 []byte                 `protobuf:"bytes,2,opt,name=enc_share,json=encShare,proto3" json:"enc_share,omitempty"` // 64 bytes: ElGamal ciphertext (C1 || C2, compressed Pallas points)
	ProposalId               uint32                 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision             uint32                 `protobuf:"varint,4,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgRevealShare) Reset() {
	*x = MsgRevealShare{}
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShare) ProtoMessage() {}

func (x *MsgRevealShare) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShare.ProtoReflect.Descriptor instead.
func (*MsgRevealShare) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRevealShare) GetShareNullifier() []byte {
	if x != nil {
		return x.ShareNullifier
	}
	return nil
}

func (x *MsgRevealShare) GetEncShare() []byte {
	if x != nil {
		return x.EncShare
	}
	return nil
}

func (x *MsgRevealShare) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgRevealShare) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *MsgRevealShare) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgRevealShare) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgRevealShare) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgRevealShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealShareResponse) Reset() {
	*x = MsgRevealShareResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealShareResponse) ProtoMessage() {}

func (x *MsgRevealShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealShareResponse.ProtoReflect.Descriptor instead.
func (*MsgRevealShareResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{7}
}

// MsgSubmitTally finalizes a voting session, transitioning it from TALLYING to FINALIZED.
// The election authority submits decrypted vote totals for each (proposal, decision) pair.
// Only the session creator (election authority) may submit this message.
type MsgSubmitTally struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Creator       string                 `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"` // Must match the session creator
	Entries       []*TallyEntry          `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"` // One per (proposal_id, vote_decision) pair
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitTally) Reset() {
	*x = MsgSubmitTally{}
	mi := &file_zvote_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTally) ProtoMessage() {}

func (x *MsgSubmitTally) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTally.ProtoReflect.Descriptor instead.
func (*MsgSubmitTally) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgSubmitTally) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgSubmitTally) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSubmitTally) GetEntries() []*TallyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// TallyEntry contains the decrypted vote total for one (proposal, decision) pair.
type TallyEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      uint32                 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision    uint32                 `protobuf:"varint,2,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue      uint64                 `protobuf:"varint,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`               // Decrypted aggregate (zatoshi)
	DecryptionProof []byte                 `protobuf:"bytes,4,opt,name=decryption_proof,json=decryptionProof,proto3" json:"decryption_proof,omitempty"` // Chaum-Pedersen DLEQ proof (reserved for future use)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TallyEntry) Reset() {
	*x = TallyEntry{}
	mi := &file_zvote_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyEntry) ProtoMessage() {}

func (x *TallyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyEntry.ProtoReflect.Descriptor instead.
func (*TallyEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *TallyEntry) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyEntry) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyEntry) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *TallyEntry) GetDecryptionProof() []byte {
	if x != nil {
		return x.DecryptionProof
	}
	return nil
}

type MsgSubmitTallyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinalizedEntries uint32                 `protobuf:"varint,1,opt,name=finalized_entries,json=finalizedEntries,proto3" json:"finalized_entries,omitempty"` // Number of tally entries stored
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgSubmitTallyResponse) Reset() {
	*x = MsgSubmitTallyResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitTallyResponse) ProtoMessage() {}

func (x *MsgSubmitTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitTallyResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitTallyResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgSubmitTallyResponse) GetFinalizedEntries() uint32 {
	if x != nil {
		return x.FinalizedEntries
	}
	return 0
}

var File_zvote_v1_tx_proto protoreflect.FileDescriptor

const file_zvote_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x11zvote/v1/tx.proto\x12\bzvote.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14zvote/v1/types.proto\"\xae\x03\n" +
	"\x16MsgCreateVotingSession\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x13\n" +
	"\x05ea_pk\x18\b \x01(\fR\x04eaPk\x12\x17\n" +
	"\avk_zkp1\x18\t \x01(\fR\x06vkZkp1\x12\x17\n" +
	"\avk_zkp2\x18\n" +
	" \x01(\fR\x06vkZkp2\x12\x17\n" +
	"\avk_zkp3\x18\v \x01(\fR\x06vkZkp3\x120\n" +
	"\tproposals\x18\f \x03(\v2\x12.zvote.v1.ProposalR\tproposals\"D\n" +
	"\x1eMsgCreateVotingSessionResponse\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"\xc5\x02\n" +
	"\x0fMsgDelegateVote\x12\x0e\n" +
	"\x02rk\x18\x01 \x01(\fR\x02rk\x12$\n" +
	"\x0espend_auth_sig\x18\x02 \x01(\fR\fspendAuthSig\x122\n" +
	"\x15signed_note_nullifier\x18\x03 \x01(\fR\x13signedNoteNullifier\x12\x17\n" +
	"\acmx_new\x18\x04 \x01(\fR\x06cmxNew\x12\x19\n" +
	"\benc_memo\x18\x05 \x01(\fR\aencMemo\x12\x19\n" +
	"\bgov_comm\x18\x06 \x01(\fR\agovComm\x12%\n" +
	"\x0egov_nullifiers\x18\a \x03(\fR\rgovNullifiers\x12\x14\n" +
	"\x05proof\x18\b \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\t \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\asighash\x18\n" +
	" \x01(\fR\asighash\"\x19\n" +
	"\x17MsgDelegateVoteResponse\"\xad\x02\n" +
	"\vMsgCastVote\x12#\n" +
	"\rvan_nullifier\x18\x01 \x01(\fR\fvanNullifier\x125\n" +
	"\x17vote_authority_note_new\x18\x02 \x01(\fR\x14voteAuthorityNoteNew\x12'\n" +
	"\x0fvote_commitment\x18\x03 \x01(\fR\x0evoteCommitment\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\rR\n" +
	"proposalId\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"\x15\n" +
	"\x13MsgCastVoteResponse\"\x96\x02\n" +
	"\x0eMsgRevealShare\x12'\n" +
	"\x0fshare_nullifier\x18\x01 \x01(\fR\x0eshareNullifier\x12\x1b\n" +
	"\tenc_share\x18\x02 \x01(\fR\bencShare\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x04 \x01(\rR\fvoteDecision\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"\x18\n" +
	"\x16MsgRevealShareResponse\"~\n" +
	"\x0eMsgSubmitTally\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.zvote.v1.TallyEntryR\aentries\"\x9e\x01\n" +
	"\n" +
	"TallyEntry\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x02 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x03 \x01(\x04R\n" +
	"totalValue\x12)\n" +
	"\x10decryption_proof\x18\x04 \x01(\fR\x0fdecryptionProof\"E\n" +
	"\x16MsgSubmitTallyResponse\x12+\n" +
	"\x11finalized_entries\x18\x01 \x01(\rR\x10finalizedEntries2\x95\x03\n" +
	"\x03Msg\x12a\n" +
	"\x13CreateVotingSession\x12 .zvote.v1.MsgCreateVotingSession\x1a(.zvote.v1.MsgCreateVotingSessionResponse\x12L\n" +
	"\fDelegateVote\x12\x19.zvote.v1.MsgDelegateVote\x1a!.zvote.v1.MsgDelegateVoteResponse\x12@\n" +
	"\bCastVote\x12\x15.zvote.v1.MsgCastVote\x1a\x1d.zvote.v1.MsgCastVoteResponse\x12I\n" +
	"\vRevealShare\x12\x18.zvote.v1.MsgRevealShare\x1a .zvote.v1.MsgRevealShareResponse\x12I\n" +
	"\vSubmitTally\x12\x18.zvote.v1.MsgSubmitTally\x1a .zvote.v1.MsgSubmitTallyResponse\x1a\x05\x80\xe7\xb0*\x01B&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_tx_proto_rawDescOnce sync.Once
	file_zvote_v1_tx_proto_rawDescData []byte
)

func file_zvote_v1_tx_proto_rawDescGZIP() []byte {
	file_zvote_v1_tx_proto_rawDescOnce.Do(func() {
		file_zvote_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)))
	})
	return file_zvote_v1_tx_proto_rawDescData
}

var file_zvote_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_zvote_v1_tx_proto_goTypes = []any{
	(*MsgCreateVotingSession)(nil),         // 0: zvote.v1.MsgCreateVotingSession
	(*MsgCreateVotingSessionResponse)(nil), // 1: zvote.v1.MsgCreateVotingSessionResponse
	(*MsgDelegateVote)(nil),                // 2: zvote.v1.MsgDelegateVote
	(*MsgDelegateVoteResponse)(nil),        // 3: zvote.v1.MsgDelegateVoteResponse
	(*MsgCastVote)(nil),                    // 4: zvote.v1.MsgCastVote
	(*MsgCastVoteResponse)(nil),            // 5: zvote.v1.MsgCastVoteResponse
	(*MsgRevealShare)(nil),                 // 6: zvote.v1.MsgRevealShare
	(*MsgRevealShareResponse)(nil),         // 7: zvote.v1.MsgRevealShareResponse
	(*MsgSubmitTally)(nil),                 // 8: zvote.v1.MsgSubmitTally
	(*TallyEntry)(nil),                     // 9: zvote.v1.TallyEntry
	(*MsgSubmitTallyResponse)(nil),         // 10: zvote.v1.MsgSubmitTallyResponse
	(*Proposal)(nil),                       // 11: zvote.v1.Proposal
}
var file_zvote_v1_tx_proto_depIdxs = []int32{
	11, // 0: zvote.v1.MsgCreateVotingSession.proposals:type_name -> zvote.v1.Proposal
	9,  // 1: zvote.v1.MsgSubmitTally.entries:type_name -> zvote.v1.TallyEntry
	0,  // 2: zvote.v1.Msg.CreateVotingSession:input_type -> zvote.v1.MsgCreateVotingSession
	2,  // 3: zvote.v1.Msg.DelegateVote:input_type -> zvote.v1.MsgDelegateVote
	4,  // 4: zvote.v1.Msg.CastVote:input_type -> zvote.v1.MsgCastVote
	6,  // 5: zvote.v1.Msg.RevealShare:input_type -> zvote.v1.MsgRevealShare
	8,  // 6: zvote.v1.Msg.SubmitTally:input_type -> zvote.v1.MsgSubmitTally
	1,  // 7: zvote.v1.Msg.CreateVotingSession:output_type -> zvote.v1.MsgCreateVotingSessionResponse
	3,  // 8: zvote.v1.Msg.DelegateVote:output_type -> zvote.v1.MsgDelegateVoteResponse
	5,  // 9: zvote.v1.Msg.CastVote:output_type -> zvote.v1.MsgCastVoteResponse
	7,  // 10: zvote.v1.Msg.RevealShare:output_type -> zvote.v1.MsgRevealShareResponse
	10, // 11: zvote.v1.Msg.SubmitTally:output_type -> zvote.v1.MsgSubmitTallyResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_zvote_v1_tx_proto_init() }
func file_zvote_v1_tx_proto_init() {
	if File_zvote_v1_tx_proto != nil {
		return
	}
	file_zvote_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zvote_v1_tx_proto_goTypes,
		DependencyIndexes: file_zvote_v1_tx_proto_depIdxs,
		MessageInfos:      file_zvote_v1_tx_proto_msgTypes,
	}.Build()
	File_zvote_v1_tx_proto = out.File
	file_zvote_v1_tx_proto_goTypes = nil
	file_zvote_v1_tx_proto_depIdxs = nil
}
