// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: zvote/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreateVotingSession_FullMethodName = "/zvote.v1.Msg/CreateVotingSession"
	Msg_DelegateVote_FullMethodName        = "/zvote.v1.Msg/DelegateVote"
	Msg_CastVote_FullMethodName            = "/zvote.v1.Msg/CastVote"
	Msg_RevealShare_FullMethodName         = "/zvote.v1.Msg/RevealShare"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the vote module's Msg service.
// NOTE: Vote transactions use ZKP + RedPallas authentication instead of standard
// Cosmos signatures. In Phase 5, transaction submission bypasses the Cosmos Tx
// envelope entirely; the Msg service is defined here for gRPC registration only.
type MsgClient interface {
	CreateVotingSession(ctx context.Context, in *MsgCreateVotingSession, opts ...grpc.CallOption) (*MsgCreateVotingSessionResponse, error)
	DelegateVote(ctx context.Context, in *MsgDelegateVote, opts ...grpc.CallOption) (*MsgDelegateVoteResponse, error)
	CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error)
	RevealShare(ctx context.Context, in *MsgRevealShare, opts ...grpc.CallOption) (*MsgRevealShareResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateVotingSession(ctx context.Context, in *MsgCreateVotingSession, opts ...grpc.CallOption) (*MsgCreateVotingSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateVotingSessionResponse)
	err := c.cc.Invoke(ctx, Msg_CreateVotingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateVote(ctx context.Context, in *MsgDelegateVote, opts ...grpc.CallOption) (*MsgDelegateVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDelegateVoteResponse)
	err := c.cc.Invoke(ctx, Msg_DelegateVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCastVoteResponse)
	err := c.cc.Invoke(ctx, Msg_CastVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealShare(ctx context.Context, in *MsgRevealShare, opts ...grpc.CallOption) (*MsgRevealShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealShareResponse)
	err := c.cc.Invoke(ctx, Msg_RevealShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the vote module's Msg service.
// NOTE: Vote transactions use ZKP + RedPallas authentication instead of standard
// Cosmos signatures. In Phase 5, transaction submission bypasses the Cosmos Tx
// envelope entirely; the Msg service is defined here for gRPC registration only.
type MsgServer interface {
	CreateVotingSession(context.Context, *MsgCreateVotingSession) (*MsgCreateVotingSessionResponse, error)
	DelegateVote(context.Context, *MsgDelegateVote) (*MsgDelegateVoteResponse, error)
	CastVote(context.Context, *MsgCastVote) (*MsgCastVoteResponse, error)
	RevealShare(context.Context, *MsgRevealShare) (*MsgRevealShareResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreateVotingSession(context.Context, *MsgCreateVotingSession) (*MsgCreateVotingSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVotingSession not implemented")
}
func (UnimplementedMsgServer) DelegateVote(context.Context, *MsgDelegateVote) (*MsgDelegateVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateVote not implemented")
}
func (UnimplementedMsgServer) CastVote(context.Context, *MsgCastVote) (*MsgCastVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedMsgServer) RevealShare(context.Context, *MsgRevealShare) (*MsgRevealShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealShare not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateVotingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVotingSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVotingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateVotingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVotingSession(ctx, req.(*MsgCreateVotingSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DelegateVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateVote(ctx, req.(*MsgDelegateVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCastVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CastVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CastVote(ctx, req.(*MsgCastVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealShare(ctx, req.(*MsgRevealShare))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zvote.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVotingSession",
			Handler:    _Msg_CreateVotingSession_Handler,
		},
		{
			MethodName: "DelegateVote",
			Handler:    _Msg_DelegateVote_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _Msg_CastVote_Handler,
		},
		{
			MethodName: "RevealShare",
			Handler:    _Msg_RevealShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvote/v1/tx.proto",
}
