// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: zvote/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_CreateVotingSession_FullMethodName           = "/zvote.v1.Msg/CreateVotingSession"
	Msg_DelegateVote_FullMethodName                  = "/zvote.v1.Msg/DelegateVote"
	Msg_CastVote_FullMethodName                      = "/zvote.v1.Msg/CastVote"
	Msg_RevealShare_FullMethodName                   = "/zvote.v1.Msg/RevealShare"
	Msg_SubmitTally_FullMethodName                   = "/zvote.v1.Msg/SubmitTally"
	Msg_RegisterPallasKey_FullMethodName             = "/zvote.v1.Msg/RegisterPallasKey"
	Msg_DealExecutiveAuthorityKey_FullMethodName     = "/zvote.v1.Msg/DealExecutiveAuthorityKey"
	Msg_AckExecutiveAuthorityKey_FullMethodName      = "/zvote.v1.Msg/AckExecutiveAuthorityKey"
	Msg_CreateValidatorWithPallasKey_FullMethodName  = "/zvote.v1.Msg/CreateValidatorWithPallasKey"
	Msg_ReInitializeElectionAuthority_FullMethodName = "/zvote.v1.Msg/ReInitializeElectionAuthority"
	Msg_SetVoteManager_FullMethodName                = "/zvote.v1.Msg/SetVoteManager"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the vote module's Msg service.
// NOTE: Vote transactions use ZKP + RedPallas authentication instead of standard
// Cosmos signatures. In Phase 5, transaction submission bypasses the Cosmos Tx
// envelope entirely; the Msg service is defined here for gRPC registration only.
type MsgClient interface {
	CreateVotingSession(ctx context.Context, in *MsgCreateVotingSession, opts ...grpc.CallOption) (*MsgCreateVotingSessionResponse, error)
	DelegateVote(ctx context.Context, in *MsgDelegateVote, opts ...grpc.CallOption) (*MsgDelegateVoteResponse, error)
	CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error)
	RevealShare(ctx context.Context, in *MsgRevealShare, opts ...grpc.CallOption) (*MsgRevealShareResponse, error)
	SubmitTally(ctx context.Context, in *MsgSubmitTally, opts ...grpc.CallOption) (*MsgSubmitTallyResponse, error)
	RegisterPallasKey(ctx context.Context, in *MsgRegisterPallasKey, opts ...grpc.CallOption) (*MsgRegisterPallasKeyResponse, error)
	DealExecutiveAuthorityKey(ctx context.Context, in *MsgDealExecutiveAuthorityKey, opts ...grpc.CallOption) (*MsgDealExecutiveAuthorityKeyResponse, error)
	AckExecutiveAuthorityKey(ctx context.Context, in *MsgAckExecutiveAuthorityKey, opts ...grpc.CallOption) (*MsgAckExecutiveAuthorityKeyResponse, error)
	CreateValidatorWithPallasKey(ctx context.Context, in *MsgCreateValidatorWithPallasKey, opts ...grpc.CallOption) (*MsgCreateValidatorWithPallasKeyResponse, error)
	ReInitializeElectionAuthority(ctx context.Context, in *MsgReInitializeElectionAuthority, opts ...grpc.CallOption) (*MsgReInitializeElectionAuthorityResponse, error)
	SetVoteManager(ctx context.Context, in *MsgSetVoteManager, opts ...grpc.CallOption) (*MsgSetVoteManagerResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateVotingSession(ctx context.Context, in *MsgCreateVotingSession, opts ...grpc.CallOption) (*MsgCreateVotingSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateVotingSessionResponse)
	err := c.cc.Invoke(ctx, Msg_CreateVotingSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DelegateVote(ctx context.Context, in *MsgDelegateVote, opts ...grpc.CallOption) (*MsgDelegateVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDelegateVoteResponse)
	err := c.cc.Invoke(ctx, Msg_DelegateVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CastVote(ctx context.Context, in *MsgCastVote, opts ...grpc.CallOption) (*MsgCastVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCastVoteResponse)
	err := c.cc.Invoke(ctx, Msg_CastVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealShare(ctx context.Context, in *MsgRevealShare, opts ...grpc.CallOption) (*MsgRevealShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevealShareResponse)
	err := c.cc.Invoke(ctx, Msg_RevealShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitTally(ctx context.Context, in *MsgSubmitTally, opts ...grpc.CallOption) (*MsgSubmitTallyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSubmitTallyResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitTally_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterPallasKey(ctx context.Context, in *MsgRegisterPallasKey, opts ...grpc.CallOption) (*MsgRegisterPallasKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterPallasKeyResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterPallasKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DealExecutiveAuthorityKey(ctx context.Context, in *MsgDealExecutiveAuthorityKey, opts ...grpc.CallOption) (*MsgDealExecutiveAuthorityKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgDealExecutiveAuthorityKeyResponse)
	err := c.cc.Invoke(ctx, Msg_DealExecutiveAuthorityKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AckExecutiveAuthorityKey(ctx context.Context, in *MsgAckExecutiveAuthorityKey, opts ...grpc.CallOption) (*MsgAckExecutiveAuthorityKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgAckExecutiveAuthorityKeyResponse)
	err := c.cc.Invoke(ctx, Msg_AckExecutiveAuthorityKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateValidatorWithPallasKey(ctx context.Context, in *MsgCreateValidatorWithPallasKey, opts ...grpc.CallOption) (*MsgCreateValidatorWithPallasKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgCreateValidatorWithPallasKeyResponse)
	err := c.cc.Invoke(ctx, Msg_CreateValidatorWithPallasKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ReInitializeElectionAuthority(ctx context.Context, in *MsgReInitializeElectionAuthority, opts ...grpc.CallOption) (*MsgReInitializeElectionAuthorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgReInitializeElectionAuthorityResponse)
	err := c.cc.Invoke(ctx, Msg_ReInitializeElectionAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetVoteManager(ctx context.Context, in *MsgSetVoteManager, opts ...grpc.CallOption) (*MsgSetVoteManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSetVoteManagerResponse)
	err := c.cc.Invoke(ctx, Msg_SetVoteManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the vote module's Msg service.
// NOTE: Vote transactions use ZKP + RedPallas authentication instead of standard
// Cosmos signatures. In Phase 5, transaction submission bypasses the Cosmos Tx
// envelope entirely; the Msg service is defined here for gRPC registration only.
type MsgServer interface {
	CreateVotingSession(context.Context, *MsgCreateVotingSession) (*MsgCreateVotingSessionResponse, error)
	DelegateVote(context.Context, *MsgDelegateVote) (*MsgDelegateVoteResponse, error)
	CastVote(context.Context, *MsgCastVote) (*MsgCastVoteResponse, error)
	RevealShare(context.Context, *MsgRevealShare) (*MsgRevealShareResponse, error)
	SubmitTally(context.Context, *MsgSubmitTally) (*MsgSubmitTallyResponse, error)
	RegisterPallasKey(context.Context, *MsgRegisterPallasKey) (*MsgRegisterPallasKeyResponse, error)
	DealExecutiveAuthorityKey(context.Context, *MsgDealExecutiveAuthorityKey) (*MsgDealExecutiveAuthorityKeyResponse, error)
	AckExecutiveAuthorityKey(context.Context, *MsgAckExecutiveAuthorityKey) (*MsgAckExecutiveAuthorityKeyResponse, error)
	CreateValidatorWithPallasKey(context.Context, *MsgCreateValidatorWithPallasKey) (*MsgCreateValidatorWithPallasKeyResponse, error)
	ReInitializeElectionAuthority(context.Context, *MsgReInitializeElectionAuthority) (*MsgReInitializeElectionAuthorityResponse, error)
	SetVoteManager(context.Context, *MsgSetVoteManager) (*MsgSetVoteManagerResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) CreateVotingSession(context.Context, *MsgCreateVotingSession) (*MsgCreateVotingSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVotingSession not implemented")
}
func (UnimplementedMsgServer) DelegateVote(context.Context, *MsgDelegateVote) (*MsgDelegateVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelegateVote not implemented")
}
func (UnimplementedMsgServer) CastVote(context.Context, *MsgCastVote) (*MsgCastVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CastVote not implemented")
}
func (UnimplementedMsgServer) RevealShare(context.Context, *MsgRevealShare) (*MsgRevealShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevealShare not implemented")
}
func (UnimplementedMsgServer) SubmitTally(context.Context, *MsgSubmitTally) (*MsgSubmitTallyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTally not implemented")
}
func (UnimplementedMsgServer) RegisterPallasKey(context.Context, *MsgRegisterPallasKey) (*MsgRegisterPallasKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPallasKey not implemented")
}
func (UnimplementedMsgServer) DealExecutiveAuthorityKey(context.Context, *MsgDealExecutiveAuthorityKey) (*MsgDealExecutiveAuthorityKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DealExecutiveAuthorityKey not implemented")
}
func (UnimplementedMsgServer) AckExecutiveAuthorityKey(context.Context, *MsgAckExecutiveAuthorityKey) (*MsgAckExecutiveAuthorityKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckExecutiveAuthorityKey not implemented")
}
func (UnimplementedMsgServer) CreateValidatorWithPallasKey(context.Context, *MsgCreateValidatorWithPallasKey) (*MsgCreateValidatorWithPallasKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateValidatorWithPallasKey not implemented")
}
func (UnimplementedMsgServer) ReInitializeElectionAuthority(context.Context, *MsgReInitializeElectionAuthority) (*MsgReInitializeElectionAuthorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReInitializeElectionAuthority not implemented")
}
func (UnimplementedMsgServer) SetVoteManager(context.Context, *MsgSetVoteManager) (*MsgSetVoteManagerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVoteManager not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call panics, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateVotingSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVotingSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVotingSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateVotingSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVotingSession(ctx, req.(*MsgCreateVotingSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DelegateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDelegateVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DelegateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DelegateVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DelegateVote(ctx, req.(*MsgDelegateVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CastVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCastVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CastVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CastVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CastVote(ctx, req.(*MsgCastVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealShare(ctx, req.(*MsgRevealShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitTally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitTally)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitTally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitTally_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitTally(ctx, req.(*MsgSubmitTally))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterPallasKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterPallasKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterPallasKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterPallasKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterPallasKey(ctx, req.(*MsgRegisterPallasKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DealExecutiveAuthorityKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDealExecutiveAuthorityKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DealExecutiveAuthorityKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DealExecutiveAuthorityKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DealExecutiveAuthorityKey(ctx, req.(*MsgDealExecutiveAuthorityKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AckExecutiveAuthorityKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAckExecutiveAuthorityKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AckExecutiveAuthorityKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AckExecutiveAuthorityKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AckExecutiveAuthorityKey(ctx, req.(*MsgAckExecutiveAuthorityKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateValidatorWithPallasKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateValidatorWithPallasKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateValidatorWithPallasKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateValidatorWithPallasKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateValidatorWithPallasKey(ctx, req.(*MsgCreateValidatorWithPallasKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ReInitializeElectionAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgReInitializeElectionAuthority)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ReInitializeElectionAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ReInitializeElectionAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ReInitializeElectionAuthority(ctx, req.(*MsgReInitializeElectionAuthority))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetVoteManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetVoteManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetVoteManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetVoteManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetVoteManager(ctx, req.(*MsgSetVoteManager))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zvote.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVotingSession",
			Handler:    _Msg_CreateVotingSession_Handler,
		},
		{
			MethodName: "DelegateVote",
			Handler:    _Msg_DelegateVote_Handler,
		},
		{
			MethodName: "CastVote",
			Handler:    _Msg_CastVote_Handler,
		},
		{
			MethodName: "RevealShare",
			Handler:    _Msg_RevealShare_Handler,
		},
		{
			MethodName: "SubmitTally",
			Handler:    _Msg_SubmitTally_Handler,
		},
		{
			MethodName: "RegisterPallasKey",
			Handler:    _Msg_RegisterPallasKey_Handler,
		},
		{
			MethodName: "DealExecutiveAuthorityKey",
			Handler:    _Msg_DealExecutiveAuthorityKey_Handler,
		},
		{
			MethodName: "AckExecutiveAuthorityKey",
			Handler:    _Msg_AckExecutiveAuthorityKey_Handler,
		},
		{
			MethodName: "CreateValidatorWithPallasKey",
			Handler:    _Msg_CreateValidatorWithPallasKey_Handler,
		},
		{
			MethodName: "ReInitializeElectionAuthority",
			Handler:    _Msg_ReInitializeElectionAuthority_Handler,
		},
		{
			MethodName: "SetVoteManager",
			Handler:    _Msg_SetVoteManager_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zvote/v1/tx.proto",
}
