// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus represents the lifecycle state of a voting session.
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_TALLYING    SessionStatus = 2
	SessionStatus_SESSION_STATUS_FINALIZED   SessionStatus = 3
	SessionStatus_SESSION_STATUS_PENDING     SessionStatus = 4 // Ceremony in progress, not yet active
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_TALLYING",
		3: "SESSION_STATUS_FINALIZED",
		4: "SESSION_STATUS_PENDING",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_TALLYING":    2,
		"SESSION_STATUS_FINALIZED":   3,
		"SESSION_STATUS_PENDING":     4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zvote_v1_types_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_zvote_v1_types_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{0}
}

// CeremonyStatus represents the lifecycle state of the EA key ceremony.
type CeremonyStatus int32

const (
	CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED CeremonyStatus = 0
	CeremonyStatus_CEREMONY_STATUS_REGISTERING CeremonyStatus = 1 // Accepting validator pk_i registrations (no timeout)
	CeremonyStatus_CEREMONY_STATUS_DEALT       CeremonyStatus = 2 // DealerTx landed, awaiting acks
	CeremonyStatus_CEREMONY_STATUS_CONFIRMED   CeremonyStatus = 3 // >=2/3 validators acked, ea_pk ready
)

// Enum value maps for CeremonyStatus.
var (
	CeremonyStatus_name = map[int32]string{
		0: "CEREMONY_STATUS_UNSPECIFIED",
		1: "CEREMONY_STATUS_REGISTERING",
		2: "CEREMONY_STATUS_DEALT",
		3: "CEREMONY_STATUS_CONFIRMED",
	}
	CeremonyStatus_value = map[string]int32{
		"CEREMONY_STATUS_UNSPECIFIED": 0,
		"CEREMONY_STATUS_REGISTERING": 1,
		"CEREMONY_STATUS_DEALT":       2,
		"CEREMONY_STATUS_CONFIRMED":   3,
	}
)

func (x CeremonyStatus) Enum() *CeremonyStatus {
	p := new(CeremonyStatus)
	*p = x
	return p
}

func (x CeremonyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CeremonyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zvote_v1_types_proto_enumTypes[1].Descriptor()
}

func (CeremonyStatus) Type() protoreflect.EnumType {
	return &file_zvote_v1_types_proto_enumTypes[1]
}

func (x CeremonyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CeremonyStatus.Descriptor instead.
func (CeremonyStatus) EnumDescriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{1}
}

// VoteOption represents a named choice within a proposal.
type VoteOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 0-indexed
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`  // e.g. "Support", "Oppose"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteOption) Reset() {
	*x = VoteOption{}
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteOption) ProtoMessage() {}

func (x *VoteOption) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteOption.ProtoReflect.Descriptor instead.
func (*VoteOption) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *VoteOption) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VoteOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Proposal represents a single ballot option within a voting session.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Options       []*VoteOption          `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // 2-8 named choices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Proposal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proposal) GetOptions() []*VoteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// VoteRound represents a voting session created by MsgCreateVotingSession.
type VoteRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId       []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	Creator           string                 `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Status            SessionStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=zvote.v1.SessionStatus" json:"status,omitempty"`
	EaPk              []byte                 `protobuf:"bytes,10,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"`       // Election authority public key (Pallas, 32 bytes)
	VkZkp1            []byte                 `protobuf:"bytes,11,opt,name=vk_zkp1,json=vkZkp1,proto3" json:"vk_zkp1,omitempty"` // Verification key for ZKP #1
	VkZkp2            []byte                 `protobuf:"bytes,12,opt,name=vk_zkp2,json=vkZkp2,proto3" json:"vk_zkp2,omitempty"` // Verification key for ZKP #2
	VkZkp3            []byte                 `protobuf:"bytes,13,opt,name=vk_zkp3,json=vkZkp3,proto3" json:"vk_zkp3,omitempty"` // Verification key for ZKP #3
	Proposals         []*Proposal            `protobuf:"bytes,14,rep,name=proposals,proto3" json:"proposals,omitempty"`
	Description       string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`                                   // Human-readable round description
	CreatedAtHeight   uint64                 `protobuf:"varint,16,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"` // Block height at which this round was registered on-chain
	Title             string                 `protobuf:"bytes,17,opt,name=title,proto3" json:"title,omitempty"`                                               // Short human-readable round title
	// Per-round ceremony fields (populated when status = PENDING).
	CeremonyStatus       CeremonyStatus        `protobuf:"varint,18,opt,name=ceremony_status,json=ceremonyStatus,proto3,enum=zvote.v1.CeremonyStatus" json:"ceremony_status,omitempty"`
	CeremonyValidators   []*ValidatorPallasKey `protobuf:"bytes,19,rep,name=ceremony_validators,json=ceremonyValidators,proto3" json:"ceremony_validators,omitempty"`
	CeremonyPayloads     []*DealerPayload      `protobuf:"bytes,20,rep,name=ceremony_payloads,json=ceremonyPayloads,proto3" json:"ceremony_payloads,omitempty"`
	CeremonyAcks         []*AckEntry           `protobuf:"bytes,21,rep,name=ceremony_acks,json=ceremonyAcks,proto3" json:"ceremony_acks,omitempty"`
	CeremonyDealer       string                `protobuf:"bytes,22,opt,name=ceremony_dealer,json=ceremonyDealer,proto3" json:"ceremony_dealer,omitempty"`
	CeremonyPhaseStart   uint64                `protobuf:"varint,23,opt,name=ceremony_phase_start,json=ceremonyPhaseStart,proto3" json:"ceremony_phase_start,omitempty"`
	CeremonyPhaseTimeout uint64                `protobuf:"varint,24,opt,name=ceremony_phase_timeout,json=ceremonyPhaseTimeout,proto3" json:"ceremony_phase_timeout,omitempty"`
	CeremonyLog          []string              `protobuf:"bytes,25,rep,name=ceremony_log,json=ceremonyLog,proto3" json:"ceremony_log,omitempty"` // Timestamped human-readable ceremony log entries
	// Threshold decryption fields (populated by MsgDealExecutiveAuthorityKey in threshold mode).
	// threshold is the minimum number of partial decryptions required to reconstruct the tally.
	// verification_keys holds VK_i = f(i)*G for each validator (same order as ceremony_validators).
	Threshold        uint32   `protobuf:"varint,26,opt,name=threshold,proto3" json:"threshold,omitempty"`                                      // 0 = legacy single-key mode
	VerificationKeys [][]byte `protobuf:"bytes,27,rep,name=verification_keys,json=verificationKeys,proto3" json:"verification_keys,omitempty"` // 32-byte compressed Pallas points, one per ceremony validator
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoteRound) Reset() {
	*x = VoteRound{}
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRound) ProtoMessage() {}

func (x *VoteRound) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRound.ProtoReflect.Descriptor instead.
func (*VoteRound) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *VoteRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *VoteRound) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *VoteRound) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *VoteRound) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *VoteRound) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *VoteRound) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *VoteRound) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *VoteRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *VoteRound) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *VoteRound) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *VoteRound) GetVkZkp1() []byte {
	if x != nil {
		return x.VkZkp1
	}
	return nil
}

func (x *VoteRound) GetVkZkp2() []byte {
	if x != nil {
		return x.VkZkp2
	}
	return nil
}

func (x *VoteRound) GetVkZkp3() []byte {
	if x != nil {
		return x.VkZkp3
	}
	return nil
}

func (x *VoteRound) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *VoteRound) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VoteRound) GetCreatedAtHeight() uint64 {
	if x != nil {
		return x.CreatedAtHeight
	}
	return 0
}

func (x *VoteRound) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VoteRound) GetCeremonyStatus() CeremonyStatus {
	if x != nil {
		return x.CeremonyStatus
	}
	return CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED
}

func (x *VoteRound) GetCeremonyValidators() []*ValidatorPallasKey {
	if x != nil {
		return x.CeremonyValidators
	}
	return nil
}

func (x *VoteRound) GetCeremonyPayloads() []*DealerPayload {
	if x != nil {
		return x.CeremonyPayloads
	}
	return nil
}

func (x *VoteRound) GetCeremonyAcks() []*AckEntry {
	if x != nil {
		return x.CeremonyAcks
	}
	return nil
}

func (x *VoteRound) GetCeremonyDealer() string {
	if x != nil {
		return x.CeremonyDealer
	}
	return ""
}

func (x *VoteRound) GetCeremonyPhaseStart() uint64 {
	if x != nil {
		return x.CeremonyPhaseStart
	}
	return 0
}

func (x *VoteRound) GetCeremonyPhaseTimeout() uint64 {
	if x != nil {
		return x.CeremonyPhaseTimeout
	}
	return 0
}

func (x *VoteRound) GetCeremonyLog() []string {
	if x != nil {
		return x.CeremonyLog
	}
	return nil
}

func (x *VoteRound) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *VoteRound) GetVerificationKeys() [][]byte {
	if x != nil {
		return x.VerificationKeys
	}
	return nil
}

// VoteManagerState stores the singleton vote manager address.
type VoteManagerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteManagerState) Reset() {
	*x = VoteManagerState{}
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteManagerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteManagerState) ProtoMessage() {}

func (x *VoteManagerState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteManagerState.ProtoReflect.Descriptor instead.
func (*VoteManagerState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *VoteManagerState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// CommitmentTreeState holds the current state of the append-only commitment tree.
type CommitmentTreeState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextIndex       uint64                 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`                       // Next leaf index to write
	Root            []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                                                   // Current Merkle root (empty until EndBlocker computes it)
	Height          uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                                              // Block height at which this root was last computed
	NextIndexAtRoot uint64                 `protobuf:"varint,4,opt,name=next_index_at_root,json=nextIndexAtRoot,proto3" json:"next_index_at_root,omitempty"` // NextIndex at the time the root was last stored (used to compute per-block leaf ranges)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitmentTreeState) Reset() {
	*x = CommitmentTreeState{}
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentTreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentTreeState) ProtoMessage() {}

func (x *CommitmentTreeState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentTreeState.ProtoReflect.Descriptor instead.
func (*CommitmentTreeState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *CommitmentTreeState) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *CommitmentTreeState) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CommitmentTreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommitmentTreeState) GetNextIndexAtRoot() uint64 {
	if x != nil {
		return x.NextIndexAtRoot
	}
	return 0
}

// GenesisState defines the vote module's genesis state.
type GenesisState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rounds           []*VoteRound           `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	TreeState        *CommitmentTreeState   `protobuf:"bytes,2,opt,name=tree_state,json=treeState,proto3" json:"tree_state,omitempty"`
	CommitmentLeaves []*CommitmentLeaf      `protobuf:"bytes,3,rep,name=commitment_leaves,json=commitmentLeaves,proto3" json:"commitment_leaves,omitempty"`
	Nullifiers       []*NullifierEntry      `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	VoteManager      string                 `protobuf:"bytes,5,opt,name=vote_manager,json=voteManager,proto3" json:"vote_manager,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_zvote_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *GenesisState) GetRounds() []*VoteRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GenesisState) GetTreeState() *CommitmentTreeState {
	if x != nil {
		return x.TreeState
	}
	return nil
}

func (x *GenesisState) GetCommitmentLeaves() []*CommitmentLeaf {
	if x != nil {
		return x.CommitmentLeaves
	}
	return nil
}

func (x *GenesisState) GetNullifiers() []*NullifierEntry {
	if x != nil {
		return x.Nullifiers
	}
	return nil
}

func (x *GenesisState) GetVoteManager() string {
	if x != nil {
		return x.VoteManager
	}
	return ""
}

// CommitmentLeaf is an entry in the append-only commitment tree.
type CommitmentLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentLeaf) Reset() {
	*x = CommitmentLeaf{}
	mi := &file_zvote_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentLeaf) ProtoMessage() {}

func (x *CommitmentLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentLeaf.ProtoReflect.Descriptor instead.
func (*CommitmentLeaf) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *CommitmentLeaf) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitmentLeaf) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// NullifierEntry is a recorded nullifier, scoped by type and round.
type NullifierEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullifier     []byte                 `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	NullifierType uint32                 `protobuf:"varint,2,opt,name=nullifier_type,json=nullifierType,proto3" json:"nullifier_type,omitempty"` // 0=gov, 1=vote-authority-note, 2=share (maps to NullifierType)
	RoundId       []byte                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`                    // voting round this nullifier belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullifierEntry) Reset() {
	*x = NullifierEntry{}
	mi := &file_zvote_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullifierEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullifierEntry) ProtoMessage() {}

func (x *NullifierEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullifierEntry.ProtoReflect.Descriptor instead.
func (*NullifierEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *NullifierEntry) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *NullifierEntry) GetNullifierType() uint32 {
	if x != nil {
		return x.NullifierType
	}
	return 0
}

func (x *NullifierEntry) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

// TallyResult stores a finalized vote total for one (round, proposal, decision) tuple.
// Written by MsgSubmitTally, read by the TallyResults query.
type TallyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision  uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue    uint64                 `protobuf:"varint,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"` // Decrypted aggregate (zatoshi)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TallyResult) Reset() {
	*x = TallyResult{}
	mi := &file_zvote_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyResult) ProtoMessage() {}

func (x *TallyResult) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyResult.ProtoReflect.Descriptor instead.
func (*TallyResult) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *TallyResult) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *TallyResult) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyResult) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyResult) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// BlockCommitments holds the commitment leaves appended during a single block.
// Used by the CommitmentLeaves query to serve tree data to remote clients
// implementing the TreeSyncApi trait.
type BlockCommitments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`                           // Block height
	StartIndex    uint64                 `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"` // Index of the first leaf in this block
	Leaves        [][]byte               `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`                            // Commitment leaves (each 32 bytes, Pallas Fp LE)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommitments) Reset() {
	*x = BlockCommitments{}
	mi := &file_zvote_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommitments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommitments) ProtoMessage() {}

func (x *BlockCommitments) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommitments.ProtoReflect.Descriptor instead.
func (*BlockCommitments) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *BlockCommitments) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockCommitments) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *BlockCommitments) GetLeaves() [][]byte {
	if x != nil {
		return x.Leaves
	}
	return nil
}

// ProposalSummary is a denormalized view of a proposal for the VoteSummary query.
type ProposalSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Options       []*OptionSummary       `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalSummary) Reset() {
	*x = ProposalSummary{}
	mi := &file_zvote_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalSummary) ProtoMessage() {}

func (x *ProposalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalSummary.ProtoReflect.Descriptor instead.
func (*ProposalSummary) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *ProposalSummary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProposalSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProposalSummary) GetOptions() []*OptionSummary {
	if x != nil {
		return x.Options
	}
	return nil
}

// OptionSummary is a denormalized view of a vote option for the VoteSummary query.
type OptionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	BallotCount   uint64                 `protobuf:"varint,3,opt,name=ballot_count,json=ballotCount,proto3" json:"ballot_count,omitempty"` // shares revealed for this (proposal, decision)
	TotalValue    uint64                 `protobuf:"varint,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`    // only populated when status = FINALIZED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionSummary) Reset() {
	*x = OptionSummary{}
	mi := &file_zvote_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionSummary) ProtoMessage() {}

func (x *OptionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionSummary.ProtoReflect.Descriptor instead.
func (*OptionSummary) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *OptionSummary) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OptionSummary) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *OptionSummary) GetBallotCount() uint64 {
	if x != nil {
		return x.BallotCount
	}
	return 0
}

func (x *OptionSummary) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// CeremonyState tracks the singleton EA key ceremony lifecycle.
type CeremonyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CeremonyStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=zvote.v1.CeremonyStatus" json:"status,omitempty"`
	EaPk          []byte                 `protobuf:"bytes,2,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"`                          // Set when DealerTx lands
	Validators    []*ValidatorPallasKey  `protobuf:"bytes,3,rep,name=validators,proto3" json:"validators,omitempty"`                          // All registered pk_i
	Payloads      []*DealerPayload       `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`                              // ECIES envelopes from DealerTx
	Acks          []*AckEntry            `protobuf:"bytes,5,rep,name=acks,proto3" json:"acks,omitempty"`                                      // Per-validator ack status
	Dealer        string                 `protobuf:"bytes,6,opt,name=dealer,proto3" json:"dealer,omitempty"`                                  // Validator address of the dealer
	PhaseStart    uint64                 `protobuf:"varint,7,opt,name=phase_start,json=phaseStart,proto3" json:"phase_start,omitempty"`       // Unix seconds when current phase started
	PhaseTimeout  uint64                 `protobuf:"varint,8,opt,name=phase_timeout,json=phaseTimeout,proto3" json:"phase_timeout,omitempty"` // Timeout in seconds for current phase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CeremonyState) Reset() {
	*x = CeremonyState{}
	mi := &file_zvote_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CeremonyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeremonyState) ProtoMessage() {}

func (x *CeremonyState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeremonyState.ProtoReflect.Descriptor instead.
func (*CeremonyState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *CeremonyState) GetStatus() CeremonyStatus {
	if x != nil {
		return x.Status
	}
	return CeremonyStatus_CEREMONY_STATUS_UNSPECIFIED
}

func (x *CeremonyState) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *CeremonyState) GetValidators() []*ValidatorPallasKey {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *CeremonyState) GetPayloads() []*DealerPayload {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *CeremonyState) GetAcks() []*AckEntry {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *CeremonyState) GetDealer() string {
	if x != nil {
		return x.Dealer
	}
	return ""
}

func (x *CeremonyState) GetPhaseStart() uint64 {
	if x != nil {
		return x.PhaseStart
	}
	return 0
}

func (x *CeremonyState) GetPhaseTimeout() uint64 {
	if x != nil {
		return x.PhaseTimeout
	}
	return 0
}

// ValidatorPallasKey records a validator's registered Pallas public key.
type ValidatorPallasKey struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	PallasPk         []byte                 `protobuf:"bytes,2,opt,name=pallas_pk,json=pallasPk,proto3" json:"pallas_pk,omitempty"` // Compressed Pallas point (32 bytes)
	// shamir_index is the original 1-based Shamir evaluation point f(shamir_index)
	// assigned to this validator when the round ceremony was created. It is set
	// once at round creation and never changed, even when non-acking validators
	// are stripped from CeremonyValidators by StripNonAckersFromRound. Partial
	// decrypt injectors and the SubmitPartialDecryption handler must use this
	// field for Lagrange interpolation indices, not the post-stripping array position.
	ShamirIndex   uint32 `protobuf:"varint,3,opt,name=shamir_index,json=shamirIndex,proto3" json:"shamir_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorPallasKey) Reset() {
	*x = ValidatorPallasKey{}
	mi := &file_zvote_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorPallasKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorPallasKey) ProtoMessage() {}

func (x *ValidatorPallasKey) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorPallasKey.ProtoReflect.Descriptor instead.
func (*ValidatorPallasKey) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *ValidatorPallasKey) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *ValidatorPallasKey) GetPallasPk() []byte {
	if x != nil {
		return x.PallasPk
	}
	return nil
}

func (x *ValidatorPallasKey) GetShamirIndex() uint32 {
	if x != nil {
		return x.ShamirIndex
	}
	return 0
}

// DealerPayload is an ECIES envelope from the dealer to a specific validator.
type DealerPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	EphemeralPk      []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pk,json=ephemeralPk,proto3" json:"ephemeral_pk,omitempty"` // E_i (32 bytes)
	Ciphertext       []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                      // ct_i: ChaCha20-Poly1305 (32 + 16 = 48 bytes)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DealerPayload) Reset() {
	*x = DealerPayload{}
	mi := &file_zvote_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealerPayload) ProtoMessage() {}

func (x *DealerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealerPayload.ProtoReflect.Descriptor instead.
func (*DealerPayload) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *DealerPayload) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *DealerPayload) GetEphemeralPk() []byte {
	if x != nil {
		return x.EphemeralPk
	}
	return nil
}

func (x *DealerPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

// AckEntry records a validator's acknowledgement of receiving their share.
type AckEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatorAddress string                 `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	AckSignature     []byte                 `protobuf:"bytes,2,opt,name=ack_signature,json=ackSignature,proto3" json:"ack_signature,omitempty"` // Signature over H("ack" || ea_pk || validator_address)
	AckHeight        uint64                 `protobuf:"varint,3,opt,name=ack_height,json=ackHeight,proto3" json:"ack_height,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckEntry) Reset() {
	*x = AckEntry{}
	mi := &file_zvote_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEntry) ProtoMessage() {}

func (x *AckEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEntry.ProtoReflect.Descriptor instead.
func (*AckEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *AckEntry) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *AckEntry) GetAckSignature() []byte {
	if x != nil {
		return x.AckSignature
	}
	return nil
}

func (x *AckEntry) GetAckHeight() uint64 {
	if x != nil {
		return x.AckHeight
	}
	return 0
}

var File_zvote_v1_types_proto protoreflect.FileDescriptor

const file_zvote_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14zvote/v1/types.proto\x12\bzvote.v1\"8\n" +
	"\n" +
	"VoteOption\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x82\x01\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\aoptions\x18\x04 \x03(\v2\x14.zvote.v1.VoteOptionR\aoptions\"\xea\b\n" +
	"\tVoteRound\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x18\n" +
	"\acreator\x18\b \x01(\tR\acreator\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.zvote.v1.SessionStatusR\x06status\x12\x13\n" +
	"\x05ea_pk\x18\n" +
	" \x01(\fR\x04eaPk\x12\x17\n" +
	"\avk_zkp1\x18\v \x01(\fR\x06vkZkp1\x12\x17\n" +
	"\avk_zkp2\x18\f \x01(\fR\x06vkZkp2\x12\x17\n" +
	"\avk_zkp3\x18\r \x01(\fR\x06vkZkp3\x120\n" +
	"\tproposals\x18\x0e \x03(\v2\x12.zvote.v1.ProposalR\tproposals\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12*\n" +
	"\x11created_at_height\x18\x10 \x01(\x04R\x0fcreatedAtHeight\x12\x14\n" +
	"\x05title\x18\x11 \x01(\tR\x05title\x12A\n" +
	"\x0fceremony_status\x18\x12 \x01(\x0e2\x18.zvote.v1.CeremonyStatusR\x0eceremonyStatus\x12M\n" +
	"\x13ceremony_validators\x18\x13 \x03(\v2\x1c.zvote.v1.ValidatorPallasKeyR\x12ceremonyValidators\x12D\n" +
	"\x11ceremony_payloads\x18\x14 \x03(\v2\x17.zvote.v1.DealerPayloadR\x10ceremonyPayloads\x127\n" +
	"\rceremony_acks\x18\x15 \x03(\v2\x12.zvote.v1.AckEntryR\fceremonyAcks\x12'\n" +
	"\x0fceremony_dealer\x18\x16 \x01(\tR\x0eceremonyDealer\x120\n" +
	"\x14ceremony_phase_start\x18\x17 \x01(\x04R\x12ceremonyPhaseStart\x124\n" +
	"\x16ceremony_phase_timeout\x18\x18 \x01(\x04R\x14ceremonyPhaseTimeout\x12!\n" +
	"\fceremony_log\x18\x19 \x03(\tR\vceremonyLog\x12\x1c\n" +
	"\tthreshold\x18\x1a \x01(\rR\tthreshold\x12+\n" +
	"\x11verification_keys\x18\x1b \x03(\fR\x10verificationKeys\",\n" +
	"\x10VoteManagerState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x8d\x01\n" +
	"\x13CommitmentTreeState\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x04R\tnextIndex\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12+\n" +
	"\x12next_index_at_root\x18\x04 \x01(\x04R\x0fnextIndexAtRoot\"\x9d\x02\n" +
	"\fGenesisState\x12+\n" +
	"\x06rounds\x18\x01 \x03(\v2\x13.zvote.v1.VoteRoundR\x06rounds\x12<\n" +
	"\n" +
	"tree_state\x18\x02 \x01(\v2\x1d.zvote.v1.CommitmentTreeStateR\ttreeState\x12E\n" +
	"\x11commitment_leaves\x18\x03 \x03(\v2\x18.zvote.v1.CommitmentLeafR\x10commitmentLeaves\x128\n" +
	"\n" +
	"nullifiers\x18\x04 \x03(\v2\x18.zvote.v1.NullifierEntryR\n" +
	"nullifiers\x12!\n" +
	"\fvote_manager\x18\x05 \x01(\tR\vvoteManager\"<\n" +
	"\x0eCommitmentLeaf\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"p\n" +
	"\x0eNullifierEntry\x12\x1c\n" +
	"\tnullifier\x18\x01 \x01(\fR\tnullifier\x12%\n" +
	"\x0enullifier_type\x18\x02 \x01(\rR\rnullifierType\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\fR\aroundId\"\x98\x01\n" +
	"\vTallyResult\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x04R\n" +
	"totalValue\"c\n" +
	"\x10BlockCommitments\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vstart_index\x18\x02 \x01(\x04R\n" +
	"startIndex\x12\x16\n" +
	"\x06leaves\x18\x03 \x03(\fR\x06leaves\"\x8c\x01\n" +
	"\x0fProposalSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\aoptions\x18\x04 \x03(\v2\x17.zvote.v1.OptionSummaryR\aoptions\"\x7f\n" +
	"\rOptionSummary\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\fballot_count\x18\x03 \x01(\x04R\vballotCount\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x04R\n" +
	"totalValue\"\xcf\x02\n" +
	"\rCeremonyState\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.zvote.v1.CeremonyStatusR\x06status\x12\x13\n" +
	"\x05ea_pk\x18\x02 \x01(\fR\x04eaPk\x12<\n" +
	"\n" +
	"validators\x18\x03 \x03(\v2\x1c.zvote.v1.ValidatorPallasKeyR\n" +
	"validators\x123\n" +
	"\bpayloads\x18\x04 \x03(\v2\x17.zvote.v1.DealerPayloadR\bpayloads\x12&\n" +
	"\x04acks\x18\x05 \x03(\v2\x12.zvote.v1.AckEntryR\x04acks\x12\x16\n" +
	"\x06dealer\x18\x06 \x01(\tR\x06dealer\x12\x1f\n" +
	"\vphase_start\x18\a \x01(\x04R\n" +
	"phaseStart\x12#\n" +
	"\rphase_timeout\x18\b \x01(\x04R\fphaseTimeout\"\x81\x01\n" +
	"\x12ValidatorPallasKey\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12\x1b\n" +
	"\tpallas_pk\x18\x02 \x01(\fR\bpallasPk\x12!\n" +
	"\fshamir_index\x18\x03 \x01(\rR\vshamirIndex\"\x7f\n" +
	"\rDealerPayload\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12!\n" +
	"\fephemeral_pk\x18\x02 \x01(\fR\vephemeralPk\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\"{\n" +
	"\bAckEntry\x12+\n" +
	"\x11validator_address\x18\x01 \x01(\tR\x10validatorAddress\x12#\n" +
	"\rack_signature\x18\x02 \x01(\fR\fackSignature\x12\x1d\n" +
	"\n" +
	"ack_height\x18\x03 \x01(\x04R\tackHeight*\xa1\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SESSION_STATUS_TALLYING\x10\x02\x12\x1c\n" +
	"\x18SESSION_STATUS_FINALIZED\x10\x03\x12\x1a\n" +
	"\x16SESSION_STATUS_PENDING\x10\x04*\x8c\x01\n" +
	"\x0eCeremonyStatus\x12\x1f\n" +
	"\x1bCEREMONY_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCEREMONY_STATUS_REGISTERING\x10\x01\x12\x19\n" +
	"\x15CEREMONY_STATUS_DEALT\x10\x02\x12\x1d\n" +
	"\x19CEREMONY_STATUS_CONFIRMED\x10\x03B&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_types_proto_rawDescOnce sync.Once
	file_zvote_v1_types_proto_rawDescData []byte
)

func file_zvote_v1_types_proto_rawDescGZIP() []byte {
	file_zvote_v1_types_proto_rawDescOnce.Do(func() {
		file_zvote_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)))
	})
	return file_zvote_v1_types_proto_rawDescData
}

var file_zvote_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_zvote_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_zvote_v1_types_proto_goTypes = []any{
	(SessionStatus)(0),          // 0: zvote.v1.SessionStatus
	(CeremonyStatus)(0),         // 1: zvote.v1.CeremonyStatus
	(*VoteOption)(nil),          // 2: zvote.v1.VoteOption
	(*Proposal)(nil),            // 3: zvote.v1.Proposal
	(*VoteRound)(nil),           // 4: zvote.v1.VoteRound
	(*VoteManagerState)(nil),    // 5: zvote.v1.VoteManagerState
	(*CommitmentTreeState)(nil), // 6: zvote.v1.CommitmentTreeState
	(*GenesisState)(nil),        // 7: zvote.v1.GenesisState
	(*CommitmentLeaf)(nil),      // 8: zvote.v1.CommitmentLeaf
	(*NullifierEntry)(nil),      // 9: zvote.v1.NullifierEntry
	(*TallyResult)(nil),         // 10: zvote.v1.TallyResult
	(*BlockCommitments)(nil),    // 11: zvote.v1.BlockCommitments
	(*ProposalSummary)(nil),     // 12: zvote.v1.ProposalSummary
	(*OptionSummary)(nil),       // 13: zvote.v1.OptionSummary
	(*CeremonyState)(nil),       // 14: zvote.v1.CeremonyState
	(*ValidatorPallasKey)(nil),  // 15: zvote.v1.ValidatorPallasKey
	(*DealerPayload)(nil),       // 16: zvote.v1.DealerPayload
	(*AckEntry)(nil),            // 17: zvote.v1.AckEntry
}
var file_zvote_v1_types_proto_depIdxs = []int32{
	2,  // 0: zvote.v1.Proposal.options:type_name -> zvote.v1.VoteOption
	0,  // 1: zvote.v1.VoteRound.status:type_name -> zvote.v1.SessionStatus
	3,  // 2: zvote.v1.VoteRound.proposals:type_name -> zvote.v1.Proposal
	1,  // 3: zvote.v1.VoteRound.ceremony_status:type_name -> zvote.v1.CeremonyStatus
	15, // 4: zvote.v1.VoteRound.ceremony_validators:type_name -> zvote.v1.ValidatorPallasKey
	16, // 5: zvote.v1.VoteRound.ceremony_payloads:type_name -> zvote.v1.DealerPayload
	17, // 6: zvote.v1.VoteRound.ceremony_acks:type_name -> zvote.v1.AckEntry
	4,  // 7: zvote.v1.GenesisState.rounds:type_name -> zvote.v1.VoteRound
	6,  // 8: zvote.v1.GenesisState.tree_state:type_name -> zvote.v1.CommitmentTreeState
	8,  // 9: zvote.v1.GenesisState.commitment_leaves:type_name -> zvote.v1.CommitmentLeaf
	9,  // 10: zvote.v1.GenesisState.nullifiers:type_name -> zvote.v1.NullifierEntry
	13, // 11: zvote.v1.ProposalSummary.options:type_name -> zvote.v1.OptionSummary
	1,  // 12: zvote.v1.CeremonyState.status:type_name -> zvote.v1.CeremonyStatus
	15, // 13: zvote.v1.CeremonyState.validators:type_name -> zvote.v1.ValidatorPallasKey
	16, // 14: zvote.v1.CeremonyState.payloads:type_name -> zvote.v1.DealerPayload
	17, // 15: zvote.v1.CeremonyState.acks:type_name -> zvote.v1.AckEntry
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_zvote_v1_types_proto_init() }
func file_zvote_v1_types_proto_init() {
	if File_zvote_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zvote_v1_types_proto_goTypes,
		DependencyIndexes: file_zvote_v1_types_proto_depIdxs,
		EnumInfos:         file_zvote_v1_types_proto_enumTypes,
		MessageInfos:      file_zvote_v1_types_proto_msgTypes,
	}.Build()
	File_zvote_v1_types_proto = out.File
	file_zvote_v1_types_proto_goTypes = nil
	file_zvote_v1_types_proto_depIdxs = nil
}
