// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus represents the lifecycle state of a voting session.
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_TALLYING    SessionStatus = 2
	SessionStatus_SESSION_STATUS_FINALIZED   SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_TALLYING",
		3: "SESSION_STATUS_FINALIZED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_TALLYING":    2,
		"SESSION_STATUS_FINALIZED":   3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zvote_v1_types_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_zvote_v1_types_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{0}
}

// Proposal represents a single ballot option within a voting session.
type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// VoteRound represents a voting session created by MsgCreateVotingSession.
type VoteRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId       []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	Creator           string                 `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Status            SessionStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=zvote.v1.SessionStatus" json:"status,omitempty"`
	EaPk              []byte                 `protobuf:"bytes,10,opt,name=ea_pk,json=eaPk,proto3" json:"ea_pk,omitempty"`       // Election authority public key (Pallas, 32 bytes)
	VkZkp1            []byte                 `protobuf:"bytes,11,opt,name=vk_zkp1,json=vkZkp1,proto3" json:"vk_zkp1,omitempty"` // Verification key for ZKP #1
	VkZkp2            []byte                 `protobuf:"bytes,12,opt,name=vk_zkp2,json=vkZkp2,proto3" json:"vk_zkp2,omitempty"` // Verification key for ZKP #2
	VkZkp3            []byte                 `protobuf:"bytes,13,opt,name=vk_zkp3,json=vkZkp3,proto3" json:"vk_zkp3,omitempty"` // Verification key for ZKP #3
	Proposals         []*Proposal            `protobuf:"bytes,14,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoteRound) Reset() {
	*x = VoteRound{}
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRound) ProtoMessage() {}

func (x *VoteRound) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRound.ProtoReflect.Descriptor instead.
func (*VoteRound) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *VoteRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *VoteRound) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *VoteRound) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *VoteRound) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *VoteRound) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *VoteRound) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *VoteRound) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *VoteRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *VoteRound) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *VoteRound) GetEaPk() []byte {
	if x != nil {
		return x.EaPk
	}
	return nil
}

func (x *VoteRound) GetVkZkp1() []byte {
	if x != nil {
		return x.VkZkp1
	}
	return nil
}

func (x *VoteRound) GetVkZkp2() []byte {
	if x != nil {
		return x.VkZkp2
	}
	return nil
}

func (x *VoteRound) GetVkZkp3() []byte {
	if x != nil {
		return x.VkZkp3
	}
	return nil
}

func (x *VoteRound) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

// CommitmentTreeState holds the current state of the append-only commitment tree.
type CommitmentTreeState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NextIndex       uint64                 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`                       // Next leaf index to write
	Root            []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                                                   // Current Merkle root (empty until EndBlocker computes it)
	Height          uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                                              // Block height at which this root was last computed
	NextIndexAtRoot uint64                 `protobuf:"varint,4,opt,name=next_index_at_root,json=nextIndexAtRoot,proto3" json:"next_index_at_root,omitempty"` // NextIndex at the time the root was last stored (used to compute per-block leaf ranges)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitmentTreeState) Reset() {
	*x = CommitmentTreeState{}
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentTreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentTreeState) ProtoMessage() {}

func (x *CommitmentTreeState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentTreeState.ProtoReflect.Descriptor instead.
func (*CommitmentTreeState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *CommitmentTreeState) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *CommitmentTreeState) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CommitmentTreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CommitmentTreeState) GetNextIndexAtRoot() uint64 {
	if x != nil {
		return x.NextIndexAtRoot
	}
	return 0
}

// GenesisState defines the vote module's genesis state.
type GenesisState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rounds           []*VoteRound           `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	TreeState        *CommitmentTreeState   `protobuf:"bytes,2,opt,name=tree_state,json=treeState,proto3" json:"tree_state,omitempty"`
	CommitmentLeaves []*CommitmentLeaf      `protobuf:"bytes,3,rep,name=commitment_leaves,json=commitmentLeaves,proto3" json:"commitment_leaves,omitempty"`
	Nullifiers       []*NullifierEntry      `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *GenesisState) GetRounds() []*VoteRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GenesisState) GetTreeState() *CommitmentTreeState {
	if x != nil {
		return x.TreeState
	}
	return nil
}

func (x *GenesisState) GetCommitmentLeaves() []*CommitmentLeaf {
	if x != nil {
		return x.CommitmentLeaves
	}
	return nil
}

func (x *GenesisState) GetNullifiers() []*NullifierEntry {
	if x != nil {
		return x.Nullifiers
	}
	return nil
}

// CommitmentLeaf is an entry in the append-only commitment tree.
type CommitmentLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentLeaf) Reset() {
	*x = CommitmentLeaf{}
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentLeaf) ProtoMessage() {}

func (x *CommitmentLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentLeaf.ProtoReflect.Descriptor instead.
func (*CommitmentLeaf) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *CommitmentLeaf) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitmentLeaf) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// NullifierEntry is a recorded nullifier, scoped by type and round.
type NullifierEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullifier     []byte                 `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	NullifierType uint32                 `protobuf:"varint,2,opt,name=nullifier_type,json=nullifierType,proto3" json:"nullifier_type,omitempty"` // 0=gov, 1=vote-authority-note, 2=share (maps to NullifierType)
	RoundId       []byte                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`                    // voting round this nullifier belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullifierEntry) Reset() {
	*x = NullifierEntry{}
	mi := &file_zvote_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullifierEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullifierEntry) ProtoMessage() {}

func (x *NullifierEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullifierEntry.ProtoReflect.Descriptor instead.
func (*NullifierEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *NullifierEntry) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *NullifierEntry) GetNullifierType() uint32 {
	if x != nil {
		return x.NullifierType
	}
	return 0
}

func (x *NullifierEntry) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

// TallyResult stores a finalized vote total for one (round, proposal, decision) tuple.
// Written by MsgSubmitTally, read by the TallyResults query.
type TallyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	ProposalId    uint32                 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision  uint32                 `protobuf:"varint,3,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	TotalValue    uint64                 `protobuf:"varint,4,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"` // Decrypted aggregate (zatoshi)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TallyResult) Reset() {
	*x = TallyResult{}
	mi := &file_zvote_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyResult) ProtoMessage() {}

func (x *TallyResult) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyResult.ProtoReflect.Descriptor instead.
func (*TallyResult) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *TallyResult) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *TallyResult) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *TallyResult) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *TallyResult) GetTotalValue() uint64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

// BlockCommitments holds the commitment leaves appended during a single block.
// Used by the CommitmentLeaves query to serve tree data to remote clients
// implementing the TreeSyncApi trait.
type BlockCommitments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`                           // Block height
	StartIndex    uint64                 `protobuf:"varint,2,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"` // Index of the first leaf in this block
	Leaves        [][]byte               `protobuf:"bytes,3,rep,name=leaves,proto3" json:"leaves,omitempty"`                            // Commitment leaves (each 32 bytes, Pallas Fp LE)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommitments) Reset() {
	*x = BlockCommitments{}
	mi := &file_zvote_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommitments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommitments) ProtoMessage() {}

func (x *BlockCommitments) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommitments.ProtoReflect.Descriptor instead.
func (*BlockCommitments) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *BlockCommitments) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockCommitments) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *BlockCommitments) GetLeaves() [][]byte {
	if x != nil {
		return x.Leaves
	}
	return nil
}

var File_zvote_v1_types_proto protoreflect.FileDescriptor

const file_zvote_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14zvote/v1/types.proto\x12\bzvote.v1\"R\n" +
	"\bProposal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xf6\x03\n" +
	"\tVoteRound\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x18\n" +
	"\acreator\x18\b \x01(\tR\acreator\x12/\n" +
	"\x06status\x18\t \x01(\x0e2\x17.zvote.v1.SessionStatusR\x06status\x12\x13\n" +
	"\x05ea_pk\x18\n" +
	" \x01(\fR\x04eaPk\x12\x17\n" +
	"\avk_zkp1\x18\v \x01(\fR\x06vkZkp1\x12\x17\n" +
	"\avk_zkp2\x18\f \x01(\fR\x06vkZkp2\x12\x17\n" +
	"\avk_zkp3\x18\r \x01(\fR\x06vkZkp3\x120\n" +
	"\tproposals\x18\x0e \x03(\v2\x12.zvote.v1.ProposalR\tproposals\"\x8d\x01\n" +
	"\x13CommitmentTreeState\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x04R\tnextIndex\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12+\n" +
	"\x12next_index_at_root\x18\x04 \x01(\x04R\x0fnextIndexAtRoot\"\xfa\x01\n" +
	"\fGenesisState\x12+\n" +
	"\x06rounds\x18\x01 \x03(\v2\x13.zvote.v1.VoteRoundR\x06rounds\x12<\n" +
	"\n" +
	"tree_state\x18\x02 \x01(\v2\x1d.zvote.v1.CommitmentTreeStateR\ttreeState\x12E\n" +
	"\x11commitment_leaves\x18\x03 \x03(\v2\x18.zvote.v1.CommitmentLeafR\x10commitmentLeaves\x128\n" +
	"\n" +
	"nullifiers\x18\x04 \x03(\v2\x18.zvote.v1.NullifierEntryR\n" +
	"nullifiers\"<\n" +
	"\x0eCommitmentLeaf\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"p\n" +
	"\x0eNullifierEntry\x12\x1c\n" +
	"\tnullifier\x18\x01 \x01(\fR\tnullifier\x12%\n" +
	"\x0enullifier_type\x18\x02 \x01(\rR\rnullifierType\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\fR\aroundId\"\x98\x01\n" +
	"\vTallyResult\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12\x1f\n" +
	"\vproposal_id\x18\x02 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x03 \x01(\rR\fvoteDecision\x12\x1f\n" +
	"\vtotal_value\x18\x04 \x01(\x04R\n" +
	"totalValue\"c\n" +
	"\x10BlockCommitments\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vstart_index\x18\x02 \x01(\x04R\n" +
	"startIndex\x12\x16\n" +
	"\x06leaves\x18\x03 \x03(\fR\x06leaves*\x85\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17SESSION_STATUS_TALLYING\x10\x02\x12\x1c\n" +
	"\x18SESSION_STATUS_FINALIZED\x10\x03B&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_types_proto_rawDescOnce sync.Once
	file_zvote_v1_types_proto_rawDescData []byte
)

func file_zvote_v1_types_proto_rawDescGZIP() []byte {
	file_zvote_v1_types_proto_rawDescOnce.Do(func() {
		file_zvote_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)))
	})
	return file_zvote_v1_types_proto_rawDescData
}

var file_zvote_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zvote_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zvote_v1_types_proto_goTypes = []any{
	(SessionStatus)(0),          // 0: zvote.v1.SessionStatus
	(*Proposal)(nil),            // 1: zvote.v1.Proposal
	(*VoteRound)(nil),           // 2: zvote.v1.VoteRound
	(*CommitmentTreeState)(nil), // 3: zvote.v1.CommitmentTreeState
	(*GenesisState)(nil),        // 4: zvote.v1.GenesisState
	(*CommitmentLeaf)(nil),      // 5: zvote.v1.CommitmentLeaf
	(*NullifierEntry)(nil),      // 6: zvote.v1.NullifierEntry
	(*TallyResult)(nil),         // 7: zvote.v1.TallyResult
	(*BlockCommitments)(nil),    // 8: zvote.v1.BlockCommitments
}
var file_zvote_v1_types_proto_depIdxs = []int32{
	0, // 0: zvote.v1.VoteRound.status:type_name -> zvote.v1.SessionStatus
	1, // 1: zvote.v1.VoteRound.proposals:type_name -> zvote.v1.Proposal
	2, // 2: zvote.v1.GenesisState.rounds:type_name -> zvote.v1.VoteRound
	3, // 3: zvote.v1.GenesisState.tree_state:type_name -> zvote.v1.CommitmentTreeState
	5, // 4: zvote.v1.GenesisState.commitment_leaves:type_name -> zvote.v1.CommitmentLeaf
	6, // 5: zvote.v1.GenesisState.nullifiers:type_name -> zvote.v1.NullifierEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_zvote_v1_types_proto_init() }
func file_zvote_v1_types_proto_init() {
	if File_zvote_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zvote_v1_types_proto_goTypes,
		DependencyIndexes: file_zvote_v1_types_proto_depIdxs,
		EnumInfos:         file_zvote_v1_types_proto_enumTypes,
		MessageInfos:      file_zvote_v1_types_proto_msgTypes,
	}.Build()
	File_zvote_v1_types_proto = out.File
	file_zvote_v1_types_proto_goTypes = nil
	file_zvote_v1_types_proto_depIdxs = nil
}
