// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VoteRound represents a voting session created by MsgCreateVotingSession.
type VoteRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId       []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	Creator           string                 `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoteRound) Reset() {
	*x = VoteRound{}
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRound) ProtoMessage() {}

func (x *VoteRound) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRound.ProtoReflect.Descriptor instead.
func (*VoteRound) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRound) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *VoteRound) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *VoteRound) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *VoteRound) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *VoteRound) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *VoteRound) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *VoteRound) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

func (x *VoteRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

// CommitmentTreeState holds the current state of the append-only commitment tree.
type CommitmentTreeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextIndex     uint64                 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"` // Next leaf index to write
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                             // Current Merkle root (empty until EndBlocker computes it)
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                        // Block height at which this root was last computed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentTreeState) Reset() {
	*x = CommitmentTreeState{}
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentTreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentTreeState) ProtoMessage() {}

func (x *CommitmentTreeState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentTreeState.ProtoReflect.Descriptor instead.
func (*CommitmentTreeState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *CommitmentTreeState) GetNextIndex() uint64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

func (x *CommitmentTreeState) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *CommitmentTreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// GenesisState defines the vote module's genesis state.
type GenesisState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rounds           []*VoteRound           `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	TreeState        *CommitmentTreeState   `protobuf:"bytes,2,opt,name=tree_state,json=treeState,proto3" json:"tree_state,omitempty"`
	CommitmentLeaves []*CommitmentLeaf      `protobuf:"bytes,3,rep,name=commitment_leaves,json=commitmentLeaves,proto3" json:"commitment_leaves,omitempty"`
	Nullifiers       []*NullifierEntry      `protobuf:"bytes,4,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisState) GetRounds() []*VoteRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *GenesisState) GetTreeState() *CommitmentTreeState {
	if x != nil {
		return x.TreeState
	}
	return nil
}

func (x *GenesisState) GetCommitmentLeaves() []*CommitmentLeaf {
	if x != nil {
		return x.CommitmentLeaves
	}
	return nil
}

func (x *GenesisState) GetNullifiers() []*NullifierEntry {
	if x != nil {
		return x.Nullifiers
	}
	return nil
}

// CommitmentLeaf is an entry in the append-only commitment tree.
type CommitmentLeaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitmentLeaf) Reset() {
	*x = CommitmentLeaf{}
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitmentLeaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitmentLeaf) ProtoMessage() {}

func (x *CommitmentLeaf) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitmentLeaf.ProtoReflect.Descriptor instead.
func (*CommitmentLeaf) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *CommitmentLeaf) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CommitmentLeaf) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// NullifierEntry is a recorded nullifier, scoped by type and round.
type NullifierEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nullifier     []byte                 `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	NullifierType uint32                 `protobuf:"varint,2,opt,name=nullifier_type,json=nullifierType,proto3" json:"nullifier_type,omitempty"` // 0=gov, 1=vote-authority-note, 2=share (maps to NullifierType)
	RoundId       []byte                 `protobuf:"bytes,3,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`                    // voting round this nullifier belongs to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullifierEntry) Reset() {
	*x = NullifierEntry{}
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullifierEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullifierEntry) ProtoMessage() {}

func (x *NullifierEntry) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullifierEntry.ProtoReflect.Descriptor instead.
func (*NullifierEntry) Descriptor() ([]byte, []int) {
	return file_zvote_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *NullifierEntry) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

func (x *NullifierEntry) GetNullifierType() uint32 {
	if x != nil {
		return x.NullifierType
	}
	return 0
}

func (x *NullifierEntry) GetRoundId() []byte {
	if x != nil {
		return x.RoundId
	}
	return nil
}

var File_zvote_v1_types_proto protoreflect.FileDescriptor

const file_zvote_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14zvote/v1/types.proto\x12\bzvote.v1\"\xb3\x02\n" +
	"\tVoteRound\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\x12\x18\n" +
	"\acreator\x18\b \x01(\tR\acreator\"`\n" +
	"\x13CommitmentTreeState\x12\x1d\n" +
	"\n" +
	"next_index\x18\x01 \x01(\x04R\tnextIndex\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\"\xfa\x01\n" +
	"\fGenesisState\x12+\n" +
	"\x06rounds\x18\x01 \x03(\v2\x13.zvote.v1.VoteRoundR\x06rounds\x12<\n" +
	"\n" +
	"tree_state\x18\x02 \x01(\v2\x1d.zvote.v1.CommitmentTreeStateR\ttreeState\x12E\n" +
	"\x11commitment_leaves\x18\x03 \x03(\v2\x18.zvote.v1.CommitmentLeafR\x10commitmentLeaves\x128\n" +
	"\n" +
	"nullifiers\x18\x04 \x03(\v2\x18.zvote.v1.NullifierEntryR\n" +
	"nullifiers\"<\n" +
	"\x0eCommitmentLeaf\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"p\n" +
	"\x0eNullifierEntry\x12\x1c\n" +
	"\tnullifier\x18\x01 \x01(\fR\tnullifier\x12%\n" +
	"\x0enullifier_type\x18\x02 \x01(\rR\rnullifierType\x12\x19\n" +
	"\bround_id\x18\x03 \x01(\fR\aroundIdB&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_types_proto_rawDescOnce sync.Once
	file_zvote_v1_types_proto_rawDescData []byte
)

func file_zvote_v1_types_proto_rawDescGZIP() []byte {
	file_zvote_v1_types_proto_rawDescOnce.Do(func() {
		file_zvote_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)))
	})
	return file_zvote_v1_types_proto_rawDescData
}

var file_zvote_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zvote_v1_types_proto_goTypes = []any{
	(*VoteRound)(nil),           // 0: zvote.v1.VoteRound
	(*CommitmentTreeState)(nil), // 1: zvote.v1.CommitmentTreeState
	(*GenesisState)(nil),        // 2: zvote.v1.GenesisState
	(*CommitmentLeaf)(nil),      // 3: zvote.v1.CommitmentLeaf
	(*NullifierEntry)(nil),      // 4: zvote.v1.NullifierEntry
}
var file_zvote_v1_types_proto_depIdxs = []int32{
	0, // 0: zvote.v1.GenesisState.rounds:type_name -> zvote.v1.VoteRound
	1, // 1: zvote.v1.GenesisState.tree_state:type_name -> zvote.v1.CommitmentTreeState
	3, // 2: zvote.v1.GenesisState.commitment_leaves:type_name -> zvote.v1.CommitmentLeaf
	4, // 3: zvote.v1.GenesisState.nullifiers:type_name -> zvote.v1.NullifierEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zvote_v1_types_proto_init() }
func file_zvote_v1_types_proto_init() {
	if File_zvote_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_types_proto_rawDesc), len(file_zvote_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zvote_v1_types_proto_goTypes,
		DependencyIndexes: file_zvote_v1_types_proto_depIdxs,
		MessageInfos:      file_zvote_v1_types_proto_msgTypes,
	}.Build()
	File_zvote_v1_types_proto = out.File
	file_zvote_v1_types_proto_goTypes = nil
	file_zvote_v1_types_proto_depIdxs = nil
}
