//go:build halo2

package halo2

import (
	"encoding/binary"
	"os"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/z-cale/zally/crypto/zkp"
)

// TestGenerateShareRevealRoundTrip generates a share reveal proof and verifies it.
//
// This test requires the halo2 build tag and the Rust static library:
//
//	make circuits
//	go test -tags halo2 -count=1 -v ./crypto/zkp/halo2/ -run TestGenerateShareRevealRoundTrip
//
// The test reads inputs from a fixture file generated by the Rust fixture
// generator (cargo test --release -- generate_fixtures --ignored).
// Proof generation takes ~30-60s in release mode.
func TestGenerateShareRevealRoundTrip(t *testing.T) {
	// Read fixture file.
	// Format (1104 bytes):
	//   [0..772)      merkle_path
	//   [772..1028)   all_enc_shares (256 bytes)
	//   [1028..1032)  share_index (u32 LE)
	//   [1032..1036)  proposal_id (u32 LE)
	//   [1036..1040)  vote_decision (u32 LE)
	//   [1040..1072)  round_id (32 bytes)
	//   [1072..1104)  shares_hash (32 bytes)
	fixture, err := os.ReadFile("../testdata/share_reveal_inputs.bin")
	require.NoError(t, err, "fixture file missing — run: make fixtures")
	require.Len(t, fixture, 1104, "unexpected fixture size")

	merklePath := fixture[0:772]

	var allEncShares [8][32]byte
	for i := 0; i < 8; i++ {
		copy(allEncShares[i][:], fixture[772+i*32:772+(i+1)*32])
	}

	shareIndex := binary.LittleEndian.Uint32(fixture[1028:1032])
	proposalID := binary.LittleEndian.Uint32(fixture[1032:1036])
	voteDecision := binary.LittleEndian.Uint32(fixture[1036:1040])

	var roundID [32]byte
	copy(roundID[:], fixture[1040:1072])

	var sharesHash [32]byte
	copy(sharesHash[:], fixture[1072:1104])

	// Generate proof.
	t.Log("generating share reveal proof (this takes ~30-60s)...")
	proof, nullifier, treeRoot, err := GenerateShareRevealProof(
		merklePath,
		allEncShares,
		shareIndex,
		proposalID, voteDecision,
		roundID,
		sharesHash,
	)
	require.NoError(t, err)
	require.NotEmpty(t, proof)

	t.Logf("proof: %d bytes, nullifier: %x..., treeRoot: %x...",
		len(proof), nullifier[:4], treeRoot[:4])

	// Verify the generated proof using the verify FFI.
	// Build EncShare: C1 || C2 from allEncShares at shareIndex.
	idx := int(shareIndex)
	encShare := make([]byte, 64)
	copy(encShare[:32], allEncShares[idx*2][:])
	copy(encShare[32:], allEncShares[idx*2+1][:])

	inputs := zkp.VoteShareInputs{
		ShareNullifier:   nullifier[:],
		EncShare:         encShare,
		ProposalId:       proposalID,
		VoteDecision:     voteDecision,
		VoteRoundId:      roundID[:],
		VoteCommTreeRoot: treeRoot[:],
	}

	err = VerifyShareRevealProof(proof, inputs)
	require.NoError(t, err, "generated proof should verify")
}
