//go:build halo2

package halo2

import (
	"encoding/binary"
	"os"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/valargroup/shielded-vote/crypto/zkp"
)

// TestGenerateShareRevealRoundTrip generates a share reveal proof and verifies it.
//
// This test requires the halo2 build tag and the Rust static library:
//
//	make circuits
//	go test -tags halo2 -count=1 -v ./crypto/zkp/halo2/ -run TestGenerateShareRevealRoundTrip
//
// The test reads inputs from a fixture file generated by the Rust fixture
// generator (cargo test --release -- generate_fixtures --ignored).
// Proof generation takes ~5-15s in release mode.
func TestGenerateShareRevealRoundTrip(t *testing.T) {
	// Format (1488 bytes):
	//   [0..772)       merkle_path
	//   [772..1284)    share_comms (512 bytes: 16 × 32)
	//   [1284..1316)   primary_blind (32 bytes)
	//   [1316..1348)   enc_c1_x (32 bytes, LE Fp — ZKP public input)
	//   [1348..1380)   enc_c2_x (32 bytes, LE Fp — ZKP public input)
	//   [1380..1384)   share_index (u32 LE)
	//   [1384..1388)   proposal_id (u32 LE)
	//   [1388..1392)   vote_decision (u32 LE)
	//   [1392..1424)   round_id (32 bytes)
	//   [1424..1488)   enc_share (64 bytes: C1 compressed || C2 compressed Pallas points)
	fixture, err := os.ReadFile("../testdata/share_reveal_inputs.bin")
	require.NoError(t, err, "fixture file missing — run: make fixtures")
	require.Len(t, fixture, 1488, "unexpected fixture size — run: make fixtures")

	merklePath := fixture[0:772]

	var shareComms [16][32]byte
	for i := 0; i < 16; i++ {
		copy(shareComms[i][:], fixture[772+i*32:772+(i+1)*32])
	}

	var primaryBlind [32]byte
	copy(primaryBlind[:], fixture[1284:1316])

	var encC1X [32]byte
	copy(encC1X[:], fixture[1316:1348])

	var encC2X [32]byte
	copy(encC2X[:], fixture[1348:1380])

	shareIndex := binary.LittleEndian.Uint32(fixture[1380:1384])
	proposalID := binary.LittleEndian.Uint32(fixture[1384:1388])
	voteDecision := binary.LittleEndian.Uint32(fixture[1388:1392])

	var roundID [32]byte
	copy(roundID[:], fixture[1392:1424])

	// enc_share: the full compressed ElGamal ciphertext (C1 || C2, 64 bytes).
	// Read directly from the fixture — these are real Pallas compressed points
	// produced by the Rust fixture generator, compatible with UnmarshalCiphertext.
	encShare := make([]byte, 64)
	copy(encShare, fixture[1424:1488])

	// Generate proof.
	t.Log("generating share reveal proof (this takes ~5-15s)...")
	proof, nullifier, treeRoot, err := GenerateShareRevealProof(
		merklePath,
		shareComms,
		primaryBlind,
		encC1X,
		encC2X,
		shareIndex,
		proposalID, voteDecision,
		roundID,
	)
	require.NoError(t, err)
	require.NotEmpty(t, proof)

	t.Logf("proof: %d bytes, nullifier: %x..., treeRoot: %x...",
		len(proof), nullifier[:4], treeRoot[:4])

	inputs := zkp.VoteShareInputs{
		ShareNullifier:   nullifier[:],
		EncShare:         encShare,
		ProposalId:       proposalID,
		VoteDecision:     voteDecision,
		VoteRoundId:      roundID[:],
		VoteCommTreeRoot: treeRoot[:],
	}

	err = VerifyShareRevealProof(proof, inputs)
	require.NoError(t, err, "generated proof should verify")
}
