package keeper

import (
	"context"
	"fmt"

	"cosmossdk.io/core/store"
	"cosmossdk.io/log"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"golang.org/x/crypto/blake2b"
	"google.golang.org/protobuf/proto"

	"github.com/z-cale/zally/x/vote/types"
)

// Keeper of the vote module store.
//
// KV Store Layout:
//   0x01 || type || round_id || nf  -> []byte{1}         (nullifier set, scoped by type+round)
//   0x02 || uint64 index            -> commitment_bytes   (append-only commitment tree)
//   0x03 || uint64 height           -> root_bytes         (commitment tree roots by height)
//   0x04 || round_id                -> VoteRound protobuf (vote round data)
//   0x05 || round_id || proposal_id || decision -> uint64 amount (tally accumulator)
//   0x06                            -> CommitmentTreeState protobuf (tree metadata)
//
// Uses google.golang.org/protobuf/proto for binary marshal (our types are
// generated by protoc-gen-go, not gogoproto).
type Keeper struct {
	storeService store.KVStoreService
	authority    string
	logger       log.Logger
}

// NewKeeper creates a new vote module keeper.
func NewKeeper(
	storeService store.KVStoreService,
	authority string,
	logger log.Logger,
) Keeper {
	return Keeper{
		storeService: storeService,
		authority:    authority,
		logger:       logger.With("module", "x/"+types.ModuleName),
	}
}

// OpenKVStore opens the module's KV store from a context.
func (k Keeper) OpenKVStore(ctx context.Context) store.KVStore {
	return k.storeService.OpenKVStore(ctx)
}

// marshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func marshal(m proto.Message) ([]byte, error) {
	return proto.Marshal(m)
}

// unmarshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func unmarshal(bz []byte, m proto.Message) error {
	return proto.Unmarshal(bz, m)
}

// GetAuthority returns the module's authority address.
func (k Keeper) GetAuthority() string {
	return k.authority
}

// Logger returns a module-specific logger.
func (k Keeper) Logger() log.Logger {
	return k.logger
}

// HasNullifier checks if a nullifier has already been recorded in the given
// type-scoped, round-scoped nullifier set.
func (k Keeper) HasNullifier(ctx store.KVStore, nfType types.NullifierType, roundID, nullifier []byte) (bool, error) {
	return ctx.Has(types.NullifierKey(nfType, roundID, nullifier))
}

// SetNullifier records a nullifier as spent in the given type-scoped,
// round-scoped nullifier set.
func (k Keeper) SetNullifier(ctx store.KVStore, nfType types.NullifierType, roundID, nullifier []byte) error {
	return ctx.Set(types.NullifierKey(nfType, roundID, nullifier), []byte{1})
}

// GetVoteRound retrieves a vote round by its ID.
func (k Keeper) GetVoteRound(kvStore store.KVStore, roundID []byte) (*types.VoteRound, error) {
	bz, err := kvStore.Get(types.VoteRoundKey(roundID))
	if err != nil {
		return nil, err
	}
	if bz == nil {
		return nil, types.ErrRoundNotFound
	}

	var round types.VoteRound
	if err := unmarshal(bz, &round); err != nil {
		return nil, err
	}
	return &round, nil
}

// SetVoteRound stores a vote round.
func (k Keeper) SetVoteRound(kvStore store.KVStore, round *types.VoteRound) error {
	bz, err := marshal(round)
	if err != nil {
		return err
	}
	return kvStore.Set(types.VoteRoundKey(round.VoteRoundId), bz)
}

// GetCommitmentTreeState returns the current state of the commitment tree.
func (k Keeper) GetCommitmentTreeState(kvStore store.KVStore) (*types.CommitmentTreeState, error) {
	bz, err := kvStore.Get(types.TreeStateKey)
	if err != nil {
		return nil, err
	}
	if bz == nil {
		// Return default state if not initialized.
		return &types.CommitmentTreeState{NextIndex: 0}, nil
	}

	var state types.CommitmentTreeState
	if err := unmarshal(bz, &state); err != nil {
		return nil, err
	}
	return &state, nil
}

// SetCommitmentTreeState stores the commitment tree state.
func (k Keeper) SetCommitmentTreeState(kvStore store.KVStore, state *types.CommitmentTreeState) error {
	bz, err := marshal(state)
	if err != nil {
		return err
	}
	return kvStore.Set(types.TreeStateKey, bz)
}

// AppendCommitment appends a commitment to the tree and returns its index.
func (k Keeper) AppendCommitment(kvStore store.KVStore, commitment []byte) (uint64, error) {
	state, err := k.GetCommitmentTreeState(kvStore)
	if err != nil {
		return 0, err
	}

	index := state.NextIndex

	// Write the leaf.
	if err := kvStore.Set(types.CommitmentLeafKey(index), commitment); err != nil {
		return 0, err
	}

	// Increment next_index.
	state.NextIndex = index + 1
	if err := k.SetCommitmentTreeState(kvStore, state); err != nil {
		return 0, err
	}

	return index, nil
}

// ComputeTreeRoot computes the commitment tree root as Blake2b-256 over all leaves.
// This is a placeholder; production will use an incremental Poseidon Merkle tree.
func (k Keeper) ComputeTreeRoot(kvStore store.KVStore, nextIndex uint64) ([]byte, error) {
	if nextIndex == 0 {
		return nil, nil
	}
	h, _ := blake2b.New256(nil) // unkeyed; never errors
	for i := uint64(0); i < nextIndex; i++ {
		leaf, err := kvStore.Get(types.CommitmentLeafKey(i))
		if err != nil {
			return nil, err
		}
		h.Write(leaf)
	}
	return h.Sum(nil), nil
}

// GetCommitmentRootAtHeight returns the commitment tree root stored at a specific height.
func (k Keeper) GetCommitmentRootAtHeight(kvStore store.KVStore, height uint64) ([]byte, error) {
	return kvStore.Get(types.CommitmentRootKey(height))
}

// SetCommitmentRootAtHeight stores the commitment tree root for a specific height.
func (k Keeper) SetCommitmentRootAtHeight(kvStore store.KVStore, height uint64, root []byte) error {
	return kvStore.Set(types.CommitmentRootKey(height), root)
}

// GetTally returns the accumulated tally for a (round, proposal, decision) tuple.
func (k Keeper) GetTally(kvStore store.KVStore, roundID []byte, proposalID, decision uint32) (uint64, error) {
	bz, err := kvStore.Get(types.TallyKey(roundID, proposalID, decision))
	if err != nil {
		return 0, err
	}
	if bz == nil {
		return 0, nil
	}
	if len(bz) != 8 {
		return 0, types.ErrInvalidField
	}
	return getUint64BE(bz), nil
}

// AddToTally adds amount to the tally for a (round, proposal, decision) tuple.
func (k Keeper) AddToTally(kvStore store.KVStore, roundID []byte, proposalID, decision uint32, amount uint64) error {
	current, err := k.GetTally(kvStore, roundID, proposalID, decision)
	if err != nil {
		return err
	}
	newAmount := current + amount

	bz := make([]byte, 8)
	putUint64BE(bz, newAmount)
	return kvStore.Set(types.TallyKey(roundID, proposalID, decision), bz)
}

// GetProposalTally returns all tallied votes for a (round, proposal) pair,
// keyed by decision ID. Iterates over the tally prefix
// 0x05 || round_id || proposal_id to collect all decision → amount entries.
func (k Keeper) GetProposalTally(kvStore store.KVStore, roundID []byte, proposalID uint32) (map[uint32]uint64, error) {
	prefix := types.TallyPrefixForProposal(roundID, proposalID)
	end := types.PrefixEndBytes(prefix)

	iter, err := kvStore.Iterator(prefix, end)
	if err != nil {
		return nil, err
	}
	defer iter.Close()

	tally := make(map[uint32]uint64)
	for ; iter.Valid(); iter.Next() {
		key := iter.Key()
		val := iter.Value()

		// The decision is the last 4 bytes of the key.
		if len(key) < 4 {
			continue
		}
		decision := getUint32BE(key[len(key)-4:])
		if len(val) != 8 {
			continue
		}
		amount := getUint64BE(val)
		tally[decision] = amount
	}

	return tally, nil
}

// getUint32BE reads a uint32 from big-endian bytes.
func getUint32BE(b []byte) uint32 {
	return uint32(b[0])<<24 | uint32(b[1])<<16 | uint32(b[2])<<8 | uint32(b[3])
}

// ---------------------------------------------------------------------------
// Validation helpers (used by the ante validation pipeline, Phase 3)
// ---------------------------------------------------------------------------

// ValidateRoundActive checks that a vote round exists and has not expired.
// It reads the VoteRound from the KV store and compares its VoteEndTime against
// the current block time.
func (k Keeper) ValidateRoundActive(ctx context.Context, roundID []byte) error {
	kvStore := k.OpenKVStore(ctx)
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err // wraps ErrRoundNotFound if missing
	}

	sdkCtx := sdk.UnwrapSDKContext(ctx)
	blockTime := uint64(sdkCtx.BlockTime().Unix())

	if blockTime >= round.VoteEndTime {
		return fmt.Errorf("%w: vote_end_time %d <= block_time %d", types.ErrRoundNotActive, round.VoteEndTime, blockTime)
	}

	return nil
}

// CheckNullifiersUnique verifies that none of the provided nullifiers have
// already been recorded in the type-scoped, round-scoped nullifier set.
// This runs on every check including RecheckTx, because nullifiers may have
// been consumed by the newly committed block.
func (k Keeper) CheckNullifiersUnique(ctx context.Context, nfType types.NullifierType, roundID []byte, nullifiers [][]byte) error {
	kvStore := k.OpenKVStore(ctx)
	for _, nf := range nullifiers {
		has, err := k.HasNullifier(kvStore, nfType, roundID, nf)
		if err != nil {
			return err
		}
		if has {
			return fmt.Errorf("%w: %x", types.ErrDuplicateNullifier, nf)
		}
	}
	return nil
}

// putUint64BE writes a uint64 in big-endian byte order.
func putUint64BE(b []byte, v uint64) {
	b[0] = byte(v >> 56)
	b[1] = byte(v >> 48)
	b[2] = byte(v >> 40)
	b[3] = byte(v >> 32)
	b[4] = byte(v >> 24)
	b[5] = byte(v >> 16)
	b[6] = byte(v >> 8)
	b[7] = byte(v)
}

// getUint64BE reads a uint64 from big-endian bytes.
func getUint64BE(b []byte) uint64 {
	return uint64(b[0])<<56 | uint64(b[1])<<48 | uint64(b[2])<<40 | uint64(b[3])<<32 |
		uint64(b[4])<<24 | uint64(b[5])<<16 | uint64(b[6])<<8 | uint64(b[7])
}
