package keeper

import (
	"context"
	"fmt"

	"cosmossdk.io/core/store"
	"cosmossdk.io/log"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"golang.org/x/crypto/blake2b"
	"google.golang.org/protobuf/proto"

	"github.com/z-cale/zally/crypto/elgamal"
	"github.com/z-cale/zally/x/vote/types"
)

// Keeper of the vote module store.
//
// KV Store Layout:
//   0x01 || type || round_id || nf  -> []byte{1}         (nullifier set, scoped by type+round)
//   0x02 || uint64 index            -> commitment_bytes   (append-only commitment tree)
//   0x03 || uint64 height           -> root_bytes         (commitment tree roots by height)
//   0x04 || round_id                -> VoteRound protobuf (vote round data)
//   0x05 || round_id || proposal_id || decision -> []byte (64 bytes: ElGamal ciphertext)
//   0x06                            -> CommitmentTreeState protobuf (tree metadata)
//
// Uses google.golang.org/protobuf/proto for binary marshal (our types are
// generated by protoc-gen-go, not gogoproto).
type Keeper struct {
	storeService store.KVStoreService
	authority    string
	logger       log.Logger
}

// NewKeeper creates a new vote module keeper.
func NewKeeper(
	storeService store.KVStoreService,
	authority string,
	logger log.Logger,
) Keeper {
	return Keeper{
		storeService: storeService,
		authority:    authority,
		logger:       logger.With("module", "x/"+types.ModuleName),
	}
}

// OpenKVStore opens the module's KV store from a context.
func (k Keeper) OpenKVStore(ctx context.Context) store.KVStore {
	return k.storeService.OpenKVStore(ctx)
}

// marshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func marshal(m proto.Message) ([]byte, error) {
	return proto.Marshal(m)
}

// unmarshal is a helper using google.golang.org/protobuf/proto (not gogoproto).
func unmarshal(bz []byte, m proto.Message) error {
	return proto.Unmarshal(bz, m)
}

// GetAuthority returns the module's authority address.
func (k Keeper) GetAuthority() string {
	return k.authority
}

// Logger returns a module-specific logger.
func (k Keeper) Logger() log.Logger {
	return k.logger
}

// HasNullifier checks if a nullifier has already been recorded in the given
// type-scoped, round-scoped nullifier set.
func (k Keeper) HasNullifier(ctx store.KVStore, nfType types.NullifierType, roundID, nullifier []byte) (bool, error) {
	return ctx.Has(types.NullifierKey(nfType, roundID, nullifier))
}

// SetNullifier records a nullifier as spent in the given type-scoped,
// round-scoped nullifier set.
func (k Keeper) SetNullifier(ctx store.KVStore, nfType types.NullifierType, roundID, nullifier []byte) error {
	return ctx.Set(types.NullifierKey(nfType, roundID, nullifier), []byte{1})
}

// GetVoteRound retrieves a vote round by its ID.
func (k Keeper) GetVoteRound(kvStore store.KVStore, roundID []byte) (*types.VoteRound, error) {
	bz, err := kvStore.Get(types.VoteRoundKey(roundID))
	if err != nil {
		return nil, err
	}
	if bz == nil {
		return nil, types.ErrRoundNotFound
	}

	var round types.VoteRound
	if err := unmarshal(bz, &round); err != nil {
		return nil, err
	}
	return &round, nil
}

// SetVoteRound stores a vote round.
func (k Keeper) SetVoteRound(kvStore store.KVStore, round *types.VoteRound) error {
	bz, err := marshal(round)
	if err != nil {
		return err
	}
	return kvStore.Set(types.VoteRoundKey(round.VoteRoundId), bz)
}

// GetCommitmentTreeState returns the current state of the commitment tree.
func (k Keeper) GetCommitmentTreeState(kvStore store.KVStore) (*types.CommitmentTreeState, error) {
	bz, err := kvStore.Get(types.TreeStateKey)
	if err != nil {
		return nil, err
	}
	if bz == nil {
		// Return default state if not initialized.
		return &types.CommitmentTreeState{NextIndex: 0}, nil
	}

	var state types.CommitmentTreeState
	if err := unmarshal(bz, &state); err != nil {
		return nil, err
	}
	return &state, nil
}

// SetCommitmentTreeState stores the commitment tree state.
func (k Keeper) SetCommitmentTreeState(kvStore store.KVStore, state *types.CommitmentTreeState) error {
	bz, err := marshal(state)
	if err != nil {
		return err
	}
	return kvStore.Set(types.TreeStateKey, bz)
}

// AppendCommitment appends a commitment to the tree and returns its index.
func (k Keeper) AppendCommitment(kvStore store.KVStore, commitment []byte) (uint64, error) {
	state, err := k.GetCommitmentTreeState(kvStore)
	if err != nil {
		return 0, err
	}

	index := state.NextIndex

	// Write the leaf.
	if err := kvStore.Set(types.CommitmentLeafKey(index), commitment); err != nil {
		return 0, err
	}

	// Increment next_index.
	state.NextIndex = index + 1
	if err := k.SetCommitmentTreeState(kvStore, state); err != nil {
		return 0, err
	}

	return index, nil
}

// ComputeTreeRoot computes the commitment tree root as Blake2b-256 over all leaves.
// This is a placeholder; production will use an incremental Poseidon Merkle tree.
func (k Keeper) ComputeTreeRoot(kvStore store.KVStore, nextIndex uint64) ([]byte, error) {
	if nextIndex == 0 {
		return nil, nil
	}
	h, _ := blake2b.New256(nil) // unkeyed; never errors
	for i := uint64(0); i < nextIndex; i++ {
		leaf, err := kvStore.Get(types.CommitmentLeafKey(i))
		if err != nil {
			return nil, err
		}
		h.Write(leaf)
	}
	return h.Sum(nil), nil
}

// GetCommitmentRootAtHeight returns the commitment tree root stored at a specific height.
func (k Keeper) GetCommitmentRootAtHeight(kvStore store.KVStore, height uint64) ([]byte, error) {
	return kvStore.Get(types.CommitmentRootKey(height))
}

// SetCommitmentRootAtHeight stores the commitment tree root for a specific height.
func (k Keeper) SetCommitmentRootAtHeight(kvStore store.KVStore, height uint64, root []byte) error {
	return kvStore.Set(types.CommitmentRootKey(height), root)
}

// GetTally returns the accumulated ciphertext tally for a (round, proposal, decision) tuple.
// Returns nil if no tally exists for this tuple.
func (k Keeper) GetTally(kvStore store.KVStore, roundID []byte, proposalID, decision uint32) ([]byte, error) {
	bz, err := kvStore.Get(types.TallyKey(roundID, proposalID, decision))
	if err != nil {
		return nil, err
	}
	return bz, nil // nil means no tally yet
}

// AddToTally accumulates an ElGamal ciphertext (encShareBytes, 64 bytes) into
// the tally for a (round, proposal, decision) tuple using HomomorphicAdd.
func (k Keeper) AddToTally(kvStore store.KVStore, roundID []byte, proposalID, decision uint32, encShareBytes []byte) error {
	key := types.TallyKey(roundID, proposalID, decision)
	existing, err := kvStore.Get(key)
	if err != nil {
		return err
	}

	if existing == nil {
		// First share: store directly (identity + X = X).
		return kvStore.Set(key, encShareBytes)
	}

	// Deserialize both, HomomorphicAdd, serialize result.
	acc, err := elgamal.UnmarshalCiphertext(existing)
	if err != nil {
		return fmt.Errorf("failed to unmarshal accumulator: %w", err)
	}
	share, err := elgamal.UnmarshalCiphertext(encShareBytes)
	if err != nil {
		return fmt.Errorf("failed to unmarshal enc_share: %w", err)
	}
	result := elgamal.HomomorphicAdd(acc, share)
	resultBytes, err := elgamal.MarshalCiphertext(result)
	if err != nil {
		return fmt.Errorf("failed to marshal accumulated ciphertext: %w", err)
	}
	return kvStore.Set(key, resultBytes)
}

// GetProposalTally returns all tallied ciphertexts for a (round, proposal) pair,
// keyed by decision ID. Iterates over the tally prefix
// 0x05 || round_id || proposal_id to collect all decision → ciphertext entries.
func (k Keeper) GetProposalTally(kvStore store.KVStore, roundID []byte, proposalID uint32) (map[uint32][]byte, error) {
	prefix := types.TallyPrefixForProposal(roundID, proposalID)
	end := types.PrefixEndBytes(prefix)

	iter, err := kvStore.Iterator(prefix, end)
	if err != nil {
		return nil, err
	}
	defer iter.Close()

	tally := make(map[uint32][]byte)
	for ; iter.Valid(); iter.Next() {
		key := iter.Key()
		val := iter.Value()

		// The decision is the last 4 bytes of the key.
		if len(key) < 4 {
			continue
		}
		decision := getUint32BE(key[len(key)-4:])
		// Store the raw ciphertext bytes.
		ct := make([]byte, len(val))
		copy(ct, val)
		tally[decision] = ct
	}

	return tally, nil
}

// getUint32BE reads a uint32 from big-endian bytes.
func getUint32BE(b []byte) uint32 {
	return uint32(b[0])<<24 | uint32(b[1])<<16 | uint32(b[2])<<8 | uint32(b[3])
}

// ---------------------------------------------------------------------------
// Proposal validation
// ---------------------------------------------------------------------------

// ValidateProposalId checks that proposalId is a valid index into the round's proposals list.
func (k Keeper) ValidateProposalId(kvStore store.KVStore, roundID []byte, proposalId uint32) error {
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err
	}
	if int(proposalId) >= len(round.Proposals) {
		return fmt.Errorf("%w: proposal_id %d >= proposals count %d", types.ErrInvalidProposalID, proposalId, len(round.Proposals))
	}
	return nil
}

// ---------------------------------------------------------------------------
// Round status management
// ---------------------------------------------------------------------------

// UpdateVoteRoundStatus reads a vote round, sets its status, and writes it back.
func (k Keeper) UpdateVoteRoundStatus(kvStore store.KVStore, roundID []byte, newStatus types.SessionStatus) error {
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err
	}
	round.Status = newStatus
	return k.SetVoteRound(kvStore, round)
}

// IterateActiveRounds iterates over all stored VoteRounds and calls the
// callback for each round whose status is SESSION_STATUS_ACTIVE.
// The callback receives a pointer to the round; returning true stops iteration.
//
// This performs a full prefix scan of VoteRoundPrefix. This is acceptable
// because the expected cardinality is a few concurrent rounds at most.
func (k Keeper) IterateActiveRounds(kvStore store.KVStore, cb func(round *types.VoteRound) bool) error {
	prefix := types.VoteRoundPrefix
	end := types.PrefixEndBytes(prefix)

	iter, err := kvStore.Iterator(prefix, end)
	if err != nil {
		return err
	}
	defer iter.Close()

	for ; iter.Valid(); iter.Next() {
		var round types.VoteRound
		if err := unmarshal(iter.Value(), &round); err != nil {
			return err
		}
		if round.Status == types.SessionStatus_SESSION_STATUS_ACTIVE {
			if cb(&round) {
				break
			}
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Validation helpers (used by the ante validation pipeline, Phase 3)
// ---------------------------------------------------------------------------

// ValidateRoundForVoting checks that a vote round exists, has ACTIVE status,
// and has not expired (belt-and-suspenders: EndBlocker may not have run yet
// this block).
func (k Keeper) ValidateRoundForVoting(ctx context.Context, roundID []byte) error {
	kvStore := k.OpenKVStore(ctx)
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err // wraps ErrRoundNotFound if missing
	}

	if round.Status != types.SessionStatus_SESSION_STATUS_ACTIVE {
		return fmt.Errorf("%w: status is %s", types.ErrRoundNotActive, round.Status)
	}

	sdkCtx := sdk.UnwrapSDKContext(ctx)
	blockTime := uint64(sdkCtx.BlockTime().Unix())

	if blockTime >= round.VoteEndTime {
		return fmt.Errorf("%w: vote_end_time %d <= block_time %d", types.ErrRoundNotActive, round.VoteEndTime, blockTime)
	}

	return nil
}

// ValidateRoundForShares checks that a vote round exists and is in a state
// that accepts MsgRevealShare. Shares are accepted when the round is ACTIVE
// (with time check) or TALLYING (unconditionally).
func (k Keeper) ValidateRoundForShares(ctx context.Context, roundID []byte) error {
	kvStore := k.OpenKVStore(ctx)
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err
	}

	switch round.Status {
	case types.SessionStatus_SESSION_STATUS_ACTIVE:
		// Belt-and-suspenders: also check time in case EndBlocker hasn't run yet.
		sdkCtx := sdk.UnwrapSDKContext(ctx)
		blockTime := uint64(sdkCtx.BlockTime().Unix())
		if blockTime >= round.VoteEndTime {
			// Time has passed but EndBlocker hasn't transitioned yet — still
			// accept shares (the round will become TALLYING this block).
			return nil
		}
		return nil

	case types.SessionStatus_SESSION_STATUS_TALLYING:
		// Tallying phase: shares are accepted unconditionally.
		return nil

	default:
		return fmt.Errorf("%w: status is %s", types.ErrRoundNotActive, round.Status)
	}
}

// ValidateRoundForTally checks that a vote round exists, is in TALLYING state,
// and that the provided creator matches the session creator.
func (k Keeper) ValidateRoundForTally(ctx context.Context, roundID []byte, creator string) error {
	kvStore := k.OpenKVStore(ctx)
	round, err := k.GetVoteRound(kvStore, roundID)
	if err != nil {
		return err // wraps ErrRoundNotFound if missing
	}

	if round.Status != types.SessionStatus_SESSION_STATUS_TALLYING {
		return fmt.Errorf("%w: status is %s", types.ErrRoundNotTallying, round.Status)
	}

	if round.Creator != creator {
		return fmt.Errorf("%w: creator mismatch: expected %s, got %s", types.ErrInvalidField, round.Creator, creator)
	}

	return nil
}

// ValidateRoundActive checks that a vote round exists and has not expired.
// Deprecated: Use ValidateRoundForVoting or ValidateRoundForShares instead.
// Kept as a thin wrapper to minimize churn in existing callers.
func (k Keeper) ValidateRoundActive(ctx context.Context, roundID []byte) error {
	return k.ValidateRoundForVoting(ctx, roundID)
}

// CheckNullifiersUnique verifies that none of the provided nullifiers have
// already been recorded in the type-scoped, round-scoped nullifier set.
// This runs on every check including RecheckTx, because nullifiers may have
// been consumed by the newly committed block.
func (k Keeper) CheckNullifiersUnique(ctx context.Context, nfType types.NullifierType, roundID []byte, nullifiers [][]byte) error {
	kvStore := k.OpenKVStore(ctx)
	for _, nf := range nullifiers {
		has, err := k.HasNullifier(kvStore, nfType, roundID, nf)
		if err != nil {
			return err
		}
		if has {
			return fmt.Errorf("%w: %x", types.ErrDuplicateNullifier, nf)
		}
	}
	return nil
}

// putUint64BE writes a uint64 in big-endian byte order.
func putUint64BE(b []byte, v uint64) {
	b[0] = byte(v >> 56)
	b[1] = byte(v >> 48)
	b[2] = byte(v >> 40)
	b[3] = byte(v >> 32)
	b[4] = byte(v >> 24)
	b[5] = byte(v >> 16)
	b[6] = byte(v >> 8)
	b[7] = byte(v)
}

// getUint64BE reads a uint64 from big-endian bytes.
func getUint64BE(b []byte) uint64 {
	return uint64(b[0])<<56 | uint64(b[1])<<48 | uint64(b[2])<<40 | uint64(b[3])<<32 |
		uint64(b[4])<<24 | uint64(b[5])<<16 | uint64(b[6])<<8 | uint64(b[7])
}

// ---------------------------------------------------------------------------
// Tally result storage (written by MsgSubmitTally, read by TallyResults query)
// ---------------------------------------------------------------------------

// SetTallyResult stores a finalized tally result for one (round, proposal, decision) tuple.
func (k Keeper) SetTallyResult(kvStore store.KVStore, result *types.TallyResult) error {
	bz, err := marshal(result)
	if err != nil {
		return err
	}
	return kvStore.Set(types.TallyResultKey(result.VoteRoundId, result.ProposalId, result.VoteDecision), bz)
}

// GetTallyResult retrieves a finalized tally result for one (round, proposal, decision) tuple.
func (k Keeper) GetTallyResult(kvStore store.KVStore, roundID []byte, proposalID, decision uint32) (*types.TallyResult, error) {
	bz, err := kvStore.Get(types.TallyResultKey(roundID, proposalID, decision))
	if err != nil {
		return nil, err
	}
	if bz == nil {
		return nil, nil
	}
	var result types.TallyResult
	if err := unmarshal(bz, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetAllTallyResults retrieves all finalized tally results for a vote round.
// Results are returned in key order (proposal_id, then decision).
func (k Keeper) GetAllTallyResults(kvStore store.KVStore, roundID []byte) ([]*types.TallyResult, error) {
	prefix := types.TallyResultPrefixForRound(roundID)
	end := types.PrefixEndBytes(prefix)

	iter, err := kvStore.Iterator(prefix, end)
	if err != nil {
		return nil, err
	}
	defer iter.Close()

	var results []*types.TallyResult
	for ; iter.Valid(); iter.Next() {
		var result types.TallyResult
		if err := unmarshal(iter.Value(), &result); err != nil {
			return nil, err
		}
		results = append(results, &result)
	}
	return results, nil
}
