//! Happy-path E2E voting flow: create session, delegate (real ZKP #1), cast
//! (real ZKP #2), reveal shares (real ZKP #3), wait for TALLYING, auto-tally finalizes.
//! No fixture files — all three ZKP proofs generated inline.
//! ElGamal PK is read from the node's EA keypair (ZALLY_EA_PK_PATH env var).

use base64::Engine;
use blake2b_simd::Params as Blake2bParams;
use e2e_tests::{
    api::{
        self, commitment_tree_next_index, get_json, post_json, post_json_accept_committed,
        tally_has_proposal, wait_for_round_status, SESSION_STATUS_FINALIZED, SESSION_STATUS_TALLYING,
    },
    elgamal::{self, homomorphic_add},
    payloads::{
        create_voting_session_payload, delegate_vote_payload, cast_vote_payload_real,
        reveal_share_payload, ciphertext_to_base64,
    },
    setup::{build_delegation_bundle_for_test, build_van_merkle_witness, build_vote_commitment_merkle_witness},
};
use ff::{Field, PrimeField};
use group::Curve;
use orchard::keys::SpendAuthorizingKey;
use orchard::share_reveal::builder::build_share_reveal;
use orchard::share_reveal::{create_share_reveal_proof, verify_share_reveal_proof};
use orchard::vote_proof::build_vote_proof_from_delegation;
use pasta_curves::pallas;
use rand::SeedableRng;
use rand_chacha::ChaCha20Rng;

const BLOCK_WAIT_MS: u64 = 6000;
// Must match orchard::vote_proof::builder::BALLOT_DIVISOR.
const BALLOT_DIVISOR: u64 = 12_500_000;

fn log_step(step: &str, msg: &str) {
    eprintln!("[E2E] {}: {}", step, msg);
}

fn block_wait() {
    std::thread::sleep(std::time::Duration::from_millis(BLOCK_WAIT_MS));
}

fn round_id_hex(round_id: &[u8]) -> String {
    hex::encode(round_id)
}

/// Run vote-tree-cli with args. Returns stdout or panics on failure.
fn run_tree_cli(args: &[&str]) -> String {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../vote-commitment-tree-client/Cargo.toml");
    let out = std::process::Command::new("cargo")
        .args([
            "run",
            "--quiet",
            "--manifest-path",
            manifest.to_str().unwrap(),
            "--bin",
            "vote-tree-cli",
            "--",
        ])
        .args(args)
        .output()
        .expect("vote-tree-cli");
    if !out.status.success() {
        panic!(
            "vote-tree-cli failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    String::from_utf8_lossy(&out.stdout).into_owned()
}

#[test]
#[ignore = "requires running chain: make init && make start"]
fn voting_flow_full_lifecycle() {
    // ----- Setup: Read EA public key + delegation bundle (once, ~30-60s for proof) -----
    // The EA keypair is generated by `zallyd ea-keygen` during chain init.
    // The node holds the secret key for auto-tally; we read the public key here.
    let ea_pk_path = std::env::var("ZALLY_EA_PK_PATH")
        .expect("ZALLY_EA_PK_PATH env var must point to the EA public key file");
    log_step("Setup", &format!("reading EA public key from {}", ea_pk_path));
    let ea_pk_bytes_vec = std::fs::read(&ea_pk_path)
        .unwrap_or_else(|e| panic!("failed to read EA PK from {}: {}", ea_pk_path, e));
    let ea_pk_bytes: [u8; 32] = ea_pk_bytes_vec.as_slice().try_into()
        .expect("EA PK must be exactly 32 bytes");
    let elgamal_pk = elgamal::unmarshal_public_key(&ea_pk_bytes)
        .expect("failed to parse EA public key");

    log_step("Setup", "generating delegation bundle (K=14 proof may take 30-60s)...");
    let mut rng = ChaCha20Rng::seed_from_u64(42);

    let (delegation_bundle, session_fields, vote_proof_data) =
        build_delegation_bundle_for_test().expect("build_delegation_bundle_for_test");
    log_step("Setup", "delegation bundle ready");

    let (body, created_fields, round_id) =
        create_voting_session_payload(&ea_pk_bytes, 120, Some(session_fields));
    let round_id_hex = round_id_hex(&round_id);

    // ----- Step 1: Create voting session -----
    log_step("Step 1", "create voting session");
    let (status, json) = post_json("/zally/v1/create-voting-session", &body)
        .expect("POST create-voting-session");
    assert_eq!(status, 200, "create session: expected HTTP 200, got {} body={:?}", status, json);
    let code = json.get("code").and_then(|c| c.as_i64()).unwrap_or(-1);
    assert_eq!(code, 0, "create session rejected: {:?}", json.get("log"));
    block_wait();

    // ----- Step 2: Delegate vote (real ZKP #1) -----
    log_step("Step 2", "delegate vote (ZKP #1)");
    let deleg_body = delegate_vote_payload(&round_id, &delegation_bundle);
    let (status, json) = post_json_accept_committed(
        "/zally/v1/delegate-vote",
        &deleg_body,
        || commitment_tree_next_index().map(|n| n >= 1).unwrap_or(false),
    )
    .expect("POST delegate-vote");
    assert_eq!(status, 200, "delegate-vote: expected HTTP 200, got {} body={:?}", status, json);
    assert_eq!(
        json.get("code").and_then(|c| c.as_i64()).unwrap_or(-1),
        0,
        "delegation rejected: {:?}",
        json.get("log")
    );
    block_wait();

    // ----- Step 3: Commitment tree has root after delegation -----
    log_step("Step 3", "commitment tree has root after delegation");
    let mut anchor_height: u32 = 0;
    for _ in 0..10 {
        let (status, json) = get_json("/zally/v1/commitment-tree/latest").expect("GET tree latest");
        assert_eq!(status, 200, "GET commitment-tree/latest: expected 200, got {} body={:?}", status, json);
        if let Some(tree) = json.get("tree") {
            let h = tree.get("height").and_then(|x| x.as_u64()).unwrap_or(0) as u32;
            if h > 0 {
                anchor_height = h;
                assert!(tree.get("root").is_some());
                // Only van_cmx is appended to the tree (cmx_new is not included).
                assert!(tree.get("next_index").and_then(|x| x.as_u64()).unwrap_or(0) >= 1);
                break;
            }
        }
        std::thread::sleep(std::time::Duration::from_secs(2));
    }
    assert!(anchor_height > 0, "tree never populated after delegation");

    // Step 2b: tree at anchor height
    let (status, json) = get_json(&format!("/zally/v1/commitment-tree/{}", anchor_height))
        .expect("GET tree at height");
    assert_eq!(status, 200, "GET tree at height: status={} body={:?}", status, json);
    assert!(json.get("tree").is_some());

    // Step 2c: Rust tree client sync (1 leaf: only van_cmx is appended)
    log_step("Step 2c", "tree CLI sync (1 leaf)");
    let base_url = api::base_url();
    let out = run_tree_cli(&["sync", "--node", &base_url]);
    assert!(out.contains("leaves synced:     1") || out.contains("leaves synced: 1"));
    assert!(out.contains("root match:") || out.contains("OK"));

    // Step 2d: witness position 0
    let out = run_tree_cli(&["witness", "--node", &base_url, "--position", "0"]);
    assert!(out.contains("Witness") && out.contains("bytes"));

    // ----- Step 4: Cast vote (real ZKP #2) -----
    log_step("Step 4", "building vote proof (ZKP #2, K=14 may take 30-60s)...");

    // 4a: Build local commitment tree witness for the VAN (van_cmx at position 0).
    let (van_auth_path, van_position, van_tree_root) = build_van_merkle_witness(
        vote_proof_data.van_comm,
        anchor_height,
    );

    // 4a-verify: Sanity check that the locally computed root matches the on-chain root.
    {
        let (status, json) = get_json(&format!("/zally/v1/commitment-tree/{}", anchor_height))
            .expect("GET tree at height");
        assert_eq!(status, 200);
        let on_chain_root_b64 = json.get("tree")
            .and_then(|t| t.get("root"))
            .and_then(|r| r.as_str())
            .expect("on-chain tree root");
        let on_chain_root_bytes = base64::engine::general_purpose::STANDARD
            .decode(on_chain_root_b64)
            .expect("decode on-chain root");
        let local_root_bytes = van_tree_root.to_repr();
        assert_eq!(
            on_chain_root_bytes,
            local_root_bytes.as_ref(),
            "local tree root does not match on-chain root at height {}",
            anchor_height
        );
    }

    // 4b: Convert the session EA public key (elgamal_pk) to pallas::Affine
    // for the vote proof builder. The EA key was generated by
    // elgamal::keygen which uses pallas::Point::generator().
    let ea_pk_affine = elgamal_pk.0.to_affine();

    // 4c: Generate alpha_v for spend auth randomization (caller controls signing).
    let alpha_v = pallas::Scalar::random(&mut rng);

    // 4c: Generate real vote proof.
    let vote_bundle = build_vote_proof_from_delegation(
        &vote_proof_data.sk,
        1u32,                           // address_index used in delegation
        vote_proof_data.total_note_value,
        vote_proof_data.van_comm_rand,
        vote_proof_data.vote_round_id,
        van_auth_path,
        van_position,
        anchor_height,                  // tree snapshot block height
        1,                              // proposal_id
        1,                              // vote_decision
        ea_pk_affine,
        alpha_v,
        &mut rng,
    )
    .expect("build_vote_proof_from_delegation");

    // 4c-verify: Verify the proof locally (same binary = same VK as prover).
    orchard::vote_proof::verify_vote_proof(&vote_bundle.proof, &vote_bundle.instance)
        .expect("local vote proof verification must pass");
    // Instance must have 11 public inputs (van_nullifier, r_vpk_x, r_vpk_y, vote_authority_note_new, ...).
    assert_eq!(
        vote_bundle.instance.to_halo2_instance().len(),
        11,
        "vote proof instance must have 11 public inputs (condition 4: r_vpk in-circuit)"
    );
    log_step("Step 4", "local verification passed, submitting cast-vote");

    // 4d: Extract public inputs from the instance for the payload (condition 4: r_vpk required).
    let van_nullifier_bytes = vote_bundle.instance.van_nullifier.to_repr();
    let r_vpk_x_bytes = vote_bundle.instance.r_vpk_x.to_repr();
    let r_vpk_y_bytes = vote_bundle.instance.r_vpk_y.to_repr();
    let van_new_bytes = vote_bundle.instance.vote_authority_note_new.to_repr();
    let vote_comm_bytes = vote_bundle.instance.vote_commitment.to_repr();
    let r_vpk_bytes = &vote_bundle.r_vpk_bytes;

    // 4e: Compute canonical sighash for MsgCastVote (must match Go's ComputeCastVoteSighash).
    // Domain || vote_round_id || r_vpk || van_nullifier || vote_authority_note_new ||
    // vote_commitment || proposal_id (4 LE, padded 32) || anchor_height (8 LE, padded 32)
    const CAST_VOTE_SIGHASH_DOMAIN: &[u8] = b"ZALLY_CAST_VOTE_SIGHASH_V0";
    let mut canonical = Vec::new();
    canonical.extend_from_slice(CAST_VOTE_SIGHASH_DOMAIN);
    // vote_round_id: pad to 32 bytes
    let mut buf32 = [0u8; 32];
    let vr_len = round_id.len().min(32);
    buf32[..vr_len].copy_from_slice(&round_id[..vr_len]);
    canonical.extend_from_slice(&buf32);
    // r_vpk: already 32 bytes
    canonical.extend_from_slice(r_vpk_bytes);
    // van_nullifier: 32 bytes
    buf32 = [0u8; 32];
    let vn = van_nullifier_bytes.as_ref();
    buf32[..vn.len().min(32)].copy_from_slice(&vn[..vn.len().min(32)]);
    canonical.extend_from_slice(&buf32);
    // vote_authority_note_new: 32 bytes
    buf32 = [0u8; 32];
    let vn_new = van_new_bytes.as_ref();
    buf32[..vn_new.len().min(32)].copy_from_slice(&vn_new[..vn_new.len().min(32)]);
    canonical.extend_from_slice(&buf32);
    // vote_commitment: 32 bytes
    buf32 = [0u8; 32];
    let vc = vote_comm_bytes.as_ref();
    buf32[..vc.len().min(32)].copy_from_slice(&vc[..vc.len().min(32)]);
    canonical.extend_from_slice(&buf32);
    // proposal_id: 4 bytes LE, padded to 32 bytes
    let mut pid_buf = [0u8; 32];
    pid_buf[..4].copy_from_slice(&1u32.to_le_bytes());
    canonical.extend_from_slice(&pid_buf);
    // anchor_height: 8 bytes LE, padded to 32 bytes
    let mut ah_buf = [0u8; 32];
    ah_buf[..8].copy_from_slice(&(anchor_height as u64).to_le_bytes());
    canonical.extend_from_slice(&ah_buf);

    let sighash_full = Blake2bParams::new().hash_length(32).hash(&canonical);
    let mut sighash = [0u8; 32];
    sighash.copy_from_slice(sighash_full.as_bytes());

    // 4f: Sign the sighash with the randomized voting key (rsk_v = ask_v.randomize(&alpha_v)).
    let ask_v = SpendAuthorizingKey::from(&vote_proof_data.sk);
    let rsk_v = ask_v.randomize(&alpha_v);
    let vote_auth_sig = rsk_v.sign(&mut rng, &sighash);
    let vote_auth_sig_bytes: [u8; 64] = (&vote_auth_sig).into();

    let cast_body = cast_vote_payload_real(
        &round_id,
        anchor_height,
        van_nullifier_bytes.as_ref(),
        r_vpk_x_bytes.as_ref(),
        r_vpk_y_bytes.as_ref(),
        van_new_bytes.as_ref(),
        vote_comm_bytes.as_ref(),
        1,  // proposal_id
        &vote_bundle.proof,
        r_vpk_bytes,
        &sighash,
        &vote_auth_sig_bytes,
    );

    let (status, json) = {
        let mut last = None;
        for attempt in 1..=3 {
            let result = post_json_accept_committed(
                "/zally/v1/cast-vote",
                &cast_body,
                || commitment_tree_next_index().map(|n| n >= 3).unwrap_or(false),
            )
            .expect("POST cast-vote");
            let code = result.1.get("code").and_then(|c| c.as_i64()).unwrap_or(-1);
            if result.0 == 200 && code == 0 {
                last = Some(result);
                break;
            }
            eprintln!(
                "[E2E] Step 4 attempt {}: status={} code={} log={:?}",
                attempt,
                result.0,
                code,
                result.1.get("log").or(result.1.get("error"))
            );
            last = Some(result);
            if attempt < 3 {
                block_wait();
            }
        }
        last.expect("cast-vote: 3 attempts")
    };
    assert_eq!(status, 200, "cast-vote: expected 200, got {} body={:?}", status, json);
    let code = json.get("code").and_then(|c| c.as_i64()).unwrap_or(-1);
    assert_eq!(
        code,
        0,
        "cast-vote rejected: code={} log={:?}",
        code,
        json.get("log").or(json.get("error"))
    );
    // broadcast_tx_sync returns after CheckTx; wait until the cast is committed (tree has 3 leaves).
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(90);
    while std::time::Instant::now() < deadline {
        if commitment_tree_next_index().map(|n| n >= 3).unwrap_or(false) {
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(1500));
    }
    block_wait();

    // ----- Step 5: Tree updated after cast (3 leaves: 1 from delegation + 2 from cast) -----
    log_step("Step 5", "tree updated after cast (3 leaves)");
    let (status, json) = get_json("/zally/v1/commitment-tree/latest").expect("GET tree latest");
    assert_eq!(status, 200, "GET tree latest: status={} body={:?}", status, json);
    let tree = json.get("tree").expect("tree");
    anchor_height = tree.get("height").and_then(|x| x.as_u64()).unwrap_or(0) as u32;
    let next_index = tree.get("next_index").and_then(|x| x.as_u64()).unwrap_or(0);
    assert_eq!(
        next_index,
        3,
        "commitment tree next_index: expected 3 after cast (1 delegation + 2 from cast), got {}; cast may not be in a block yet",
        next_index
    );

    // Step 5b: tree client sync 3 leaves
    let out = run_tree_cli(&["sync", "--node", &base_url]);
    assert!(out.contains("3"));

    // Step 5c: witness position 2
    let out = run_tree_cli(&["witness", "--node", &base_url, "--position", "2"]);
    assert!(out.contains("Witness"));

    // ----- Step 5d: Build vote commitment tree Merkle witness for ZKP #3 -----
    log_step("Step 5d", "building vote commitment tree Merkle witness for ZKP #3");
    let (vc_auth_path, vc_position, vc_tree_root) = build_vote_commitment_merkle_witness(
        vote_proof_data.van_comm,
        vote_bundle.instance.vote_authority_note_new,
        vote_bundle.instance.vote_commitment,
        anchor_height,
    );

    // Verify local root matches on-chain root.
    {
        let (status, json) = get_json(&format!("/zally/v1/commitment-tree/{}", anchor_height))
            .expect("GET tree at height");
        assert_eq!(status, 200);
        let on_chain_root_b64 = json.get("tree")
            .and_then(|t| t.get("root"))
            .and_then(|r| r.as_str())
            .expect("on-chain tree root");
        let on_chain_root_bytes = base64::engine::general_purpose::STANDARD
            .decode(on_chain_root_b64)
            .expect("decode on-chain root");
        let local_root_bytes = vc_tree_root.to_repr();
        assert_eq!(
            on_chain_root_bytes,
            local_root_bytes.as_ref(),
            "local vote commitment tree root does not match on-chain root at height {}",
            anchor_height
        );
    }

    // ----- Step 6: Reveal share 0 (real ZKP #3) -----
    log_step("Step 6", "building share reveal proof (ZKP #3, share 0, K=14 may take 30-60s)...");
    let share_0_bundle = build_share_reveal(
        vc_auth_path,
        vc_position,
        vote_bundle.enc_c1_x,
        vote_bundle.enc_c2_x,
        0, // share_index
        pallas::Base::from(1u64), // proposal_id
        pallas::Base::from(1u64), // vote_decision
        vote_proof_data.vote_round_id,
    );
    let share_0_proof = create_share_reveal_proof(share_0_bundle.circuit.clone(), &share_0_bundle.instance);

    // Local verification
    verify_share_reveal_proof(&share_0_proof, &share_0_bundle.instance)
        .expect("local share reveal proof verification must pass (share 0)");
    log_step("Step 6", "local verification passed, submitting reveal-share");

    let share_0_nullifier = share_0_bundle.instance.share_nullifier.to_repr();
    let enc_share_0_bytes = &vote_bundle.enc_shares_compressed[0];
    let reveal_body = reveal_share_payload(
        &round_id,
        anchor_height,
        share_0_nullifier.as_ref(),
        enc_share_0_bytes,
        1, // proposal_id
        1, // vote_decision
        &share_0_proof,
    );
    let (status, json) = post_json_accept_committed(
        "/zally/v1/reveal-share",
        &reveal_body,
        || tally_has_proposal(&round_id_hex, 1),
    )
    .expect("POST reveal-share");
    assert_eq!(status, 200, "reveal-share: expected 200, got {} body={:?}", status, json);
    assert_eq!(json.get("code").and_then(|c| c.as_i64()).unwrap_or(-1), 0,
        "reveal-share (share 0) rejected: {:?}", json.get("log").or(json.get("error")));
    block_wait();

    // ----- Step 7: Tally has encrypted ciphertext -----
    log_step("Step 7", "tally has encrypted ciphertext");
    let (status, json) = get_json(&format!("/zally/v1/tally/{}/1", round_id_hex))
        .expect("GET tally");
    assert_eq!(status, 200, "GET tally: expected 200, got {} body={:?}", status, json);
    let tally = json.get("tally").expect("tally");
    assert!(tally.get("1").is_some());

    // ----- Step 8: Reveal share 1 (real ZKP #3, while still ACTIVE) -----
    log_step("Step 8", "building share reveal proof (ZKP #3, share 1, K=14 may take 30-60s)...");
    let share_1_bundle = build_share_reveal(
        vc_auth_path,
        vc_position,
        vote_bundle.enc_c1_x,
        vote_bundle.enc_c2_x,
        1, // share_index
        pallas::Base::from(1u64), // proposal_id
        pallas::Base::from(1u64), // vote_decision
        vote_proof_data.vote_round_id,
    );
    let share_1_proof = create_share_reveal_proof(share_1_bundle.circuit.clone(), &share_1_bundle.instance);

    // Local verification
    verify_share_reveal_proof(&share_1_proof, &share_1_bundle.instance)
        .expect("local share reveal proof verification must pass (share 1)");
    log_step("Step 8", "local verification passed, submitting reveal-share");

    let share_1_nullifier = share_1_bundle.instance.share_nullifier.to_repr();
    let enc_share_1_bytes = &vote_bundle.enc_shares_compressed[1];
    let expected_accumulated_b64 = {
        let ct0 = elgamal::unmarshal(enc_share_0_bytes).expect("unmarshal share 0");
        let ct1 = elgamal::unmarshal(enc_share_1_bytes).expect("unmarshal share 1");
        ciphertext_to_base64(&homomorphic_add(&ct0, &ct1))
    };
    let reveal_body_1 = reveal_share_payload(
        &round_id,
        anchor_height,
        share_1_nullifier.as_ref(),
        enc_share_1_bytes,
        1, // proposal_id
        1, // vote_decision
        &share_1_proof,
    );
    let (status, json) = post_json_accept_committed(
        "/zally/v1/reveal-share",
        &reveal_body_1,
        || {
            let (status, json) = match get_json(&format!("/zally/v1/tally/{}/1", round_id_hex)) {
                Ok(x) => x,
                Err(_) => return false,
            };
            let on_chain = (status == 200)
                .then(|| json.get("tally").and_then(|t| t.get("1")).and_then(|v| v.as_str()));
            on_chain
                .flatten()
                .map(|s| s == expected_accumulated_b64)
                .unwrap_or(false)
        },
    )
    .expect("POST");
    assert_eq!(status, 200, "reveal-share (second): expected 200, got {} body={:?}", status, json);
    assert_eq!(json.get("code").and_then(|c| c.as_i64()).unwrap_or(-1), 0,
        "reveal-share (share 1) rejected: {:?}", json.get("log").or(json.get("error")));
    block_wait();

    // ----- Step 9: Accumulated tally matches HomomorphicAdd(share0, share1) -----
    log_step("Step 9", "accumulated tally matches HomomorphicAdd(share0, share1)");
    let ct0 = elgamal::unmarshal(enc_share_0_bytes).expect("unmarshal share 0");
    let ct1 = elgamal::unmarshal(enc_share_1_bytes).expect("unmarshal share 1");
    let expected_accumulated = homomorphic_add(&ct0, &ct1);
    let expected_accumulated_b64 = ciphertext_to_base64(&expected_accumulated);

    let (status, json) = get_json(&format!("/zally/v1/tally/{}/1", round_id_hex)).expect("GET tally");
    assert_eq!(status, 200, "GET tally (step 9): expected 200, got {} body={:?}", status, json);
    let on_chain = json.get("tally").and_then(|t| t.get("1")).and_then(|v| v.as_str()).expect("tally[\"1\"]");
    assert_eq!(on_chain, expected_accumulated_b64, "accumulated ciphertext mismatch");

    // ----- Step 10: Wait for TALLYING -----
    // The voting round can only enter TALLYING after vote_end_time passes.
    // Derive timeout from the actual round end-time (plus a small post-expiry buffer).
    let now_secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("system clock before unix epoch")
        .as_secs();
    let secs_until_vote_end = created_fields.vote_end_time.saturating_sub(now_secs);
    let wait_for_tallying_ms = (secs_until_vote_end.saturating_add(120))
        .saturating_mul(1000)
        .clamp(120_000, 900_000);
    log_step(
        "Step 10",
        &format!("waiting for TALLYING (up to {}s)", wait_for_tallying_ms / 1000),
    );
    wait_for_round_status(&round_id_hex, SESSION_STATUS_TALLYING, wait_for_tallying_ms, 3_000)
        .expect("wait for TALLYING");
    let (_, json) = get_json(&format!("/zally/v1/round/{}", round_id_hex)).expect("GET round");
    assert_eq!(
        json.get("round").and_then(|r| r.get("status")).and_then(|s| s.as_i64()).unwrap(),
        SESSION_STATUS_TALLYING
    );

    // ----- Step 11: Wait for FINALIZED (auto-tally via PrepareProposal) -----
    // The block proposer holds the EA secret key and auto-injects MsgSubmitTally
    // during PrepareProposal. We wait for the round to reach FINALIZED status.
    // The Go El Gamal uses SpendAuthG (matching the ZKP #2 circuit), so
    // BSGS decryption should succeed and auto-tally should finalize.
    log_step("Step 11", "waiting for FINALIZED via auto-tally (up to 60s)");
    wait_for_round_status(&round_id_hex, SESSION_STATUS_FINALIZED, 60_000, 2_000)
        .expect("wait for FINALIZED (auto-tally)");
    let (_, json) = get_json(&format!("/zally/v1/round/{}", round_id_hex)).expect("GET round");
    assert_eq!(
        json.get("round").and_then(|r| r.get("status")).and_then(|s| s.as_i64()).unwrap(),
        SESSION_STATUS_FINALIZED
    );

    // ----- Step 12: Tally results queryable -----
    log_step("Step 12", "tally results queryable");
    let (status, json) = get_json(&format!("/zally/v1/tally-results/{}", round_id_hex))
        .expect("GET tally-results");
    assert_eq!(status, 200, "GET tally-results: expected 200, got {} body={:?}", status, json);
    let results = json.get("results").and_then(|r| r.as_array()).expect("results");
    assert!(!results.is_empty());
    // Auto-tally decrypts ballot-count shares (not raw zatoshi shares).
    // vote_proof splits num_ballots = floor(total_note_value / BALLOT_DIVISOR)
    // into [quarter, quarter, quarter, remainder]. We reveal indices 0 and 1.
    assert_eq!(results[0].get("vote_decision").and_then(|v| v.as_u64()).unwrap_or(0), 1);
    let total_value = results[0].get("total_value").and_then(|v| v.as_u64()).unwrap_or(0);
    let num_ballots = vote_proof_data.total_note_value / BALLOT_DIVISOR;
    let quarter = num_ballots / 4;
    let expected_revealed_total = quarter * 2; // revealed shares 0 and 1
    assert_eq!(
        total_value,
        expected_revealed_total,
        "expected decrypted total from shares[0]+shares[1] = {}, got {}",
        expected_revealed_total,
        total_value
    );

    log_step("Done", "voting flow happy path passed");
}
