#!/bin/bash
set -e

CHAIN_ID="zvote-1"
MONIKER="validator"
HOME_DIR="$HOME/.zallyd"
BINARY="zallyd"
DENOM="uzvote"

echo "=== Initializing Zally Chain ==="

# Remove existing data
rm -rf "$HOME_DIR"

# Init chain
$BINARY init "$MONIKER" --chain-id "$CHAIN_ID" --home "$HOME_DIR"

# Create a validator key
$BINARY keys add validator --keyring-backend test --home "$HOME_DIR"

# Get the validator address
VALIDATOR_ADDR=$($BINARY keys show validator -a --keyring-backend test --home "$HOME_DIR")
VALIDATOR_VALOPER=$($BINARY keys show validator --bech val -a --keyring-backend test --home "$HOME_DIR")
echo "Validator address: $VALIDATOR_ADDR"
echo "Validator valoper: $VALIDATOR_VALOPER"

# Import the deterministic bootstrap admin key (matches E2E test constant).
# In dev mode this account is also set as the vote-manager for convenience.
VM_PRIVKEY="b7e910eded435dd4e19c581b9a0b8e65104dcc4ebca8a1d55aa5c803e72ba2ee"
$BINARY keys import-hex manager "$VM_PRIVKEY" --keyring-backend test --home "$HOME_DIR"
MANAGER_ADDR=$($BINARY keys show manager -a --keyring-backend test --home "$HOME_DIR")
echo "Admin address:     $MANAGER_ADDR"

# Add genesis accounts with tokens
$BINARY genesis add-genesis-account "$VALIDATOR_ADDR" "10000000${DENOM}" \
    --keyring-backend test --home "$HOME_DIR"
$BINARY genesis add-genesis-account "$MANAGER_ADDR" "1000000000${DENOM}" \
    --keyring-backend test --home "$HOME_DIR"

# Create genesis transaction (self-delegation)
$BINARY genesis gentx validator "10000000${DENOM}" \
    --chain-id "$CHAIN_ID" \
    --keyring-backend test \
    --home "$HOME_DIR"

# Collect genesis transactions
$BINARY genesis collect-gentxs --home "$HOME_DIR"

# Patch slashing genesis: zero out slash fractions (no token burn).
# Defaults for signed_blocks_window (100), min_signed_per_window (0.5),
# and downtime_jail_duration (600s) are acceptable.
GENESIS="$HOME_DIR/config/genesis.json"
jq '.app_state.slashing.params.slash_fraction_double_sign = "0.000000000000000000"
  | .app_state.slashing.params.slash_fraction_downtime = "0.000000000000000000"' \
  "$GENESIS" > "${GENESIS}.tmp" && mv "${GENESIS}.tmp" "$GENESIS"

# Validate genesis
$BINARY genesis validate-genesis --home "$HOME_DIR"

# Enable the REST API server (default: disabled).
# Use port 1318 to avoid Cursor IDE occupying 1317.
APP_TOML="$HOME_DIR/config/app.toml"
sed -i.bak '/\[api\]/,/\[.*\]/ s/enable = false/enable = true/' "$APP_TOML"
sed -i.bak 's|address = "tcp://localhost:1317"|address = "tcp://0.0.0.0:1318"|' "$APP_TOML"
# Enable CORS for dev (Vite dev server on port 5173).
sed -i.bak '/\[api\]/,/\[.*\]/ s/enabled-unsafe-cors = false/enabled-unsafe-cors = true/' "$APP_TOML"
rm -f "${APP_TOML}.bak"

# Allow long CheckTx (ZKP verification ~30–60s). Default 10s closes the RPC connection
# before the response, causing "EOF" at the API.
CONFIG_TOML="$HOME_DIR/config/config.toml"
sed -i.bak 's/^timeout_broadcast_tx_commit = .*/timeout_broadcast_tx_commit = "120s"/' "$CONFIG_TOML"
rm -f "${CONFIG_TOML}.bak"

# Generate Pallas keypair for ECIES (ceremony key distribution).
# The secret key is used by PrepareProposal to decrypt the EA key share
# and auto-inject MsgAckExecutiveAuthorityKey.
$BINARY pallas-keygen --home "$HOME_DIR"

# Update [vote] key paths in app.toml (section is auto-generated by the template).
# ea_sk_path is the parent directory for per-round ea_sk files (generated by auto-deal).
EA_SK_PATH="$HOME_DIR/ea.sk"
PALLAS_SK_PATH="$HOME_DIR/pallas.sk"
sed -i.bak "s|^ea_sk_path = .*|ea_sk_path = \"$EA_SK_PATH\"|" "$APP_TOML"
sed -i.bak "s|^pallas_sk_path = .*|pallas_sk_path = \"$PALLAS_SK_PATH\"|" "$APP_TOML"
rm -f "${APP_TOML}.bak"

# Helper defaults are privacy/dev oriented. Benchmark scripts can override them
# via environment variables before invoking this script.
HELPER_API_TOKEN="${ZALLY_HELPER_API_TOKEN:-}"
HELPER_EXPOSE_QUEUE_STATUS="${ZALLY_HELPER_EXPOSE_QUEUE_STATUS:-false}"
HELPER_MEAN_DELAY="${ZALLY_HELPER_MEAN_DELAY:-60}"
HELPER_MIN_DELAY="${ZALLY_HELPER_MIN_DELAY:-90}"
HELPER_PROCESS_INTERVAL="${ZALLY_HELPER_PROCESS_INTERVAL:-5}"
HELPER_MAX_CONCURRENT_PROOFS="${ZALLY_HELPER_MAX_CONCURRENT_PROOFS:-2}"
HELPER_PULSE_URL="${ZALLY_HELPER_PULSE_URL:-}"
HELPER_URL="${ZALLY_HELPER_URL:-}"

# Append [helper] section (not in the default template).
cat >> "$APP_TOML" <<HELPERCFG

###############################################################################
###                         Helper Server                                   ###
###############################################################################

[helper]

# Set to true to disable the helper server.
disable = false

# Optional auth token for POST /api/v1/shares (sent via X-Helper-Token header).
# Empty disables token auth for both share submission and queue-status polling.
api_token = "$HELPER_API_TOKEN"

# Benchmark-only queue metrics endpoint. Keep disabled by default to avoid
# exposing per-round share activity to unauthenticated observers.
expose_queue_status = $HELPER_EXPOSE_QUEUE_STATUS

# Path to the SQLite database file. Empty = default ($HOME/.zallyd/helper.db).
db_path = ""

# Mean of the exponential delay distribution (seconds).
# Shares are delayed by Exp(1/mean) for temporal unlinkability, capped at vote end time.
# Use a short value for testing; production default is 43200 (12 hours).
mean_delay = $HELPER_MEAN_DELAY

# Minimum delay floor (seconds).
min_delay = $HELPER_MIN_DELAY

# How often to check for shares ready to submit (seconds).
process_interval = $HELPER_PROCESS_INTERVAL

# Port of the chain's REST API (used for MsgRevealShare submission).
chain_api_port = 1318

# Maximum concurrent proof generation goroutines.
max_concurrent_proofs = $HELPER_MAX_CONCURRENT_PROOFS

# Heartbeat pulse URL. Empty disables the heartbeat (local dev default).
pulse_url = "$HELPER_PULSE_URL"

# This server's public URL. Empty disables the heartbeat (local dev default).
helper_url = "$HELPER_URL"
HELPERCFG

echo ""
echo "=== Chain initialized successfully! ==="
echo "Validator valoper: $VALIDATOR_VALOPER"
echo "Manager address:   $MANAGER_ADDR"
echo ""
echo "Start with: $BINARY start --home $HOME_DIR"
