// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: zvote/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgSetupVoteRound creates a new voting session.
// vote_round_id is computed on-chain as Blake2b(snapshot_height, snapshot_blockhash, proposals_hash, vote_end_time, nullifier_imt_root, nc_root).
type MsgSetupVoteRound struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Creator           string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SnapshotHeight    uint64                 `protobuf:"varint,2,opt,name=snapshot_height,json=snapshotHeight,proto3" json:"snapshot_height,omitempty"`
	SnapshotBlockhash []byte                 `protobuf:"bytes,3,opt,name=snapshot_blockhash,json=snapshotBlockhash,proto3" json:"snapshot_blockhash,omitempty"`
	ProposalsHash     []byte                 `protobuf:"bytes,4,opt,name=proposals_hash,json=proposalsHash,proto3" json:"proposals_hash,omitempty"`
	VoteEndTime       uint64                 `protobuf:"varint,5,opt,name=vote_end_time,json=voteEndTime,proto3" json:"vote_end_time,omitempty"`
	NullifierImtRoot  []byte                 `protobuf:"bytes,6,opt,name=nullifier_imt_root,json=nullifierImtRoot,proto3" json:"nullifier_imt_root,omitempty"`
	NcRoot            []byte                 `protobuf:"bytes,7,opt,name=nc_root,json=ncRoot,proto3" json:"nc_root,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgSetupVoteRound) Reset() {
	*x = MsgSetupVoteRound{}
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetupVoteRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetupVoteRound) ProtoMessage() {}

func (x *MsgSetupVoteRound) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetupVoteRound.ProtoReflect.Descriptor instead.
func (*MsgSetupVoteRound) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSetupVoteRound) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgSetupVoteRound) GetSnapshotHeight() uint64 {
	if x != nil {
		return x.SnapshotHeight
	}
	return 0
}

func (x *MsgSetupVoteRound) GetSnapshotBlockhash() []byte {
	if x != nil {
		return x.SnapshotBlockhash
	}
	return nil
}

func (x *MsgSetupVoteRound) GetProposalsHash() []byte {
	if x != nil {
		return x.ProposalsHash
	}
	return nil
}

func (x *MsgSetupVoteRound) GetVoteEndTime() uint64 {
	if x != nil {
		return x.VoteEndTime
	}
	return 0
}

func (x *MsgSetupVoteRound) GetNullifierImtRoot() []byte {
	if x != nil {
		return x.NullifierImtRoot
	}
	return nil
}

func (x *MsgSetupVoteRound) GetNcRoot() []byte {
	if x != nil {
		return x.NcRoot
	}
	return nil
}

type MsgSetupVoteRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteRoundId   []byte                 `protobuf:"bytes,1,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSetupVoteRoundResponse) Reset() {
	*x = MsgSetupVoteRoundResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSetupVoteRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetupVoteRoundResponse) ProtoMessage() {}

func (x *MsgSetupVoteRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetupVoteRoundResponse.ProtoReflect.Descriptor instead.
func (*MsgSetupVoteRoundResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSetupVoteRoundResponse) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

// MsgRegisterDelegation corresponds to ZKP #1: delegation registration from keystone-signed action.
type MsgRegisterDelegation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Rk                  []byte                 `protobuf:"bytes,1,opt,name=rk,proto3" json:"rk,omitempty"`                                                                // Randomized spend auth key (32 bytes)
	SpendAuthSig        []byte                 `protobuf:"bytes,2,opt,name=spend_auth_sig,json=spendAuthSig,proto3" json:"spend_auth_sig,omitempty"`                      // RedPallas signature
	SignedNoteNullifier []byte                 `protobuf:"bytes,3,opt,name=signed_note_nullifier,json=signedNoteNullifier,proto3" json:"signed_note_nullifier,omitempty"` // Nullifier of the dummy signed note
	CmxNew              []byte                 `protobuf:"bytes,4,opt,name=cmx_new,json=cmxNew,proto3" json:"cmx_new,omitempty"`                                          // Output note commitment
	EncMemo             []byte                 `protobuf:"bytes,5,opt,name=enc_memo,json=encMemo,proto3" json:"enc_memo,omitempty"`                                       // Encrypted memo
	GovComm             []byte                 `protobuf:"bytes,6,opt,name=gov_comm,json=govComm,proto3" json:"gov_comm,omitempty"`                                       // Governance commitment
	GovNullifiers       [][]byte               `protobuf:"bytes,7,rep,name=gov_nullifiers,json=govNullifiers,proto3" json:"gov_nullifiers,omitempty"`                     // Up to 4 governance nullifiers
	Proof               []byte                 `protobuf:"bytes,8,opt,name=proof,proto3" json:"proof,omitempty"`                                                          // Halo2 ZKP #1
	VoteRoundId         []byte                 `protobuf:"bytes,9,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	Sighash             []byte                 `protobuf:"bytes,10,opt,name=sighash,proto3" json:"sighash,omitempty"` // Client-provided sighash for RedPallas signature verification (32 bytes)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgRegisterDelegation) Reset() {
	*x = MsgRegisterDelegation{}
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterDelegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterDelegation) ProtoMessage() {}

func (x *MsgRegisterDelegation) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterDelegation.ProtoReflect.Descriptor instead.
func (*MsgRegisterDelegation) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgRegisterDelegation) GetRk() []byte {
	if x != nil {
		return x.Rk
	}
	return nil
}

func (x *MsgRegisterDelegation) GetSpendAuthSig() []byte {
	if x != nil {
		return x.SpendAuthSig
	}
	return nil
}

func (x *MsgRegisterDelegation) GetSignedNoteNullifier() []byte {
	if x != nil {
		return x.SignedNoteNullifier
	}
	return nil
}

func (x *MsgRegisterDelegation) GetCmxNew() []byte {
	if x != nil {
		return x.CmxNew
	}
	return nil
}

func (x *MsgRegisterDelegation) GetEncMemo() []byte {
	if x != nil {
		return x.EncMemo
	}
	return nil
}

func (x *MsgRegisterDelegation) GetGovComm() []byte {
	if x != nil {
		return x.GovComm
	}
	return nil
}

func (x *MsgRegisterDelegation) GetGovNullifiers() [][]byte {
	if x != nil {
		return x.GovNullifiers
	}
	return nil
}

func (x *MsgRegisterDelegation) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgRegisterDelegation) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgRegisterDelegation) GetSighash() []byte {
	if x != nil {
		return x.Sighash
	}
	return nil
}

type MsgRegisterDelegationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRegisterDelegationResponse) Reset() {
	*x = MsgRegisterDelegationResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRegisterDelegationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRegisterDelegationResponse) ProtoMessage() {}

func (x *MsgRegisterDelegationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRegisterDelegationResponse.ProtoReflect.Descriptor instead.
func (*MsgRegisterDelegationResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgCreateVoteCommitment corresponds to ZKP #2: create a vote commitment.
type MsgCreateVoteCommitment struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	VanNullifier             []byte                 `protobuf:"bytes,1,opt,name=van_nullifier,json=vanNullifier,proto3" json:"van_nullifier,omitempty"`
	VoteAuthorityNoteNew     []byte                 `protobuf:"bytes,2,opt,name=vote_authority_note_new,json=voteAuthorityNoteNew,proto3" json:"vote_authority_note_new,omitempty"`
	VoteCommitment           []byte                 `protobuf:"bytes,3,opt,name=vote_commitment,json=voteCommitment,proto3" json:"vote_commitment,omitempty"`
	ProposalId               uint32                 `protobuf:"varint,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgCreateVoteCommitment) Reset() {
	*x = MsgCreateVoteCommitment{}
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVoteCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVoteCommitment) ProtoMessage() {}

func (x *MsgCreateVoteCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVoteCommitment.ProtoReflect.Descriptor instead.
func (*MsgCreateVoteCommitment) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgCreateVoteCommitment) GetVanNullifier() []byte {
	if x != nil {
		return x.VanNullifier
	}
	return nil
}

func (x *MsgCreateVoteCommitment) GetVoteAuthorityNoteNew() []byte {
	if x != nil {
		return x.VoteAuthorityNoteNew
	}
	return nil
}

func (x *MsgCreateVoteCommitment) GetVoteCommitment() []byte {
	if x != nil {
		return x.VoteCommitment
	}
	return nil
}

func (x *MsgCreateVoteCommitment) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgCreateVoteCommitment) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgCreateVoteCommitment) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgCreateVoteCommitment) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgCreateVoteCommitmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateVoteCommitmentResponse) Reset() {
	*x = MsgCreateVoteCommitmentResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateVoteCommitmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateVoteCommitmentResponse) ProtoMessage() {}

func (x *MsgCreateVoteCommitmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateVoteCommitmentResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateVoteCommitmentResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{5}
}

// MsgRevealVoteShare corresponds to ZKP #3: reveal vote share (server submits).
type MsgRevealVoteShare struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ShareNullifier           []byte                 `protobuf:"bytes,1,opt,name=share_nullifier,json=shareNullifier,proto3" json:"share_nullifier,omitempty"`
	VoteAmount               uint64                 `protobuf:"varint,2,opt,name=vote_amount,json=voteAmount,proto3" json:"vote_amount,omitempty"`
	ProposalId               uint32                 `protobuf:"varint,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoteDecision             uint32                 `protobuf:"varint,4,opt,name=vote_decision,json=voteDecision,proto3" json:"vote_decision,omitempty"`
	Proof                    []byte                 `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	VoteRoundId              []byte                 `protobuf:"bytes,6,opt,name=vote_round_id,json=voteRoundId,proto3" json:"vote_round_id,omitempty"`
	VoteCommTreeAnchorHeight uint64                 `protobuf:"varint,7,opt,name=vote_comm_tree_anchor_height,json=voteCommTreeAnchorHeight,proto3" json:"vote_comm_tree_anchor_height,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MsgRevealVoteShare) Reset() {
	*x = MsgRevealVoteShare{}
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealVoteShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealVoteShare) ProtoMessage() {}

func (x *MsgRevealVoteShare) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealVoteShare.ProtoReflect.Descriptor instead.
func (*MsgRevealVoteShare) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRevealVoteShare) GetShareNullifier() []byte {
	if x != nil {
		return x.ShareNullifier
	}
	return nil
}

func (x *MsgRevealVoteShare) GetVoteAmount() uint64 {
	if x != nil {
		return x.VoteAmount
	}
	return 0
}

func (x *MsgRevealVoteShare) GetProposalId() uint32 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgRevealVoteShare) GetVoteDecision() uint32 {
	if x != nil {
		return x.VoteDecision
	}
	return 0
}

func (x *MsgRevealVoteShare) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgRevealVoteShare) GetVoteRoundId() []byte {
	if x != nil {
		return x.VoteRoundId
	}
	return nil
}

func (x *MsgRevealVoteShare) GetVoteCommTreeAnchorHeight() uint64 {
	if x != nil {
		return x.VoteCommTreeAnchorHeight
	}
	return 0
}

type MsgRevealVoteShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRevealVoteShareResponse) Reset() {
	*x = MsgRevealVoteShareResponse{}
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRevealVoteShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRevealVoteShareResponse) ProtoMessage() {}

func (x *MsgRevealVoteShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zvote_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRevealVoteShareResponse.ProtoReflect.Descriptor instead.
func (*MsgRevealVoteShareResponse) Descriptor() ([]byte, []int) {
	return file_zvote_v1_tx_proto_rawDescGZIP(), []int{7}
}

var File_zvote_v1_tx_proto protoreflect.FileDescriptor

const file_zvote_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x11zvote/v1/tx.proto\x12\bzvote.v1\x1a\x17cosmos/msg/v1/msg.proto\"\x97\x02\n" +
	"\x11MsgSetupVoteRound\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12'\n" +
	"\x0fsnapshot_height\x18\x02 \x01(\x04R\x0esnapshotHeight\x12-\n" +
	"\x12snapshot_blockhash\x18\x03 \x01(\fR\x11snapshotBlockhash\x12%\n" +
	"\x0eproposals_hash\x18\x04 \x01(\fR\rproposalsHash\x12\"\n" +
	"\rvote_end_time\x18\x05 \x01(\x04R\vvoteEndTime\x12,\n" +
	"\x12nullifier_imt_root\x18\x06 \x01(\fR\x10nullifierImtRoot\x12\x17\n" +
	"\anc_root\x18\a \x01(\fR\x06ncRoot\"?\n" +
	"\x19MsgSetupVoteRoundResponse\x12\"\n" +
	"\rvote_round_id\x18\x01 \x01(\fR\vvoteRoundId\"\xcb\x02\n" +
	"\x15MsgRegisterDelegation\x12\x0e\n" +
	"\x02rk\x18\x01 \x01(\fR\x02rk\x12$\n" +
	"\x0espend_auth_sig\x18\x02 \x01(\fR\fspendAuthSig\x122\n" +
	"\x15signed_note_nullifier\x18\x03 \x01(\fR\x13signedNoteNullifier\x12\x17\n" +
	"\acmx_new\x18\x04 \x01(\fR\x06cmxNew\x12\x19\n" +
	"\benc_memo\x18\x05 \x01(\fR\aencMemo\x12\x19\n" +
	"\bgov_comm\x18\x06 \x01(\fR\agovComm\x12%\n" +
	"\x0egov_nullifiers\x18\a \x03(\fR\rgovNullifiers\x12\x14\n" +
	"\x05proof\x18\b \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\t \x01(\fR\vvoteRoundId\x12\x18\n" +
	"\asighash\x18\n" +
	" \x01(\fR\asighash\"\x1f\n" +
	"\x1dMsgRegisterDelegationResponse\"\xb9\x02\n" +
	"\x17MsgCreateVoteCommitment\x12#\n" +
	"\rvan_nullifier\x18\x01 \x01(\fR\fvanNullifier\x125\n" +
	"\x17vote_authority_note_new\x18\x02 \x01(\fR\x14voteAuthorityNoteNew\x12'\n" +
	"\x0fvote_commitment\x18\x03 \x01(\fR\x0evoteCommitment\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\rR\n" +
	"proposalId\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"!\n" +
	"\x1fMsgCreateVoteCommitmentResponse\"\x9e\x02\n" +
	"\x12MsgRevealVoteShare\x12'\n" +
	"\x0fshare_nullifier\x18\x01 \x01(\fR\x0eshareNullifier\x12\x1f\n" +
	"\vvote_amount\x18\x02 \x01(\x04R\n" +
	"voteAmount\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\rR\n" +
	"proposalId\x12#\n" +
	"\rvote_decision\x18\x04 \x01(\rR\fvoteDecision\x12\x14\n" +
	"\x05proof\x18\x05 \x01(\fR\x05proof\x12\"\n" +
	"\rvote_round_id\x18\x06 \x01(\fR\vvoteRoundId\x12>\n" +
	"\x1cvote_comm_tree_anchor_height\x18\a \x01(\x04R\x18voteCommTreeAnchorHeight\"\x1c\n" +
	"\x1aMsgRevealVoteShareResponse2\xfd\x02\n" +
	"\x03Msg\x12R\n" +
	"\x0eSetupVoteRound\x12\x1b.zvote.v1.MsgSetupVoteRound\x1a#.zvote.v1.MsgSetupVoteRoundResponse\x12^\n" +
	"\x12RegisterDelegation\x12\x1f.zvote.v1.MsgRegisterDelegation\x1a'.zvote.v1.MsgRegisterDelegationResponse\x12d\n" +
	"\x14CreateVoteCommitment\x12!.zvote.v1.MsgCreateVoteCommitment\x1a).zvote.v1.MsgCreateVoteCommitmentResponse\x12U\n" +
	"\x0fRevealVoteShare\x12\x1c.zvote.v1.MsgRevealVoteShare\x1a$.zvote.v1.MsgRevealVoteShareResponse\x1a\x05\x80\xe7\xb0*\x01B&Z$github.com/z-cale/zally/x/vote/typesb\x06proto3"

var (
	file_zvote_v1_tx_proto_rawDescOnce sync.Once
	file_zvote_v1_tx_proto_rawDescData []byte
)

func file_zvote_v1_tx_proto_rawDescGZIP() []byte {
	file_zvote_v1_tx_proto_rawDescOnce.Do(func() {
		file_zvote_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)))
	})
	return file_zvote_v1_tx_proto_rawDescData
}

var file_zvote_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zvote_v1_tx_proto_goTypes = []any{
	(*MsgSetupVoteRound)(nil),               // 0: zvote.v1.MsgSetupVoteRound
	(*MsgSetupVoteRoundResponse)(nil),       // 1: zvote.v1.MsgSetupVoteRoundResponse
	(*MsgRegisterDelegation)(nil),           // 2: zvote.v1.MsgRegisterDelegation
	(*MsgRegisterDelegationResponse)(nil),   // 3: zvote.v1.MsgRegisterDelegationResponse
	(*MsgCreateVoteCommitment)(nil),         // 4: zvote.v1.MsgCreateVoteCommitment
	(*MsgCreateVoteCommitmentResponse)(nil), // 5: zvote.v1.MsgCreateVoteCommitmentResponse
	(*MsgRevealVoteShare)(nil),              // 6: zvote.v1.MsgRevealVoteShare
	(*MsgRevealVoteShareResponse)(nil),      // 7: zvote.v1.MsgRevealVoteShareResponse
}
var file_zvote_v1_tx_proto_depIdxs = []int32{
	0, // 0: zvote.v1.Msg.SetupVoteRound:input_type -> zvote.v1.MsgSetupVoteRound
	2, // 1: zvote.v1.Msg.RegisterDelegation:input_type -> zvote.v1.MsgRegisterDelegation
	4, // 2: zvote.v1.Msg.CreateVoteCommitment:input_type -> zvote.v1.MsgCreateVoteCommitment
	6, // 3: zvote.v1.Msg.RevealVoteShare:input_type -> zvote.v1.MsgRevealVoteShare
	1, // 4: zvote.v1.Msg.SetupVoteRound:output_type -> zvote.v1.MsgSetupVoteRoundResponse
	3, // 5: zvote.v1.Msg.RegisterDelegation:output_type -> zvote.v1.MsgRegisterDelegationResponse
	5, // 6: zvote.v1.Msg.CreateVoteCommitment:output_type -> zvote.v1.MsgCreateVoteCommitmentResponse
	7, // 7: zvote.v1.Msg.RevealVoteShare:output_type -> zvote.v1.MsgRevealVoteShareResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zvote_v1_tx_proto_init() }
func file_zvote_v1_tx_proto_init() {
	if File_zvote_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zvote_v1_tx_proto_rawDesc), len(file_zvote_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zvote_v1_tx_proto_goTypes,
		DependencyIndexes: file_zvote_v1_tx_proto_depIdxs,
		MessageInfos:      file_zvote_v1_tx_proto_msgTypes,
	}.Build()
	File_zvote_v1_tx_proto = out.File
	file_zvote_v1_tx_proto_goTypes = nil
	file_zvote_v1_tx_proto_depIdxs = nil
}
